### ISSUE TITLE
Feature Request: Add Dark Mode Version for the Docs

### ISSUE THREAD

**Issue by NovusOpus** [tailwindlabs/tailwindcss.com#1012]
Currently Tailwind CSS Site/Docs are only available in Light version(Unless I'm missing something?), It seems odd for how easy Tailwind CSS allows you to implement Dark Mode. I was hoping that in V3 Docs Dark mode was going to be implemented.

Now of course this is not a big deal, But considering how much time people spend in the Docs(Some Overnight). Not only for learning how to use Tailwind but also CSS in general, for how well structured and explained everything is, including the CSS equivalent code. To the point that many people(Myself included) consider Tailwind Docs to be one of, if not The Best Docs in the whole internet.

So I think a Dark Mode Version of the Docs is going to be greatly Appreciated.

**Comment by Levminer** [comment]
I wanted to create the same issue, so +1 for dark mode.

**Comment by aeadedoyin** [comment]
Adam mentioned it [here](https://github.com/tailwindlabs/tailwindcss.com/issues/928#issuecomment-917142297) though.

**Comment by reinink** [comment]
Hey ya'll, the docs website [is now available](https://twitter.com/tailwindcss/status/1472945416035520519) in dark mode 🙌

[![image](https://user-images.githubusercontent.com/882133/146788599-94a8a7d8-6428-46c3-a097-caa942a80c87.png)](https://tailwindcss.com/)
