### ISSUE TITLE
v2 Algolia search not working

### ISSUE THREAD

**Issue by staudenmeir** [tailwindlabs/tailwindcss.com#1014]
The Algolia search on https://v2.tailwindcss.com/docs doesn't seem to have any content yet:

<img width="1415" alt="Bildschirmfoto 2021-12-10 um 08 23 27" src="https://user-images.githubusercontent.com/1853169/145534850-5d52ef83-54a4-40b3-b6e6-fda4bb0f7b91.png">

**Comment by darkowic** [comment]
I just started learning yesterday and today I feel like without a hand 😅 Please fix ;)

**Comment by shortcuts** [comment]
Hey,

This issue is due do the domain change, I've fixed the search here: https://github.com/algolia/docsearch-configs/pull/4930

The real solution should be to use the new DocSearch infra credentials on the v2, v1 and v0 websites (same as the v3). cc @bradlc

**Comment by NovusOpus** [comment]
Seems like @bradlc Fixed it Already, Try again

**Comment by bradlc** [comment]
This has been fixed now, thanks for reporting!
