### ISSUE TITLE
Update JIT documentations for Tailwindcss-v3

### ISSUE THREAD

**Issue by mohamadaliakbari** [tailwindlabs/tailwindcss.com#1015]
Is there any configuration for JIT in v3?
For example can I disable it to have all possible tailwind's CSS in my built CSS file?

**Comment by NovusOpus** [comment]
Check [https://github.com/tailwindlabs/tailwindcss/discussions/6256](https://github.com/tailwindlabs/tailwindcss/discussions/6256)

**Comment by deadcoder0904** [comment]
I'm not sure if we should keep using `mode: "jit"` or remove it in v3 as it's not mentioned in the [Upgrade Guide](https://tailwindcss.com/docs/upgrade-guide)?

### tailwind.config.js

```js
module.exports = {
	mode: 'jit',
}
```

**Comment by adamwathan** [comment]
You can remove that now 👍🏻

**Comment by adamwathan** [comment]
@mohamadaliakbari V3 is JIT-only as mentioned in the linked comment, no way to generate every class automatically. Best option if you need something like that is to craft a large safelist of the classes you need 👍🏻

**Comment by deadcoder0904** [comment]
Thanks, Adam, `Upgrade Guide` was missing that so you might wanna update that. Wonderful site, looking cool!

**Comment by tux-tn** [comment]
In that case, shouldn't the JIT configuration docs be removed from the website? ( I'm referring to [this page ](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode)that still uses the `purge` and `mode: jit` syntax)

**Comment by jacobthesheep** [comment]
> In that case, shouldn't the JIT configuration docs be removed from the website? ( I'm referring to [this page ](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode)that still uses the `purge` and `mode: jit` syntax)

Yeah this section needs to be updated and so does [this page](https://tailwindcss.com/docs/upgrade-guide) because it forgets to mention to remove `mode: jit`

**Comment by jacobthesheep** [comment]
@mohamadaliakbari, @adamwathan fixed the issue
