### ISSUE TITLE
Scroll behavior documentation missing

### ISSUE THREAD

**Issue by dcastil** [tailwindlabs/tailwindcss.com#1016]
Just noticed that the documentation for the [scroll-behavior utilities](https://github.com/tailwindlabs/tailwindcss/pull/5388) is missing in the Tailwind v3 documentation. I didn't find it in the sidebar and the URL https://tailwindcss.com/docs/scroll-behavior leads to a 404.

**Comment by reinink** [comment]
Hey thanks for the heads up — no idea how we missed that 😅
