### ISSUE TITLE
Add sticky to the "Quick search..." field

### ISSUE THREAD

**Issue by will83** [tailwindlabs/tailwindcss.com#1018]
In the new v3 documentation, when you want to do a search, and you have already scrolled through the left navigation, you have to scroll up to find the search field. Is it possible to make this field sticky?
I know that there is `cmd+k` to open the modal, but I don't have the automatism.

**Comment by lamka02sk** [comment]
Or just move it back to the top.
Having it in a sidebar is very annoying tbh.

**Comment by reinink** [comment]
We just launched dark mode on the site, and as part of that update the search input is now sticky 💪

https://user-images.githubusercontent.com/882133/146788312-19f85b83-ae9e-4a62-bb00-dd8c78153dc4.mov
