### ISSUE TITLE
Display of deprecated config options in v3 docs

### ISSUE THREAD

**Issue by hood** [tailwindlabs/tailwindcss.com#1024]
At this URL:
https://tailwindcss.com/docs/just-in-time-mode

There Is am example containing usage of
```
mode: 'jit'
```
which AFAIK should be useless in v3, since v3 is on jit mode all the time.

Also, there's mention of
```
purge: [...]
```
which has been deprecated in favor of
```
content: [...]
```

**Comment by NovusOpus** [comment]
Already Fixed by @adamwathan in this [commit](https://github.com/tailwindlabs/tailwindcss.com/commit/28a65bf41f29024c1dc8f9485dd9f5fa01833e67)

Now https://tailwindcss.com/docs/just-in-time-mode redirects to https://v2.tailwindcss.com/docs/just-in-time-mode
