### ISSUE TITLE
Suggestion: add disclaimer about Safari and `text-decoration-color` transitions

### ISSUE THREAD

**Issue by MichaelAllenWarner** [tailwindlabs/tailwindcss.com#1039]
This might be outside of the site's scope, but I wonder if it's worth adding a note about it somewhere, especially if https://github.com/tailwindlabs/tailwindcss/pull/6405 gets accepted.

The issue:

Unlike the other major browsers, Safari seems to do badly with transitions on `text-decoration-color` unless you explicitly set a value for the original state. Compare these two playgrounds in Safari to see what I mean (in the bad example, Safari seems to cycle through `transparent` before hitting the final color):

Bad: https://play.tailwindcss.com/9AcO9GtQfo

Good: https://play.tailwindcss.com/cqV0j6ZaD9

Note that in the bad example, it doesn't help to use `decoration-inherit` or `decoration-current` for the initial value.

So the rule of thumb when using `hover:decoration-` color-utilities with a transition should be to also explicitly set a `decoration-` color, _even if it's the same as the text-color_. (Of course, if the text-decoration-color is the same as the text-color in _both_ states, then you don't need any `decoration-` colors at all.)

**Comment by MichaelAllenWarner** [comment]
The aforementioned https://github.com/tailwindlabs/tailwindcss/pull/6405 has been merged. But see also my [proposal](https://github.com/tailwindlabs/tailwindcss/discussions/6536) for a tweak to Tailwind that might take care of this under the hood.

**Comment by reinink** [comment]
Hey @MichaelAllenWarner thanks for sharing this info, and while this is a legitimate issue with Safari, I think we're going to pass on trying to explain this on the official Tailwind CSS website, at least at this time. I think this issue, plus your discussion, will serve as excellent references for folks who run into this and do a Google search.

Thanks so much either way for taking the time to explain this all 🙏
