### ISSUE TITLE
Place Content content does not match with code examples

### ISSUE THREAD

**Issue by pfried** [tailwindlabs/tailwindcss.com#1043]
The code examples at https://tailwindcss.com/docs/place-content do not match the visuals above. The code uses 3 cols and 6 items but all visuals show 4

![image](https://user-images.githubusercontent.com/1744875/145975797-d963af00-3a07-415a-855c-4f857e5f282e.png)

```
<div class="grid grid-cols-3 gap-4 place-content-center h-48 ...">
  <div>01</div>
  <div>02</div>
  <div>03</div>
  <div>04</div>
  <div>05</div>
  <div>06</div>
</div>
```

**Comment by reinink** [comment]
@pfried Good catch, this has been fixed: 2e01be1e75d12b5f8bca2f5ad40f2ed97f7424a9

Thanks! 🤟
