### ISSUE TITLE
Docs don't work well when javascript is disabled

### ISSUE THREAD

**Issue by roguesherlock** [tailwindlabs/tailwindcss.com#1048]
HI guys, thanks for all the hard work! 

I really appreciate it.

I use Dash app for all my documentation. And recently the docs were updated to tailwind 3. I soon found out that show more button doesn't seem to work. I believe it's due to javascript being disabled for the page. And I can replicate the same on the official website (this) too by disabling javascript. 

I think it would be nice to be able to browse through docs without javascript. I realise this may not be an important issue for you guys. So I'd like to help. How can I help you guys? Should I open up a PR?

<img width="909" alt="Screenshot 2021-12-15 at 00 45 55" src="https://user-images.githubusercontent.com/5683543/146067718-24d4f6fd-beda-4880-8a99-f52b0ede114a.png">
_the button I'm talking about_

Thanks,
Akash

P.S.

I've also raised an issue on the dash app.

https://github.com/Kapeli/Dash-User-Contributions/issues/3525#issue-1080135387

**Comment by adamwathan** [comment]
Hey! Unfortunately no plans to really do anything about this, the website is built with React and to work properly it needs JavaScript enabled.
