### ISSUE TITLE
Tailwind CSS IntelliSense for VSCode requires HTML CSS Support to work

### ISSUE THREAD

**Issue by imannms** [tailwindlabs/tailwindcss.com#1062]
Tailwind CSS IntelliSense for VSCode doesn't work if I don't have HTML CSS Support installed in my VSCode. It seems that the author of the docs assumed everyone had this extension installed.

Please add HTML CSS Support extension as a requirement to the docs so as not to confuse new users.

Link to the page with this issue: https://tailwindcss.com/docs/editor-setup
HTML CSS Support: https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css

**Comment by adamwathan** [comment]
Hey! I don't have that installed:

![image](https://user-images.githubusercontent.com/4323180/146939131-20d78747-d7e5-4764-8ca4-f8106d9ab865.png)

...but the IntelliSense extension does work for me, so this can't be the case. Weird that it was necessary for you — going to close this but at least having this issue around for people to find via Google might help anyone who is for whatever reason in the same situation.
