### ISSUE TITLE
responsive-design.mdx in Dark mode

### ISSUE THREAD

**Issue by dpslwk** [tailwindlabs/tailwindcss.com#1074]
On responsive-design.mdx i'm not seeing the table headings in dark mode

<img width="775" alt="Screenshot 2021-12-20 at 23 09 29" src="https://user-images.githubusercontent.com/234460/146846203-1226a791-cde8-4b68-8b60-ec4522427d1e.png">

**Comment by reinink** [comment]
Hey thanks for pointing this out — this has been fixed: 1ec93b7e220c78dcb53e9b1f5cecf53694dfdbc0

![image](https://user-images.githubusercontent.com/882133/146862006-1d3380ef-26c5-4009-8c53-d42bd6c4ee13.png)
