### ISSUE TITLE
The layout looks a little messy

### ISSUE THREAD

**Issue by feri-irawan** [tailwindlabs/tailwindcss.com#1076]
Because of the title, it may need improvement or use of 'break-words'

![Screenshot_20211221_112630](https://user-images.githubusercontent.com/57158078/146866316-b8a211ee-8389-4924-9a4f-6c3159035732.jpg)

**Comment by reinink** [comment]
Hey thanks for the heads up on this, I've corrected this: d15a3a03f29afcde3625ff55d0dce4a9eca299ed 👍
