### ISSUE TITLE
Suggestion: Add Github repo links for official plugins

### ISSUE THREAD

**Issue by adhamfarrag** [tailwindlabs/tailwindcss.com#1079]
Hello, Always grateful for the huge work you do. I believe official plugins URLs were added in the last design. Github icon next to Plugin name will be easier to access them.

**Comment by 4ndre4s** [comment]
Should this be implemented? If so, can I do it?

**Comment by reinink** [comment]
Hey thanks for this feedback. For what it's worth right now the forms, aspect ratio and line clamp plugins all link directly to GitHub, it's only the typography plugin that doesn't:

<img width="310" alt="Screen Shot 2022-02-24 at 2 38 07 PM" src="https://user-images.githubusercontent.com/882133/155595052-591211e4-b5eb-4abd-a513-64f1a2a85eed.png">

I've gone ahead (8b9f69a93a5a1b055dc8c1dcfa06f5ca2863b89c) and added a GitHub icon and link to the typography plugin page as well, beside the title:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/882133/155597921-095ed7dd-ee8c-4fb3-ac91-00e5dcc05d65.png">

We plan to eventually move all the plugin documentation to the Tailwind CSS website, similar to the typography plugin, so having this in place will be handy for those plugins as well 👍 

Hope that helps!
