### ISSUE TITLE
DOC header text info

### ISSUE THREAD

**Issue by syedsimanta03** [tailwindlabs/tailwindcss.com#1088]
Thanks for this amazing tool. But I have a question:

1.  https://tailwindcss.com/docs/justify-items
- ### Flexbox & Grid

Justify Items
In this page why it says Flexbox & Grid when **justify-items** is for **CSS grid property only**? Same with **justify-self, place-content, place-items, place-self** 

Which file on github contains this text - Flexbox & Grid?

**Comment by adamwathan** [comment]
Hey! That’s the sidebar category title:

![DD1B46C7-602E-4ED2-A516-31DC92DC109B](https://user-images.githubusercontent.com/4323180/147349662-87be3eff-7fa0-41a0-ba27-f0f0facb3f79.png)

It’s not saying it necessarily works in flexbox, just that the parent category for that page is “Flexbox and Grid”. No plans to change this right now, thanks though.
