### ISSUE TITLE
Suggestion: Add plugin support to Tailwind CDN documentation

### ISSUE THREAD

**Issue by kylebutts** [tailwindlabs/tailwindcss.com#1092]
I know that the Play CDN has support for first-class Tailwind plugins from the 3.0.0alpha1 release notes, but I don't see this on the site for installation. Could be helpful to include that information so people could try out these features more easily. Thanks for the awesome product!! :-)

https://cdn.tailwindcss.com/3.0.0?plugins=forms@0.4.0,typography@0.5.0,aspect-ratio@0.4.0,line-clamp@0.3.0

**Comment by bradlc** [comment]
Hey @kylebutts. Thanks for the suggestion! It looks like this was added in #1060, and you can now see it mentioned in step 4 on this page: https://tailwindcss.com/docs/installation/play-cdn 🤙
