### ISSUE TITLE
Suggestion: Add Vue installation guide

### ISSUE THREAD

**Issue by OyewoleOyedeji** [tailwindlabs/tailwindcss.com#1093]
I have found the official method of integrating tailwindcss and vuejs together.

The instructions are found here (for Vue 2):
https://www.npmjs.com/package/vue-cli-plugin-tailwind

For Vue 3:

1. Globally update/install Vue's CLI
`npm install -g @vue/cli@next`

2. Create a new project
`vue create octocat-adventures`

3. Install the tailwindcss plugin
`vue add tailwind@next`
or you can use the `Vue UI (not advisable)`

4. Generate the `tailwind.config.js` and `postcss.config.js`

5. Run the server

I would love for someone to add this to the documentation, so Vue devs don't have to be looking for the proper ways of setting the project up

**Comment by felix-pb** [comment]
If you're using Vue 3 + Vite, the documentation contains an "official" guide: https://tailwindcss.com/docs/guides/vite

**Comment by OyewoleOyedeji** [comment]
Well there isn't for those using Vue projects from scratch or the cli

**Comment by jtuchel** [comment]
I came up with a duplicate of this one, sorry :)

I will mention your issue in the discussion

**Comment by OyewoleOyedeji** [comment]
thanks

**Comment by ohmmolina** [comment]
The `vue add tailwind@next` is in project folder or doesn't matter?

**Comment by OyewoleOyedeji** [comment]
You now run `vue add tailwind` without the tag, as Vue 3 is now the latest default

**Comment by adamwathan** [comment]
Thanks for the suggestion, going to stick to just our Vite + Vue 3 guide for now though.
