### ISSUE TITLE
There seems to be some merge conflicts in the Chinese document

### ISSUE THREAD

**Issue by xiaoxiaobaibaibai** [tailwindlabs/tailwindcss.com#1095]
see https://www.tailwindcss.cn/docs/extracting-components
![tailwind](https://user-images.githubusercontent.com/27053812/147542623-ea26e10d-da2e-485e-ab9c-7ae6c452be7b.jpg)

**Comment by adamwathan** [comment]
We don’t maintain that site unfortunately, not sure who is running that 😕
