### ISSUE TITLE
Docs in v3.0.7 missing some part confuses reader

### ISSUE THREAD

**Issue by Benbinbin** [tailwindlabs/tailwindcss.com#1098]
[the Plugins chapter](https://tailwindcss.com/docs/plugins) of v3.0.7 version docs miss the **Providing default options** part, which is shown in [v2.2.16](https://v2.tailwindcss.com/docs/plugins#providing-default-options).

But in [Exposing options](https://tailwindcss.com/docs/plugins#exposing-options) part of v3.0.7 version docs, it still provides a the example which contains default theme 

```js
const plugin = require('tailwindcss/plugin')

module.exports = plugin.withOptions(function (options) {
  return function({ addComponents }) {
    const className = options.className ?? 'markdown'

    addComponents({
      [`.${className}`]: {
        // ...
      }
    })
  }
}, 
// 👉 it provide a default theme
function (options) {
  return {
    theme: {
      markdown: {
        // ...
      }
    },
  }
})
```

if the readers don't read the previous version doc, it can confuse them.

**Comment by adamwathan** [comment]
Just following up here — you're totally right we need to add something to the updated documentation explaining the second plugin argument that shows you how to provide default config options for your plugin 👍🏻 Will try to get that in next week.

**Comment by adamwathan** [comment]
Added some new content to the documentation here:

https://github.com/tailwindlabs/tailwindcss.com/commit/018f236b8449804eca562a44cddf6b91a18e1990

Thanks for raising this!
