### ISSUE TITLE
Broken internal link on "hover-focus-and-other-states" page

### ISSUE THREAD

**Issue by MichaelAllenWarner** [tailwindlabs/tailwindcss.com#1101]
Page: [hover-focus-and-other-states](https://tailwindcss.com/docs/hover-focus-and-other-states)

Problem: In the Quick Reference section at the bottom, the `open` link points to `#open` but the actual id is `#open-closed-state`

**Comment by adamwathan** [comment]
Fixed thanks! In the future btw you can make tiny changes like this really quickly with the "Edit this page on GitHub" link at the bottom of each page:

![image](https://user-images.githubusercontent.com/4323180/147834735-f7802edb-4fff-477e-add8-58d73e64ec0a.png)
