### ISSUE TITLE
Official website document using Google Translation error

### ISSUE THREAD

**Issue by xld1393679430** [tailwindlabs/tailwindcss.com#1102]
**What version of Tailwind CSS are you using?**

 v3.0.7

**What browser are you using?**

Edge

**What operating system are you using?**

Windows

**Describe your issue**

Documents using Google Translate will report errors, you can try to scroll up and down the page can be reproduced
![1](https://user-images.githubusercontent.com/22445609/147638364-b233b5d2-acfa-4dd6-b915-d920dc9b55f6.png)

**Comment by reinink** [comment]
Hey, sorry that you're running into this, but i'm not sure this is an issue with the Tailwind CSS website. I just tried loading the site on Google Translate, and it [seems to work fine](https://tailwindcss-com.translate.goog/docs/reusing-styles?_x_tr_sl=auto&_x_tr_tl=zh-CN&_x_tr_hl=en-US). I'm going to go ahead an close this issue, but let us know if you're able to confirm that it is in fact an issue with our site and we can revisit it 👍 

![image](https://user-images.githubusercontent.com/882133/148396477-333a72e1-18a4-40a8-9398-3135b376fa24.png)
