### ISSUE TITLE
Suggestion: Update vite installation guide for upcoming vuejs.org website

### ISSUE THREAD

**Issue by felix-pb** [tailwindlabs/tailwindcss.com#1108]
Evan You [announced on Twitter](https://twitter.com/youyuxi/status/1474751849467023365) that the official website will switch to Vue 3 in early-mid January 2022 🎉

The new documentation suggests to create vite-based projects with `npm init vue@latest` instead of `npm init vite@latest`, which lets the user choose the project configuration just like with vue-cli. I suspect most users will elect to add ESLint for code quality and add Prettier for code formatting. However, the default setup is incompatible with the official [Install Tailwind CSS with Vue 3 and Vite](https://tailwindcss.com/docs/guides/vite) guide. In particular, when running `npm run lint`, it generates these errors:
```
/<redacted>/vue-project/postcss.config.js
  1:1  error  'module' is not defined  no-undef

/<redacted>/vue-project/tailwind.config.js
  1:1  error  'module' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)
```

Although I'm not sure that's the best solution, a quick fix is to add `node: true` to `.eslintrc.cjs`:
```
  env: {
    "vue/setup-compiler-macros": true,
    node: true,
  },
```

Just a heads up since many Vue + Tailwind developers will probably run into this when the official website makes the switch later this month!

**Comment by reinink** [comment]
Hey there! Thanks for sharing this information — I was able to reproduce this issue when using `npm run lint`.

Your workaround is good. Another option is to just add this comment at the top of `postcss.config.js` and `tailwind.config.js` files:

```js
/* eslint-env node */
```

I'm not sure we should update our guide though, as this is pretty specific to ESLint, and we really want to keep our guides as short and focused as possible. However, just having this issue exist will hopefully help others who bump into this.

Thanks for sharing 👍
