### ISSUE TITLE
Update Nextjs tailwindcss example

### ISSUE THREAD

**Issue by Anishpras** [tailwindlabs/tailwindcss.com#1110]
Hey! Recently Nextjs updated their tailwind CSS example with typescript support. So Can I work on the documentation to update it?

**Comment by reinink** [comment]
Hey there!

Thanks for your interest in helping making the Tailwind CSS docs better! However, I'm not sure it makes sense to introduce TypeScript to the [Next.js framework guide](https://tailwindcss.com/docs/guides/nextjs) (I'm assuming that's what you're talking about). We're really trying to keep the framework guides as minimal as possible, without any optional steps.

Feel free to clarify if you were thinking something different 👍 

Thanks either way!
