### ISSUE TITLE
tailwindcss permission denied

### ISSUE THREAD

**Issue by lagenceoueb** [tailwindlabs/tailwindcss.com#1111]
Hi,

i'm on a local, lando based, WordPress install.
Since I want to run watch, I have this issue :
`sh: 1: tailwindcss: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! tailpress@2.0.0 watch:css-app: `tailwindcss -i ./resources/css/app.css -o ./css/app.css --postcss --watch`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the tailpress@2.0.0 watch:css-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-01-06T10_15_49_834Z-debug.log
`

Some id to help ?
Thanks in advance

**Comment by reinink** [comment]
Glad you got it figured out 👍
