### ISSUE TITLE
Overriding `default` in v3 doesn't mention it should be UPPERCASE

### ISSUE THREAD

**Issue by igorkrup** [tailwindlabs/tailwindcss.com#1114]
I've recently updated to v3. I previously have some default boxShadow styles overridden with `default` key. But now it should be `DEFAULT`. Also, bit weird that only for boxShadow should be uppercase?
With lowercase it does not produce `.shadow` class in css. 
Documentation or migration guide does not mention that.

**Comment by reinink** [comment]
Hey!

So this actually changed in Tailwind CSS `v.2.0`. You can find that PR here:

https://github.com/tailwindlabs/tailwindcss/pull/2580

This was included in the migration guide for 2.0, which you can find here:

https://v2.tailwindcss.com/docs/upgrading-to-v2#update-default-theme-keys-to-default

Hope that helps 👍

**Comment by kevinruscoe-popcreative** [comment]
Sorry for reopening this, it seems the v3 documentation doesn't mention the DEFAULT keyword at all, is hat intentional?

**Comment by reinink** [comment]
@kevinruscoe-popcreative Hey! It is actually mentioned on the [theme page](https://tailwindcss.com/docs/theme#core-plugins) under "Core plugins":

> You’ll notice that using a key of DEFAULT in the theme configuration created the class rounded with no suffix. This is a common convention in Tailwind and is supported by all core plugins.

Easy to miss though. You can also see examples of using `DEFAULT` in our default config here:

https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js
