### ISSUE TITLE
Sibling selector variant - add documentation for v3

### ISSUE THREAD

**Issue by Triloworld** [tailwindlabs/tailwindcss.com#1116]
No page exist in v3 documentation although is working correct.

This is on v2 what we use on v3 engine:
https://v2.tailwindcss.com/docs/just-in-time-mode#sibling-selector-variants
 
Is only JIT or will be now generated like any other class in production mode?

**Comment by adamwathan** [comment]
Hey! It’s documented already, first result when you search “sibling” in the docs:

https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state

Thanks though!
