### ISSUE TITLE
document  merge conflict problem

### ISSUE THREAD

**Issue by xiaoliuzhuan** [tailwindlabs/tailwindcss.com#1126]
The official document appears code merge conflict problem, please fix it

![image](https://user-images.githubusercontent.com/23628196/148918041-77c4ac96-f6d4-444d-a182-05590b0c0423.png)

**Comment by reinink** [comment]
Hey there! Thanks for reporting this, but we don't manage the [Chinese translation](https://www.tailwindcss.cn) of the website — this is a community project. Please report it with the maintainers of that fork 👍
