### ISSUE TITLE
v1 docs take you to v3 when trying to navigate to v2

### ISSUE THREAD

**Issue by hacknug** [tailwindlabs/tailwindcss.com#1128]
When browsing the docs for v1 and using the version dropdown to navigate to v2 docs, you're taken to the v3 docs. This is because v2 was previously hosted on the root domain and it now sits under the v2 subdomain.

Maybe it would be a good idea to also add v3 to the dropdown in case users land on those links for whatever reason.

**Comment by reinink** [comment]
Hey, thanks for the heads up on this!

## v1.tailwindcss.com

I've updated the v1 docs to have v3 listed in the dropdown, and have corrected the v2 address: 3bb724becde0a4c0cc63f3a3707af01155f143fc

![image](https://user-images.githubusercontent.com/882133/148976553-472b792d-80d9-4969-80e0-9f8bebf1dbf6.png)

## v2.tailwindcss.com

I've also updated the v2 docs to have v3 listed in the dropdown: 565b233b72598683d534d66409f9073b9291e6ab

![image](https://user-images.githubusercontent.com/882133/148976643-7973aec4-76b3-439e-8836-9754f65fee18.png)
