### ISSUE TITLE
Document how to add peer/group variants as well

### ISSUE THREAD

**Issue by ModProg** [tailwindlabs/tailwindcss.com#1144]
I need to have a variant enabled when the `peer` is not focused, so I added:
```js
addVariant('peer-unfocused', ':merge(.peer):not(:focus) ~ &')
```

but to find out how to do this, I had to take a look at the tailwind source code. Maybe that is just my inexperience with css selectors, but I think this would be a nice addition to the documentation here: https://tailwindcss.com/docs/plugins#adding-variants

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We will definitely add more docs on the new `addVariant` API. Took note of it and we will make sure that it is present in the future 👍

**Comment by hazae41** [comment]
While the full documentation is being written, you may add a link to [your PR about the new addVariant API](https://github.com/tailwindlabs/tailwindcss/pull/5809); which is quite complete but somewhat hard to find for newcomers 👍
