### ISSUE TITLE
v3 docs don't include `!` important modifier

### ISSUE THREAD

**Issue by olets** [tailwindlabs/tailwindcss.com#1151]
The v3 docs don't document the `!` modifier (https://v2.tailwindcss.com/docs/just-in-time-mode#built-in-important-modifier) (see the interactive search  on the site, and/or https://github.com/tailwindlabs/tailwindcss.com/search?q=important).

Happy to contribute to getting it in there if that's helpful. I'm not sure where it would go.

I have not gone through the JIT announcement point by point to make sure that everything else made it into the v3 docs.

**Comment by reinink** [comment]
@olets Hey good catch, you're right, this was lost during the redesign. I've added it back in (6c0ff0dc2d8012dbfc0b6fbe31d8cb6f008c8c3c) on the configuration page for now in the "Important" section: https://tailwindcss.com/docs/configuration#important-modifier

This maybe isn't the *best* place for it — eventually we'd like to add a dedicated specificity page to the site, which would be a better home for this content — but this will do for now.
