### ISSUE TITLE
Document code blocks lack replication capabilities

### ISSUE THREAD

**Issue by wsdo** [tailwindlabs/tailwindcss.com#1152]
Document code blocks lack replication capabilities

**Comment by reinink** [comment]
Hey, I'm not really sure what you're after here. Simply repeating the title in the description doesn't really help us understand what the issue is here 😕

When posting issues, please take the time to fully explain the problem, as it makes our work as maintainers a lot easier.

**Comment by wsdo** [comment]
![image](https://user-images.githubusercontent.com/9738969/150768806-eef3b6c6-470a-4419-9cb7-aea6aaee5726.png)
