### ISSUE TITLE
There is no search or header component on the website

### ISSUE THREAD

**Issue by BuiTanLan** [tailwindlabs/tailwindcss.com#1153]
**What browser are you using?**

Edge  97.0.1072.62

**What operating system are you using?**

Windows 10

**Describe your issue**

There is no search or header component on the website, so the website is useless
![image](https://user-images.githubusercontent.com/41078323/150063400-07cf5ee9-4f6c-454a-b714-ce361b72e61a.png)
![image](https://user-images.githubusercontent.com/41078323/150063473-1c940248-1097-4f5e-a6d7-d0af11ac6a46.png)

**Comment by reinink** [comment]
@BuiTanLan We've tried to reproduce this issue on multiple browsers and operating systems now without success. As @adamwathan suggests, this might be related to a browser extension that's causing issues.

I just tried it myself on Windows 10 on Edge 97.0.1072.55, and there are no issues (see below).

I've sometimes seen content get hidden like this in the past if it used the wrong class name, resulting in it getting flagged by an ad blocker. For example, `.banner`. However, this particular markup just uses Tailwind classes.

Really not sure where to go from here, so I am going to close this issue for now, but if anyone can provide more information on what's going wrong here, I'd be happy to have another look!

![image](https://user-images.githubusercontent.com/882133/150407654-a1464afe-505d-4e3c-894f-1050a9fe20ec.png)
