### ISSUE TITLE
Showing full tailwind.config.js

### ISSUE THREAD

**Issue by GetOrders** [tailwindlabs/tailwindcss.com#1162]
Can we please have the full tailwind config file options under node_modules/tailwindcss/stubs/defaultConfig.stub.js be linked in the documentation?

It is hard to find all config options otherwise on the internet :)

P.S. love this framework and am an avid fan of TailwindUI

**Comment by reinink** [comment]
Hey thanks for this suggestion! We do link to this on the "Theme Configuration" page, here: https://tailwindcss.com/docs/theme#customizing-the-default-theme

Hope that helps 👍
