### ISSUE TITLE
Suggestion: In the Documentation, scroll to the currently selected topic in the toc menu

### ISSUE THREAD

**Issue by MauriceArikoglu** [tailwindlabs/tailwindcss.com#1166]
When looking through the documentation, I often find myself looking for some utility class like for example "grid". And then I want to see the associated options there are, usually these are subsumized under the "grid" parent documentation entry. If I want to see the documentation table of contents and look for similar items / children styles, I have to scroll in the toc until I find the currently marked entry, and then look for the associated options nearby.
I think it would improve the UX a lot, if we would have the toc scroll to the selected item automatically, instead of having to manually search in the long list for where I am currently.

**Comment by reinink** [comment]
Hey @MauriceArikoglu!

> I think it would improve the UX a lot, if we would have the toc scroll to the selected item automatically

So maybe I'm not fully understanding what you're saying, but the site already auto-scrolls to the current position in the main (left) navigation on page load. I've recorded a quick video to illustrate this:

https://user-images.githubusercontent.com/882133/155590084-04ff91aa-00e1-48b4-932b-c16e43290c3a.mov

From there you can click between pages and the main menu stays in the current position, maintaining your context.

I will admit that the Tailwind CSS documentation has become massive, and it's certainly been a challenge to design the website in such a way that information is easy to find and nicely organized. I always recommend that folks use our global search to get around (press Command-K to open it from anywhere on the site), as it's a real time saver 👍

Hope that helps!
