### ISSUE TITLE
Pasting code block issue in SvelteKit Installation guide page

### ISSUE THREAD

**Issue by waleedmumtaz** [tailwindlabs/tailwindcss.com#1168]
Page link: [Install Tailwind CSS with SvelteKit](https://tailwindcss.com/docs/guides/sveltekit)

---
After copying the code block by clicking the copy button shown in the screenshots below and pasting it, the first characters of each line seem to chop off.

![image](https://user-images.githubusercontent.com/32681782/151532402-f936b8df-fe19-4f1f-8521-66b42e3d6637.png)
```svelte
<!-- Expected result on pasting the code block -->
<script>
  import "../app.css";
</script>

<slot />

<!-- Actual result after pasting the code block -->
script>
 import "../app.css";
/script>

slot />
```

---
Similarly for this code block:
![image](https://user-images.githubusercontent.com/32681782/151532773-feeee48b-0163-454a-817c-dd770a5376c4.png)
```svelte
<!-- Expected result on pasting the code block -->
<h1 class="text-3xl font-bold underline">
  Hello world!
</h1>

<!-- Actual result after pasting the code block -->
h1 class="text-3xl font-bold underline">
 Hello world!
/h1>
```

**Comment by thecrypticace** [comment]
Hey, definitely not seeing this over here. Can you give us more details on your browser / operating system / etc…?

**Comment by thecrypticace** [comment]
That's really weird! I'm on the latest version of chrome over here but on x86_64 instead of an arm Mac and not seeing it. That's wild.

**Comment by reinink** [comment]
Okay, this gets even more weird. Same thing happens on Safari and Firefox — so this is obviously an operating system level issue.

**Comment by thecrypticace** [comment]
Okay, I've reproduced it now. pebkac error over here. Looking into it!

**Comment by waleedmumtaz** [comment]
@thecrypticace I am on Windows 10 Version 21H1 (OS Build 19043.1466)
I can reproduce it on both my latest versions of Google Chrome (Version 97.0.4692.99 (Official Build) (64-bit)) and Mozilla Firefox (96.0.3 (64-bit)).

**Comment by thecrypticace** [comment]
Found and fixed the problem!

So, we remove the characters `+`, `>`, and `-` from be beginning of code snippets as we use those for line highlighting/callouts across the website. However, the regex we used was `/^[+->]/gm` which was treated as a range instead of three individual characters. Swap the characters `-` and `>` in the regex and all is fixed. Thanks for the report. This was a fun one!
