### ISSUE TITLE
Table of contents cannot link to heading "Content"

### ISSUE THREAD

**Issue by jacobPARIS** [tailwindlabs/tailwindcss.com#1173]
When the user clicks the "Content" item in the table of contents, they are brought to the top of the page instead of the heading they're looking for

## Why this happens

The table of contents uses hash anchor links to link to the ID for each specific heading, which are auto-generated based on the heading contents. One heading on this page is "Content" and has an ID "#content"

https://tailwindcss.com/docs/configuration#content

The docs engine wraps the rendered markdown in a div that also has an ID "#content"

Clicking the link takes the user to the first matching ID in the page

## Potential fixes

- Change the ID of the blog-wrapper to something less likely to conflict with documentation headings
- Change the content heading to something else
- Replace the `### Content` with an MDX `<h3>` element with a custom ID. This may not work with the table of contents generator and may fall out of sync with future theme changes.

**Comment by bradlc** [comment]
Nice catch, thanks for reporting! I have changed the wrapper ID to `content-wrapper` 👍
