### ISSUE TITLE
Delay animation on breakpoint not functional

### ISSUE THREAD

**Issue by Sljcom** [tailwindlabs/tailwindcss.com#1196]
Tested on personal and codepen project. delay-75 works on breakpoints, but delay-0 does not work.

Google Chrome Mac 98.0.4758.102

<div class="transition duration-300 delay-1000 md:delay-0">
  
</div>

**Comment by adamwathan** [comment]
Hey! I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
