### ISSUE TITLE
Suggestion: Update Doc Example - Borders > Ring Offset Width

### ISSUE THREAD

**Issue by jatindhola** [tailwindlabs/tailwindcss.com#1206]
Borders > Ring Offset Width

**Setting the ring offset width**

Needs to change in html because preview shows button name.

From:
<button class="... ring ring-pink-500 ring-offset-0">ring-offet-0</button>
<button class="... ring ring-pink-500 ring-offset-2">ring-offset-2</button>
<button class="... ring ring-pink-500 ring-offset-4">ring-offset-4</button>

To:
<button class="... ring ring-pink-500 ring-offset-0">Button A</button>
<button class="... ring ring-pink-500 ring-offset-2">Button B</button>
<button class="... ring ring-pink-500 ring-offset-4">Button C</button>

**Changing the offset color**

preview shows ring-offset-pink-500 and in html ring-offset-pink-100 class is used.

**Comment by simonswiss** [comment]
Hey @jatindhola,

Thank you very much for that 🙏

I have fixed your first suggestion here:

https://github.com/tailwindlabs/tailwindcss.com/commit/1bb51c1eee1928fe089d2fcdb28bf7ee5993528a

and here:

https://github.com/tailwindlabs/tailwindcss.com/commit/fa33cfbd30986d3a1f8449e9cf9a607ed50d5095
