### ISSUE TITLE
chore(nuxt): The filename ./nuxt.config.{js,ts} leads to the fact that the .nuxt output folder is observed

### ISSUE THREAD

**Issue by naschidaniel** [tailwindlabs/tailwindcss.com#1208]
https://tailwindcss.com/docs/guides/nuxtjs#header

The following setting causes that the `.nuxt` is observed. This leads to a continuous reloading process. This can be prevented by changing it to the complete `nuxt.config.js` file name.

Configure your template paths
```
module.exports = {
  content: [
    "./nuxt.config.js",
    "./nuxt.config.ts",
  ],
}
```

Dependencies:
nuxt: ^2.15.3
tailwindcss": 3.0.23

**Comment by adamwathan** [comment]
Hey! Just tested this and I can't reproduce it, I don't see any continuous reloading process and the behavior is the same with both `./nuxt.config.{js,ts}` and with including them separately.

I don't see why that would expand to include `./.nuxt` and can't reproduce so I'm going to close, but if this is still an issue please open a new issue and include a reproduction so I can look into it.

Thanks!

**Comment by naschidaniel** [comment]
Hi Adam, thank you for your reply.
You are right, the behaviour cannot be reproduced in a newly created project. 

[https://github.com/naschidaniel/nuxt-tailwindcss](https://github.com/naschidaniel/nuxt-tailwindcss)

It looks like another dependency is influencing the behaviour. The behaviour starts when I change a class.
[https://github.com/naschidaniel/fly-tirol](https://github.com/naschidaniel/fly-tirol)

Your documentation and tailwind seem to work correctly. A change is therefore not necessary.
Thank you very much for your efforts.
