### ISSUE TITLE
Docs: Missing mention of the DEFAULT key in an color object of the tailwind config

### ISSUE THREAD

**Issue by chris-sirpauls** [tailwindlabs/tailwindcss.com#1228]
This part is missing in the v3 docs.
It exists in the [v2 docs](https://v2.tailwindcss.com/docs/customizing-colors#color-object-syntax) and is still working.

Might be useful knowledge to users.

**Comment by adamwathan** [comment]
Added here: https://github.com/tailwindlabs/tailwindcss.com/commit/7f9030368079104cef17afb2c04a444a4030556d

Thanks!
