### ISSUE TITLE
Mention lack of support for backdrop-blur in Firefox

### ISSUE THREAD

**Issue by ahangarha** [tailwindlabs/tailwindcss.com#1230]
Month ago after hours of struggling with backdrop-blur I realized that Firefox doesn't support it yet. Isn't it better to mention this issue in the documentation as some notice or tip?

Related page in documentation: https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/backdrop-blur.mdx

**Comment by adamwathan** [comment]
Thanks for the suggestion! I'd like to do this but also not sure we can realistically be a source of truth for browser support for every CSS feature in different browsers.

Best bet is to reference [Can I Use](https://caniuse.com/?search=backdrop-filter) like we mention in our [Browser Support documentation](https://tailwindcss.com/docs/browser-support).

Going to close as I don't consider this a bug or anything but I do appreciate the suggestion 👍🏻
