### ISSUE TITLE
Why docs instruct install `postcss` instead `postcss-cli`?

### ISSUE THREAD

**Issue by AdsonCicilioti** [tailwindlabs/tailwindcss.com#1231]
Why docs instruct install `postcss` instead `postcss-cli` is the correct?

I spent hours trying to get postcss-import to work, but to no avail. Until I realized that there was no executable in `node_modules/.bin`. The docs don't show an example of scripts for package.json to run with postcss.

Did I do something wrong or is the documentation really missing?

**Comment by adamwathan** [comment]
`postcss` is a peer dependency of Tailwind so you need to install it. You don't need `postcss-cli` unless you are planning to use `postcss-cli` as your build runner. If you want to use `postcss-cli` to compile your CSS then yeah of course you need to install it, but that's not something Tailwind requires. You can just use the `tailwindcss` CLI tool with the `--postcss` flag if you'd like it to read additional plugins from `postcss.config.js` file 👍🏻

**Comment by AdsonCicilioti** [comment]
Not which image in my css and I also set `proccessCssUrl` to `false`.
My main Css imports TailWindCss modules with partials of my styles.

And I have the steric loop in both Watch and Hot mode.

**Comment by AdsonCicilioti** [comment]
@adamwathan , So we could have the mention of this flag in the documentation right?
