### ISSUE TITLE
"Live Demo" link for typography plugin is not working

### ISSUE THREAD

**Issue by pReya** [tailwindlabs/tailwindcss.com#1233]
The link to the "Live Demo" in the source file [typography-plugin.mdx](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/typography-plugin.mdx) is not working. It loads an empty, blue "Tailwind Play" page without any content. This is the page it's loading:
https://play.tailwindcss.com/uj1vGACRJA?layout=preview

Not sure if Tailwind Play has a problem, or if the link is broken/outdated. In any case it would be great to restore the Live Demo for the typography plugin.

**Comment by bradlc** [comment]
Hey @pReya, thanks for reporting. This was indeed an issue with Tailwind Play, but this has now been fixed via https://github.com/tailwindlabs/play.tailwindcss.com/pull/130 👍
