### ISSUE TITLE
Upgrade guide missing section about opacity values

### ISSUE THREAD

**Issue by acalvino4** [tailwindlabs/tailwindcss.com#1235]
I discovered by inspecting the difference between the v2 and v3 docs that some utilities like `ring-opacity-5` can be replaced by a `/5` after a color - like `ring-black/5`.  The old version still works, but for the sake of encouraging a uniform way of doing things, I think it's worth noting the change in the upgrade docs (it is not currently). I think it may be mentioned in a v3 video somewhere, but yeah, its not in the upgrade guide.

**Comment by adamwathan** [comment]
Thanks for the suggestion, have added a note to the upgrade guide 👍🏻
