### ISSUE TITLE
Docs: clarify Next.js installation guide

### ISSUE THREAD

**Issue by Voyager-Two** [tailwindlabs/tailwindcss.com#1237]
In the [Next.js guide](https://tailwindcss.com/docs/guides/nextjs), it gives this example in step 3:

```javascript
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
```
However, what's not clear is that these paths are relative to `package.json`/`node_modules`, not `tailwind.config.js`. So if using `src` directory, above examples will not work.

This is more clear in the [general installation guide](https://tailwindcss.com/docs/installation), step 2:
```javascript
  content: ["./src/**/*.{html,js}"],
```

Related [StackOverflow post](https://stackoverflow.com/a/70657857/1928926)

**Comment by adamwathan** [comment]
Hey! I've added a note to the content configuration page to explain this detail since it's relevant for everyone:

https://github.com/tailwindlabs/tailwindcss.com/commit/8964d423973debfa58290264918374b447c5c466

Thanks.
