### ISSUE TITLE
NextJS guide: suggest deleting .next directory

### ISSUE THREAD

**Issue by travigd** [tailwindlabs/tailwindcss.com#1239]
I just spent an embarrassing amount of time debugging why Tailwind wasn't working within my Next project after installing and configuring it. For some reason, it didn't pick up the new postcss config until I deleted the `.next` directory (where NextJS stores all its build cache things). Would be nice to add that troubleshooting suggestion to the NextJS guide.

**Comment by adamwathan** [comment]
Thanks for the suggestion! Will keep this in mind and if it's something we start to hear from more people then we will figure out a way to include it in the docs.
