### ISSUE TITLE
Missing auto margin for absolute position

### ISSUE THREAD

**Issue by jezsung** [tailwindlabs/tailwindcss.com#1257]
From the [document](https://tailwindcss.com/docs/top-right-bottom-left#placing-a-positioned-element), `inset-0` seems to center itself but it actually doesn't work without `m-auto`. Shouldn't this be mentioned in the document? Please let me know if I miss something

**Comment by adamwathan** [comment]
Hey! `inset-0` just sets `top`, `right`, `bottom`, and `left` to `0`. Anything else you want to combine with that to achieve some specific effect is up to you. Here are the MDN docs on the inset property:

https://developer.mozilla.org/en-US/docs/Web/CSS/inset
