### ISSUE TITLE
customize chapter-->a ghost word in configuration post

### ISSUE THREAD

**Issue by qingyggg** [tailwindlabs/tailwindcss.com#1265]
https://tailwindcss.com/docs/configuration#important

``Note that any of your own custom utilities (will not )---->(this should be will ,because demo call this should do )automatically be marked as !important by enabling this option.

If you’d like to make your own utilities !important, just add !important to the end of each declaration yourself:``
![112](https://user-images.githubusercontent.com/65453020/169290323-7ba8d29d-6842-4ec8-b70f-f3a2c4491b00.png)

**Comment by adamwathan** [comment]
Good catch! This changed in v3 and we forgot to update the docs.

Fixed here: https://github.com/tailwindlabs/tailwindcss.com/commit/7cbc1dd8a4c6d330298d4c5b803943e5db77bb88
