### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by aparajita** [tailwindlabs/tailwindcss.com#1277]
[hover-focus-and-other-states.mdx](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/hover-focus-and-other-states.mdx#using-arbitrary-variants):

```
[`addVariant` plugin API]((/docs/plugins#adding-variants))
```

There is an extra set of parens in the link, causing a 404.

**Comment by adamwathan** [comment]
Thank you, fixed! https://github.com/tailwindlabs/tailwindcss.com/commit/89d852d2a1838e50e9e47cde3348b3788815bdda

**Comment by aparajita** [comment]
Thank you for Tailwind! 🙏
