### ISSUE TITLE
Mention standalone cli executable in docs

### ISSUE THREAD

**Issue by jozydapozy** [tailwindlabs/tailwindcss.com#1284]
As a PHP-developer, I love the fact I can use tailwindcss with a standalone executable. (I learned about it in [this blogpost](https://tailwindcss.com/blog/standalone-cli)) 
It's nowhere mentioned in the docs though. Seems valuable to add for newcomers.

**Comment by tordans** [comment]
I was just searching for a list of CLI options as well. It would be great to have it on a separate page on the help page.

After some searching, I found the options at https://github.com/tailwindlabs/tailwindcss/blob/master/src/cli.js#L190-L229.

One think that this help page could show, is use cases like this: use the cli without an input css by specifying the content via the cli option: `tailwindcss --content ./app/views/landingpages/client_name.html.slim --output ./public/clients/client_name/style.css`. This is great for projects that have small stand alone html pages like a 404.html or 500.html and want a small, separate css file for those.

**Comment by adamwathan** [comment]
Added a note about the standalone CLI in the installation docs 👍🏻

**Comment by tordans** [comment]
@adamwathan thanks a lot. I assume you are referring to https://github.com/tailwindlabs/tailwindcss.com/commit/41242b24bb66c74291b2ff048a6efe2a625e8654, which would not answer the questions I had, unfortunately.

When I was looking for help on this, I did find https://tailwindcss.com/blog/standalone-cli but that post does not explain the available options. The only place I found that shows the options in full was [the code itself](https://github.com/tailwindlabs/tailwindcss/blob/master/src/cli.js#L190-L229).

I suggest to adding two examples to this blog post:
- `tailwindcss --content ./app/views/landingpages/client_name.html--output ./public/clients/client_name/style.css` which shows that no input css nor config is needed
- `tailwindcss --config ./app/views/landingpages/client_name.config.js --output ./public/clients/client_name/style.css` which shows that a project can have multiple custom configs to generate separate output styles

Those where the use cases I was looking for.

**Comment by adamwathan** [comment]
Yeah still want to do that but this issue is “Mention standalone CLI in docs” and that’s what I’m resolving 👍🏻
