### ISSUE TITLE
Installation instructions with Next.js couldn't work

### ISSUE THREAD

**Issue by JohannHiro** [tailwindlabs/tailwindcss.com#1306]
# Installation instructions with Next.js couldn't work

I setup a `Next.js` project and try to use `tailwindcss` by following instructions on the website.
However, the styles wouldn't come out.
I need to either import `tailwindcss/tailwind.css` file in `_app.tsx` file or move `globals.css` out of `styles` folder to make it work.

```tsx
// In _app.tsx file

// The styles wouldn't come out without this line
import "tailwindcss/tailwind.css";
```

Most of the articles or videos online use one of the method I just mentioned. Not quite sure if it's my problem or the document needs an update.

**Comment by Pavitra554** [comment]
this worked for me @JohannHiro 
` npx create-next-app -e with-tailwindcss  project_name`

this is just an solution.. but I think In my case most of the time the doc is also worked.. not sure about the current time!

**Comment by Pavitra554** [comment]
https://tailwindcss.com/docs/guides/nextjs

this is also working @JohannHiro !

**Comment by JohannHiro** [comment]
Oh, sorry. I found that it's just HMR of Next.js got buggy for moment. Thanks for your reply though @Pavitra554!

**Comment by Pavitra554** [comment]
Mark those as answers 😅 @JohannHiro
