### ISSUE TITLE
Remix Tailwind integration missing a step

### ISSUE THREAD

**Issue by brittneypostma** [tailwindlabs/tailwindcss.com#1315]
The TailwindCSS docs are missing this code section that the Remix docs include causing Tailwind to not work when using the Remix setup.
```js
import { Links } from "@remix-run/react";
// ...
export default function Root() {
  return (
    <html>
      <head>
        <Links />
        {/* ... */}
      </head>
      {/* ... */}
    </html>
  );
}
```

[Tailwind Docs](https://tailwindcss.com/docs/guides/remix)
[Remix Docs](https://remix.run/docs/en/v1/guides/styling)

**Comment by kiliman** [comment]
Nice. But in their defense, I believe the default Remix templates already include the `<Links/>` component in *root*. Anyway, I'm sure it will help to make it explicit.

**Comment by thecrypticace** [comment]
Hey, yeah the default templates / structure definitely do include the `<Links />` component making this addition not strictly needed. I provided a bit more detail on our goal for the integration guides in my comment on the PR: https://github.com/tailwindlabs/tailwindcss.com/pull/1316#issuecomment-1205290513

Appreciate it anyway ❤️
