### ISSUE TITLE
Mention Container Max-Widths (screens) in Docs

### ISSUE THREAD

**Issue by james0r** [tailwindlabs/tailwindcss.com#1322]
As described here https://stackoverflow.com/questions/65903737/configure-container-max-width-at-specific-breakpoints-tailwindcss

This has to be fairly common. Would nice to have in the docs.

**Comment by thecrypticace** [comment]
Hey, so in this case it's intentional. The option exists only for backwards compatibility but its use is not encouraged: https://github.com/tailwindlabs/tailwindcss.com/issues/866#issuecomment-854816990
