### ISSUE TITLE
classes in "Important modifier" code example are in the wrong order

### ISSUE THREAD

**Issue by json2d** [tailwindlabs/tailwindcss.com#1327]
these are flipped:

<img width="591" alt="Screen Shot 2022-08-17 at 3 48 26 PM" src="https://user-images.githubusercontent.com/143295/185230427-bef2da3a-965e-4f49-9b8d-cf8d231ecf66.png">

ie. should be `!font-medium font-bold`

https://play.tailwindcss.com/LWILn3DImQ

**Comment by adamwathan** [comment]
Hey! The order doesn't matter, both options do the exact same thing. Tailwind generates the CSS in a sort of unguaranteed order when two utilities do the same thing, so `font-bold` _might_ be before `font-medium` in the CSS but the reverse could be true too, it depends what class you use first and what order Tailwind scans your HTML files in:

https://play.tailwindcss.com/28LXh73orH

So just going to leave this as-is but thanks.
