### ISSUE TITLE
Vertical-align should mention that it accepts arbitrary values

### ISSUE THREAD

**Issue by Yovach** [tailwindlabs/tailwindcss.com#1329]
[`vertical-align`](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align#syntax) accepts arbitrary values and that's not mentionned on **Tailwind CSS Documentation**

**Comment by adamwathan** [comment]
Thanks, added: https://github.com/tailwindlabs/tailwindcss.com/commit/0e105d26887c6af7026fe27f6f8c174307bf2b66
