### ISSUE TITLE
React with Vite

### ISSUE THREAD

**Issue by josephzidell** [tailwindlabs/tailwindcss.com#1331]
First off, want to say how awesome the docs are. Period.

On the [create-react-app guide](https://tailwindcss.com/docs/guides/create-react-app), the note highly recommends installing React via some other method, notably Vite. However, when you go to the [Vite guide](https://tailwindcss.com/docs/guides/vite), it's only for Vue 3. 

Does the Vite guide work for all frameworks (Vue, React, Vanilla, etc) installed via Vite, and if so, can the documentation be generalized and clarified?
If not, is it possible to create specific pages for each framework? Eg: rename the existing one to something like Vite-Vue, and create a Vite-React, etc?

On a totally side note, the links in `... recommend using Vite, Next.js, Remix, or Parcel instead ...` all point to the framework's website, and it's kinda frustrating to go and find _the guide for that framework_.

Thanks for this amazing tool and awesome documentation!

**Comment by thecrypticace** [comment]
The guide does indeed work for React as well however we need to make some tweaks to the guide given that `npm create vite` is a thing now. We're considering adding tabs for React, Vue, static HTML, etc… But generally the only thing that's different is the imports in the sample code and the content array. With the appropriate changes the guide pretty much works as is for React — you just need to choose `react` when creating the project initially.
