### ISSUE TITLE
Copy code snippet to clipboard button

### ISSUE THREAD

**Issue by hichemfantar** [tailwindlabs/tailwindcss.com#1337]
Would appreciate a way to be able to copy code snippets directly to the clipboard.

**Comment by adamwathan** [comment]
Thanks for the suggestion — going to close since not an actual mistake or bug with the docs but appreciate the feedback regardless.

**Comment by hichemfantar** [comment]
This is already available in some parts of the docs but not all, such as https://tailwindcss.com/docs/font-size#providing-a-default-letter-spacing
