### ISSUE TITLE
Missing example for `matchVariant`

### ISSUE THREAD

**Issue by smithliam** [tailwindlabs/tailwindcss.com#1346]
https://tailwindcss.com/docs/plugins

There is no example or anything for the `matchVariant` function. I find [this example](https://github.com/tailwindlabs/tailwindcss/pull/8310) but it doesn't work. Error:

```
Tailwind CSS: matchVariant is not a function
```

**Comment by adamwathan** [comment]
Yeah this feature hasn't been released! Will add documentation when it's ready.

**Comment by adamwathan** [comment]
See what you mean now, the docs mention it but don't explain it. Removed that mention for now until we actually make it work, whoops! Thanks.
