### ISSUE TITLE
incomprehensible text

### ISSUE THREAD

**Issue by sroxck** [tailwindlabs/tailwindcss.com#1349]
![image](https://user-images.githubusercontent.com/51316180/189835424-3ebc7c0e-8e71-4367-8f84-4942ba3435e9.png)

Maybe it shouldn't exist?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

It looks like you are looking at https://www.tailwindcss.cn which is a website that is not maintained by us but by somebody from the community. 
I would recommend to let them know about the issue 👍
