### ISSUE TITLE
"Global CSS cannot be imported..."

### ISSUE THREAD

**Issue by Forseti93** [tailwindlabs/tailwindcss.com#1358]
https://github.com/tailwindlabs/discuss/issues/356
repository has been copied => npm i => npm run dev => error.

error - ./src/css/fonts.css
Global CSS cannot be imported from files other than your Custom <App>. Due to the Global nature of stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
Location: src\pages\_app.js

**Comment by reinink** [comment]
Hey! 👋

So here is how you can build this repo locally:

```sh
git clone git@github.com:tailwindlabs/tailwindcss.com.git
cd tailwindcss.com
npm install --force
npm run dev
```

Running these commands will give you a local development site at http://localhost:3000.

I just gave this a try right now and it worked without any issues. I am running on MacOS with npm v8.11.0 and node v16.15.1. If you're using another platform, for example Windows, I cannot guarantee that the site will even work.

To be honest we've made this repo public to allow others to submit corrections and just to show the community how we've built it, but it wasn't ever intended to be run locally for the purpose of offline docs. If you can get it to work that way, great, but it's not a use-case we're actively supporting.

I hope that helps! 👍

**Comment by Forseti93** [comment]
Hello,
I've tried once more, got the same error.
Windows 10 pro, node v16.17.0, npm -v 8.13.2.

Does the official tailwindcss offline documentation exists? Top search results in google suggest npm run dev or to download from strange sites.
