### ISSUE TITLE
404 on cursor example pics

### ISSUE THREAD

**Issue by AshSimmonds** [tailwindlabs/tailwindcss.com#1364]
https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/cursor.mdx

https://tailwindcss.com/docs/cursor

![MPjguWXIS0](https://user-images.githubusercontent.com/9034041/192517393-949b0b19-d142-4dab-b39c-5c5b11da19eb.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Good catch!
