### ISSUE TITLE
Incorrect import path in link tag in example html

### ISSUE THREAD

**Issue by Joey-JJ** [tailwindlabs/tailwindcss.com#1382]
I was following the installation steps when I found this. If you exactly copy everything in the example, Tailwind won't work because the path to the output css does not work. In step 5 it says the link tag should be `<link href="/dist/output.css" rel="stylesheet">` but it only worked when I changed it to `<link href="../dist/output.css" rel="stylesheet">`.

https://tailwindcss.com/docs/installation

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This is correct, but there is a difference when you run the code.

If you directly run the html file in your browser (e.g.: the url looks like `file:///path/to/your/project`) then a relative path is required (e.g.: `../dist/output.css`)

But, typically you run your code in a little server. Most tools Vite, Next.js, Webpack, Parcel, ... they all run a server and then the convention is to use an absolute path to the root of your project.

So this is not an issue but optimized for the most common / real world setup.
