### ISSUE TITLE
Flash of white screen when scroll wheel click

### ISSUE THREAD

**Issue by adarsh4d** [tailwindlabs/tailwindcss.com#1402]
When internal/hashed link is clicked in the blog using the scroll wheel to open the link in new tab, then white screen is briefly shown 

## Steps to reproduce: 

1. Open link https://tailwindcss.com/blog/tailwindcss-v3-2
2. Set theme to dark mode
3. Open internal link https://tailwindcss.com/blog/tailwindcss-v3-2#multiple-config-files-in-one-project-using-config using scroll wheel click
4. Issue: White/unstyled website is briefly shown

## Browser

1. Chrome: ❌Issue
2. Edge: ❌Issue
3. Firefox: ✔️Working fine

Not sure if this is chromium based issues, but just wanted to let you know. Thanks.

**Comment by reinink** [comment]
Hey thanks again for reporting this, it's been fixed: f87291b6fa663c30527da27f2b0920d99205300b
