### ISSUE TITLE
Terrible performance when clicking on details

### ISSUE THREAD

**Issue by chenxsan** [tailwindlabs/tailwindcss.com#1405]
E.g., https://tailwindcss.com/docs/hover-focus-and-other-states

https://user-images.githubusercontent.com/1091472/197340726-c99bcf7c-64ac-4e66-92a5-da084b80b6a1.mov

If I record the open action with react devtools,

![](https://user-images.githubusercontent.com/1091472/197340776-d35df151-9367-4363-af64-123b982aecbe.png)

Seems something wrong somewhere.

**Comment by reinink** [comment]
Hey, thanks for reporting this. This is actually a known issue. See here: #1051

Here is the response I gave previously:

> Hey! Thanks for reporting this. This is truly a weird issue — something is obviously happening in React land to cause this. I've spent some time digging into it, trying a bunch of different things, and nothing helped. So while I agree this is annoying/weird, I am going to close this issue, just because there isn't a clear obvious fix, and also because it still technically works. If anyone here wants to do more digging into this and figure out the cause, I'd be grateful! 🙏

So again if anyone can figure out what's causing this, that would be amazing, but since the site technically works still, and since I haven't been able to find a fix myself after investing a decent chunk of time on this, I'm going to close this.

Thanks again either way! 🙏

**Comment by chenxsan** [comment]
@reinink So I spent sometime digging into the issue, and I can be pretty sure it's caused by this `useTop` hook which uses https://github.com/reach/reach-ui/tree/dev/packages/rect under the hood.

If I comment out those code:

![](https://user-images.githubusercontent.com/1091472/197377476-7293b967-9502-472c-81f8-3bacdd59c59e.png)

There's no more performance problem then:

https://user-images.githubusercontent.com/1091472/197377517-8b4e10ca-ab4d-4783-a3e1-3d43fa05b5a7.mov

It might be better to implement the toc highlighting with Intersection Observer API.
