### ISSUE TITLE
Long contents in table are hidden on mobile phone

### ISSUE THREAD

**Issue by chenxsan** [tailwindlabs/tailwindcss.com#1406]
E.g.,

<img src='https://user-images.githubusercontent.com/1091472/197391306-ea7e98b9-2d6f-4446-9fe1-c9e03d15f38d.png' width='400' />

There's no way to scroll horizontally because of `overflow-hidden` applied on small screen:

![](https://user-images.githubusercontent.com/1091472/197391420-809ee3d2-7402-4ccd-957c-67c6a4b54d7e.png)

**Comment by bradlc** [comment]
Thanks for reporting, this is now fixed 👍
