### ISSUE TITLE
No way to resize the example on mobile

### ISSUE THREAD

**Issue by chenxsan** [tailwindlabs/tailwindcss.com#1407]
There're some examples where we can resize with a handler:

![](https://user-images.githubusercontent.com/1091472/197391931-b40e081d-9eff-4013-95ea-9128d37a4f29.png)

But that handler is hidden on mobile:

![](https://user-images.githubusercontent.com/1091472/197391971-fb925f86-9a8d-4a95-a35f-1715be7ae7a7.png)

Wouldn't it make sense to hide the `Resize the example to see the expected behaviour` content as well on mobile? It's sort of confusing for me when I couldn't find such a handler on my cellphone only to find it being hidden on purpose.

**Comment by bradlc** [comment]
Thanks for reporting this, the hint is now hidden on mobile 👍
