### ISSUE TITLE
Next.js 13 revision for getting started

### ISSUE THREAD

**Issue by CTOverton** [tailwindlabs/tailwindcss.com#1412]
Next.js 13 has just been introduced, along with an official app playground that uses tailwind.

The current guide suggests adding this to the content for Next.js
https://github.com/tailwindlabs/tailwindcss.com/blob/0cae8871af0a66c20522c81560db8abe20e6d069/src/pages/docs/guides/nextjs.js#L48-L49

For Next.js 13 it should look like this due to the new changes related to the app directory. 
> Note: this new feature is still in beta

https://github.com/vercel/app-playground/blob/6847701a0792d27947e8d18ce5f2391c1f8a4ba0/tailwind.config.js#L3-L7

```js
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './page/**/*.{js,ts,jsx,tsx}',
    './ui/**/*.{js,ts,jsx,tsx}',
  ],
```

**Comment by adamwathan** [comment]
Updated as per a PR from the Next team themselves here: https://github.com/tailwindlabs/tailwindcss.com/pull/1389

Thanks!
