### ISSUE TITLE
Install Tailwind CSS with Nuxt.js

### ISSUE THREAD

**Issue by lazercaveman** [tailwindlabs/tailwindcss.com#1424]
The way showed within the [Tailwind docs](https://tailwindcss.com/docs/guides/nuxtjs), to implement Tailwind into a Nuxt project [isn't valid for Nuxt 3 anymore](https://github.com/nuxt/framework/pull/8487), since Nuxt doesn't allow Nuxt 2 syntax within the nuxt.config anymore - this is leading to tailwindcss not working at all within Nuxt 3.

**Comment by reinink** [comment]
Hey thanks for reporting this!

So right now our Nuxt guide is for Nuxt 2, since it's still the default version that's installed when creating a new Nuxt project. When Nuxt 3 is officially out we'll upgrade this guide, but until then I think it makes sense to keep things the way the are.

Thanks for reporting either way — it's good for us to be aware of this 👍

**Comment by lazercaveman** [comment]
Alright, release date for Nuxt 3 will be in 5 days according to their [release schedule](https://v3.nuxtjs.org/community/roadmap/#-release-schedule). ^^

**Comment by reinink** [comment]
@lazercaveman Good to know! I'm actually working on adding a Nuxt 3 guide right now to include alongside the Nuxt 2 guide. I'll ping you when that's done, and maybe you can review it make sure I've done things correctly 😅

**Comment by lazercaveman** [comment]
@reinink sound nice - happy if I can help somehow. ^^

**Comment by reinink** [comment]
@lazercaveman Hey thanks! Have a look at my PR (#1424) and let me know if anything looks incorrect. I'm not an avid Nuxt user, so I'm sort of just going off what I can find online.

Here's a direct link: https://tailwindcss-com-git-nuxt3-tailwindlabs.vercel.app/docs/guides/nuxtjs#3

**Comment by lazercaveman** [comment]
@reinink that was fast! :D
...looks fine to me so far, and seems to work as well - thank you. : )
