### ISSUE TITLE
How to create tailwindcss matchComponents plugin

### ISSUE THREAD

**Issue by jabed-dev** [tailwindlabs/tailwindcss.com#1441]
**I'm create all the other plugins but can't create this. like 'addBase, addComponents matchUtilities, matchVariant'.**

**Comment by thecrypticace** [comment]
Hey, our `matchComponents` plugin works the same as match utilities except it's put in the `components` layer so make sure you include `@tailwind components` in your CSS.

Here's an example for you: https://play.tailwindcss.com/hCTVlVSZJQ
