### ISSUE TITLE
Form Elements not mentioned in the Preflight Docs

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss.com#1443]
In this page: https://tailwindcss.com/docs/preflight form elements are not mentioned. By default tailwind removes the border which makes the input elements to not display while development. This makes it hard for the first-time users to digest. 

So, this should be in the docs as well.

**Comment by adamwathan** [comment]
Hey! We do have this section in the Preflight docs that explains how borders are reset globally for all elements:

https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally

So going to close this as not a mistake/bug in the docs or anything but appreciate the feedback! Would like to rework a lot of foundational documentation like this at some point in the near-ish future and will take this into consideration when I do 👍
