### ISSUE TITLE
Next js install documentation doesn't mention postcss config

### ISSUE THREAD

**Issue by Hasenn** [tailwindlabs/tailwindcss.com#1449]
Following the documentation didn't work for me until I realized I needed a `postcss.config.js` for postcss with :
```js
module.exports = {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    }
  }
```
Otherwise my globals.css didn't get compiled properly

**Comment by reinink** [comment]
Hey @Hasenn! 👋

Sorry to hear you got stuck on this step, but technically the guide does explain how to generate a properly configured `postcss.config.js` file in the second step (Install Tailwind CSS):

```sh
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p
```

When you run the `npx tailwindcss init` command with the `-p` flag, it will automatically generate the correct `postcss.config.cjs` file for you.

I totally get how that's easy to miss if you're adding Tailwind CSS to an existing project. However, all of our guides to this point have been written from the perspective of creating a new project, as that's the simplest way for us to reliably share reproducible steps. For existing projects there could be any number of different things to consider, making it not super practical for quick "get up and running" guides like this.

I hope that makes sense 👍
