### ISSUE TITLE
flex-grow

### ISSUE THREAD

**Issue by JacobWeisenburger** [tailwindlabs/tailwindcss.com#1456]
[flex-grow](https://tailwindcss.com/docs/flex-grow)

![image](https://user-images.githubusercontent.com/31667350/206759486-fca2150a-2183-4369-8021-f580e1d26d5b.png)

This page shows that the class you need is `grow`, but that doesn't change the css for me.
However, using `flex-grow` instead works as expected. So maybe this is just a documentation issue.

**Comment by thecrypticace** [comment]
Hey! In v3 both `grow` and `flex-grow` (for backwards compatibility) work as you can see here: https://play.tailwindcss.com/wjrGz5SrR2

If `grow` does not work for you then you are probably using Tailwind CSS v2 (the docs for v2 can be found here: https://v2.tailwindcss.com). If you are using v3 and seeing this issue I would suggest you open an issue on the Tailwind CSS repo with a link to a repo containing as minimal a reproduction as you can provide so we can investigate why it's not working for you.

**Comment by JacobWeisenburger** [comment]
Thanks for the quick answer. I'm using Deno Fresh with Twind. So I'm guessing Twind is using Tailwind CSS v2 under the hood.
