### ISSUE TITLE
Remix documentation `path` is wrong

### ISSUE THREAD

**Issue by HubM** [tailwindlabs/tailwindcss.com#1459]
I've tried the documentation relative to Remix or how to add Tailwind to your remix project.
The documentation explain that we have to update the `package.json` to update scripts

```js
{
  "scripts": {
    "build": "npm run build:css && remix build",
    "build:css": "tailwindcss -m -i ./styles/app.css -o app/styles/app.css",
    "dev": "concurrently \"npm run dev:css\" \"remix dev\"",
    "dev:css": "tailwindcss -w -i ./styles/app.css -o app/styles/app.css"
  }
}
```

The path `./styles/app.css` is wrong, it should be `./app/styles/app.css` :)

**Comment by adamwathan** [comment]
Hey! The path is correct, we tell you to create that file in step 5:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/4323180/206852409-24180c08-0137-42ce-9414-32a274bde759.png">

The `./styles/app.css` file is the source file, and `./app/styles.app.css` is the compiled CSS file. The scripts in the `package.json` file are compiling the source file into the compiled file, so they definitely shouldn't be the same path.
