### ISSUE TITLE
Usage of class `.lead`

### ISSUE THREAD

**Issue by scheinercc** [tailwindlabs/tailwindcss.com#1481]
Hi there,
Looking at https://tailwindcss.com/docs/typography-plugin#element-modifiers
Modifier: \`prose-lead:{utility}\`
Target: \`[class~="lead"]\`
I can't find an example where `.lead` is explained/used.

Searched the documentation and the wider web.

**Comment by adamwathan** [comment]
Hey! You can see it used in the demo from the documentation here:

https://play.tailwindcss.com/uj1vGACRJA

A `lead` class is just a fairly common convention as a hook for a lead paragraph that you want to style a little bit differently than the rest of an article, usually using a larger font for example.

Nothing special just exactly what it shows in that table in the docs — just targets the selector `[class~="lead"]` just like `prose-h4` targets the selector `h4`.

**Comment by scheinercc** [comment]
Got it. Thanks for that Adam!
