### ISSUE TITLE
Install TailwindCSS with Next.js -- new /src directory

### ISSUE THREAD

**Issue by OGreeni** [tailwindlabs/tailwindcss.com#1485]
Next.js v13.1.2 introduces a new option to create a root `/src` directory to contain the `/app` and `/pages` directories. I'd love to include a toggle in the documentation showing the correct template paths for the tailwind config if a user chooses to enable this option (that is, adding a `/src` prefix to the paths). I just did, and I was wondering why Tailwind was not working correctly after following the docs.

**Comment by adamwathan** [comment]
Added a note about it to the docs 👍  You always have to put the correct paths for any template files you have in your Tailwind config though, we can't predict every folder you might ever use so it's a good thing to just understand and know how to configure.
