### ISSUE TITLE
Docs: Add tutorial for installing TailwindCSS for React using Nx

### ISSUE THREAD

**Issue by juristr** [tailwindlabs/tailwindcss.com#1492]
I came across this page following a tweet from @adamwathan replying to the whole CRA drama 😅 

I saw right now as additional options you link to Vite, Parcel, Next & Remix, each of those having [dedicated installation pages](https://tailwindcss.com/docs/guides/vite) on the docs.

<img width="988" alt="image" src="https://user-images.githubusercontent.com/542458/215039784-a27ee118-3b8d-4db0-9910-05c86411337e.png">

I think Nx could be a valuable addition here. You can use it in a monorepo or standalone configuration and we have since years a Tailwind plugin that makes setting it up a breeze. Demoing it here in this video for example: https://youtu.be/fkTz6KJxhhE?t=297

I can submit a PR to the docs here but wanted to first explore whether that would be welcomed :)

**Comment by juristr** [comment]
I've posted a video on the topic if you're curious about what I mean.
https://youtu.be/hHh0xhzSnx8

As mentioned. If you're on board with adding Nx as an option, I can work on a PR to get it in.

**Comment by Bowens20832** [comment]
At my senior dev job, we are using NX together with React and Angular together in a single app. We are upgrading to Tailwind in the React app that is a CRA. We develop our React components in Storybook, so I configured Storybooks webpack config to fire the TailwindCLI command when it rebuilds on a content change.

**Comment by ImBIOS** [comment]
I love this ❤️

**Comment by adamwathan** [comment]
Hey, thanks for the suggestion! Going to close this as we try to use issues strictly for problems in the documentation but if it ever feels like there's sufficient demand for it we can definitely consider adding it.

We primarily offer the framework guides as a way to minimize the amount of time we ourselves spend helping people get things setup with popular projects — we get the same questions over and over again so it's nice to just write up the instructions once and have somewhere to point people to 😄 It's a lot to stay on top of and maintain though so we don't have a goal of adding everything under the sun, just the stuff that's causing us a lot of support burden.

Thanks again for the suggestion regardless 👊
