### ISSUE TITLE
Docs:  Add Blazor App framework Guide

### ISSUE THREAD

**Issue by eriknyk** [tailwindlabs/tailwindcss.com#1493]
Blazor Framework Guide Request
===

Blazor Apps is being more popular at this time,
can you consider adding a Guide to integrate tailwindcss with [Blazor](https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor) please

Requested in section: [framework-guides] https://tailwindcss.com/docs/installation/framework-guides
Requested guide for: [Blazor] https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor

---

Currently there are a couple of guides on internet, like: https://chrissainty.com/adding-tailwind-css-v3-to-a-blazor-app/
However would be nice to have an official guide from you guys.

Best Regards.

**Comment by reinink** [comment]
Hey! Thanks for this suggestion. No one on our team uses .NET or Blazor, but we'd be open to a pull request that adds a Blazor guide like this, as long as it follows the same pattern/style of the other [existing framework guides](https://tailwindcss.com/docs/installation/framework-guides) 👍
