### ISSUE TITLE
[Algolia] Ampersand(&) is not encoded 

### ISSUE THREAD

**Issue by Maybach91** [tailwindlabs/tailwindcss.com#1495]
**Reproduction**
1. Go to https://tailwindcss.com/docs
2. Search something, which will not be found, e.g. `changelog`
3. Algolia Search Suggestions are shown
4. The ampersand `&` is shown as HTML entity and is not correctly converted

**Screenshot:**
<img width="779" alt="image" src="https://user-images.githubusercontent.com/1867543/215694268-819fcc8d-5beb-4119-8a9a-53523ab19b2f.png">

**Comment by thecrypticace** [comment]
Alright I've updated stuff to make sure the `&` doesn't end up escaped in search results. Thanks!
