### ISSUE TITLE
Docs: backgroundOpacity should highlight that the values must be strings

### ISSUE THREAD

**Issue by herzaso** [tailwindlabs/tailwindcss.com#1500]
when customizing backgroundOpacity, if a number if used instead of a string (e.g. `50: 0.5`), the result is a class having the property: `-tw-bg-opacity: 0.5px;` which doesn't work since the `px` is redundant there.
The documentation does show strings there but it can very easily be overlooked since people might not expect a string there.
I suggest fixing this setting to allow also a number value, but if that's not possible then the documentation needs to be point that out.

**Comment by adamwathan** [comment]
Thanks for the suggestion! If this becomes a common issue people run into then we can definitely look into making it really obvious in the documentation.
