### ISSUE TITLE
Question: Can I use beams in other projects?

### ISSUE THREAD

**Issue by akihironagai** [tailwindlabs/tailwindcss.com#1501]
tailwindcss.com has great beam backgrounds ([/src/img/beams/](https://github.com/tailwindlabs/tailwindcss.com/tree/master/src/img/beams))

I would like to use them in my project.

However, the license says that you can only use it for educational purposes.

I consider using this background to be a small purpose and therefore it should be free to use.

Could you please give me an answer to this question?

Thank you.

**Comment by adamwathan** [comment]
Hey! While you're free to draw inspiration from the design elements on the site and create any of your own design assets from scratch, the beams are a pretty core part of our brand and I can't give you permission to just take those files and use them in your own projects. Thanks!
