### ISSUE TITLE
Docs: describe the `addDefaults` helper function provided for plugin authors

### ISSUE THREAD

**Issue by yaronuliel** [tailwindlabs/tailwindcss.com#1502]
When a new plugin is registered - tailwind provides an object with helper functions for registering new components (`addComponent`/ `matchComponents`), utility classes (`addUtilities`/`matchUtilities`), etc..

The list of helper functions is documented [here](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/plugins.mdx#overview 
)

On top of the documented functions, there is another function, called `addDefaults` that can be used, as far as I understood, to register `:root` level CSS custom properties - which is really handy for plugins that want to generate classes with defaults, based on CSS custom properties (same way tailwind does in many cases)

Not only this method is not documented - it is also not available as part of the type definition of the plugin

This method doesn't seem new or deprecated, so I think it should be documented

The source code of the function is [here](https://github.com/tailwindlabs/tailwindcss/blob/ef6f9ee6c2df6ff3ecfa4fda127ae7f672735e47/src/lib/setupContextUtils.js#L315)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

As mentioned in your other issue, I'm going to close this one as well. 

More info: https://github.com/tailwindlabs/tailwindcss/issues/10514#issuecomment-1420879057
