### ISSUE TITLE
Docs: Content configuration for third party libraries

### ISSUE THREAD

**Issue by danielnavram** [tailwindlabs/tailwindcss.com#1504]
# Content Configuration for Third-Party Libraries

Currently, there is a mistake in the relative paths in third-party libraries documentation.
The `require.resolve` method will return the exact path to the module like `/node_modules/your-company/folder/file.js`, thus if you try to do a join with the regex `*.{js,html,ts}`, then it won't work.

The exact methods to get the path directory and join the regex is the following:
`path.join(path.dirname(require.resolve('your-company/folder')), '/*.{js,ts,html}')`

This is going to return a correct path directory with the regex in order to compile all the tailwind classes inside these files.

We're missing the method `path.dirname()` which will allow us to get just the path directory and not point to any module or file.

Link to the documentation which need the change: https://tailwindcss.com/docs/content-configuration#working-with-third-party-libraries

Best regards.

**Comment by thecrypticace** [comment]
Fixed, thanks!
