### ISSUE TITLE
Docs: Add @nuxtjs/tailwindcss to the installation guide for Nuxt

### ISSUE THREAD

**Issue by manaust** [tailwindlabs/tailwindcss.com#1507]
Using the [@nuxtjs/tailwindcss](https://tailwindcss.nuxtjs.org/getting-started/setup/) Nuxt module significantly simplifies installation and configuration for both Nuxt 2 and 3:

1. Install the module

```
npm install --save-dev @nuxtjs/tailwindcss
```

2. Add to Nuxt config

```js
export default defineNuxtConfig({
    modules: ['@nuxtjs/tailwindcss']
})
```

The result of following these steps is the same as following the current guides for Nuxt.

I'd like to provide a PR if this is considered a nice addition, but I would understand if not since the module not maintained by Tailwind Labs (AFAIK).

**Comment by adamwathan** [comment]
Hey! Going to stick with explicit instructions for now, personal preference is to avoid these types of framework-specific adapter libraries if it’s possible to configure things the standard way 👍🏻
