### ISSUE TITLE
Docs: Emphasizing the importance of keeping the build process running

### ISSUE THREAD

**Issue by RheingoldRiver** [tailwindlabs/tailwindcss.com#1511]
Hello, I've been using tailwincss for about a week and I'm really enjoying it so far! However, when I started using it I was having trouble for the first day, and I think it was because the docs were a bit unclear (I would blame it on myself but I've learned from my own projects that when my users have trouble, I should clarify my own docs).

In the [installation page](https://tailwindcss.com/docs/installation), step 4 has you start the Tailwind CLI build process. Because I am adding Tailwind to an existing React project made with CRA, I've been adding various npm packages, and it didn't quite click that Tailwind is its entirely own separate build; I thought that this step was injecting additional code into the CRA build. When the task didn't immediately finish running, I thought "oh, something went a bit wrong," and pressed ctrl+C. Nothing bad seemed to happen, so I thought nothing of it and continued about with my day.

Now the other thing is, as I was writing styles, I renamed my input files a couple of times, and so I happened to rerun this command which regenerated my classes for me at various points, and sometimes I didn't bother pressing ctrl+C immediately, and so I "accidentally" left the build process running. But I didn't understand at all that this was what I was doing. So then, when I *didn't* leave the build process running, I was fantastically confused why my classes weren't being generated.

Also, the [troubleshooting section](https://tailwindcss.com/docs/content-configuration#classes-aren-t-generated) which indeed I had read says nothing about keeping the build script running. Finally I ended up figuring it out but it took me a very long time & also asking for help in the discord server (although ironically I figured it out before anyone answered, which is so often the case).

So my proposal is: 

1. Make it VERY CLEAR in the installation process that you are **starting a build process that must be kept running**
2. Add a section to the "Troubleshooting" section to check if the build process is running (e.g. maybe it turned off overnight, which has also happened to me, so I check for this too)

Thank you!!

**Comment by adamwathan** [comment]
Hey thanks for the feedback! I try to keep the installation instructions very skimmable and streamlined so they feel as digestible as possible so I try to be careful about adding more steps or overloading things with too much information unless it's something lots and lots of people are running into, so I'm going to keep things as they are for now but will certainly pay attention in this area and if it's something that a lot of people are getting caught by I'll find a way to improve it 👍 The hope at least was that the `--watch` flag in the command was a signal that it's starting a watch process.

We also do just need a dedicated documentation page for the CLI tool that covers the options in more depth, and I think that would be a good place to eventually go into more detail about this stuff without making the quickstart instructions overwhelming.

For what it's worth you can use Tailwind with CRA without using our CLI tool, we have dedicated docs for that here:

https://tailwindcss.com/docs/guides/create-react-app

Setting things up that way works the way you initially expected, where it ties in to CRA's build process so if the CRA server is running, Tailwind is watching for changes. Unfortunately CRA is not very actively maintained and prevents you from customizing your PostCSS configuration, so if you need any PostCSS plugins other than Tailwind itself then you probably need to drop down to using our CLI, but not something we have the power to change 😕

**Comment by RheingoldRiver** [comment]
Okay, that makes sense, and I thought something like that might be the case. To me, it feels like you are trying to "sell tailwind" as less easily-installable than it actually is, because there actually are conceptual gotchas in the build process. I feel like this confusion could very easily happen to any newer developer without React/etc who's struggling with CLI tools in the first place who sees this, thinks "ah it's so easy, even I could do it," doesn't understand what's going on, and bails out. I'd suggest at least adding this to the troubleshooting guide and linking that from the installation guide (I did read quite a bit of the docs before doing anything, but I doubt everyone will).

Also, this is the first I've seen of the dedicated installation docs. How can you navigate to them? Thanks!

**Comment by adamwathan** [comment]
> To me, it feels like you are trying to "sell tailwind" as less easily-installable than it actually is, because there actually are conceptual gotchas in the build process.

That's not really the intention — the guide isn't missing any steps, as long as you run the command we provide it will start the build process that watches your files for changes and updates your CSS accordingly. But it's definitely the case that the target audience for the main documentation are folks who are comfortable with using their terminal and command line tools, have experience installing dependencies from npm, etc. It's been suggested before that we put together a "Tailwind CSS from absolute scratch" guide and I think that could be a good idea but hard to say when it will make sense to be top priority unfortunately.

> Also, this is the first I've seen of the dedicated installation docs. How can you navigate to them? 

At the top of the installation page there are tabs for the different ways you can install Tailwind depending on what type of context you are integrating it with:

![image](https://user-images.githubusercontent.com/4323180/219721589-7921c4a7-612f-4473-ace9-d72f69e8ea35.png)

Here's a direct link to the framework guides page, which includes the CRA guide:

https://tailwindcss.com/docs/installation/framework-guides

**Comment by RheingoldRiver** [comment]
Ahh, don't know how I missed those tabs. Thanks so much for taking this time, and I would love to see a "Tailwind from scratch" guide!
