### ISSUE TITLE
Docs: A point about a thing you should do starts with "Don't"

### ISSUE THREAD

**Issue by RheingoldRiver** [tailwindlabs/tailwindcss.com#1512]
On the [content configuration page](https://tailwindcss.com/docs/content-configuration#classes-aren-t-generated) there are a bunch of Do's and Don't's and one of them looks like this:
![image](https://user-images.githubusercontent.com/18037011/219517486-0a708ffb-45c9-4852-b29e-8cb2ee99b97d.png)

It's a very minor issue but it was a bit jarring to me to see Don't do this and then Yes do this and then Don't do this wait but this has a checkmark oh wait it's saying Don't forget. I would suggest to rephrase this in the positive as "Remember your" instead so that it follows the trend of the rest of the points in the article.

Also, I did a search using the internal "Quick search" feature for "Don't forget" to see if there was any other instance of this occurring. But the only result was in text, and didn't even include this heading. And the more I tested it, none of these Do's and Don't's seem to show up in search, "Don't construct class names dynamically" or "Always use complete class names" or etc. I guess they are inserted through a separate component and not part of the main text? I'm not sure if this is important, but it's something I noticed.

**Comment by adamwathan** [comment]
Thanks for the suggestion, pushed a tweak which should be live in a few 👍
