### ISSUE TITLE
Remix setup docs

### ISSUE THREAD

**Issue by DarrenBaldwin07** [tailwindlabs/tailwindcss.com#1515]
Found a bug in the new Remix docs for TailwindCSS setup found here: https://tailwindcss.com/docs/guides/remix

If you scroll down to step #6 it mentions "Import the compiled ./app/styles/app.css file in your ./app/root.jsx file". This is language from back when Remix did not support Postcss and needed to be compiled (looks like someone simply forgot to change this line). Personally, it was a little confusing when going through the setup process because it mentions a file we were never told to create. I would recommend changing it to "Import the ./app/tailwind.css file in your ./app/root.jsx file". This way things are more clear and users wont be wondering what "compiled" means here. 

I'll submit a PR after confirmation :)

**Comment by adamwathan** [comment]
Good catch, happy to take a PR for it 👍🏻
