### ISSUE TITLE
Add note regarding border behavior when preflight is disabled

### ISSUE THREAD

**Issue by vaelu** [tailwindlabs/tailwindcss.com#1520]
Today I almost went insane because I tried to set a `border-bottom` in a Tailwind project where preflight is disabled. In the docs and on play.tailwindcss.com, this works like a charm with setting `border-b`, which sets a `border-bottom-width` property and a border color, for example `border-black`.

In my project, no border was shown. The reason is, that Tailwind sets `border-style: solid;` per default for all elements when preflight is enabled.

A little hint that the example [here](https://tailwindcss.com/docs/border-width#individual-sides) works only when preflight is enabled, respectively when a `border-style` is set, would be cool.

**Comment by adamwathan** [comment]
Thanks for the suggestion, added a note to that page (deploying now 👍).
