### ISSUE TITLE
bug: img tags are not set to self closing

### ISSUE THREAD

**Issue by dev-phantom** [tailwindlabs/tailwindcss.com#1522]
### Description
in the utility first fundamental all the image tags there are not self closing

### steps to reproduce 

1. go to [https://tailwindcss.com/docs/utility-first](url)
2. scroll down to **Using utility classes to build custom designs without writing CSS**
3. check `<img class="h-12 w-12" src="/img/logo.svg" alt="ChitChat Logo">`
4. see error

@adamwathan please i can fix this issue

**Comment by adamwathan** [comment]
Hey! This is totally valid and normal HTML, image tags don’t need the slash to be self closing.

https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags

**Comment by Nothing-Works** [comment]
The / is only required for XHTML & XML.

If you're using a HTML5 doctype, then there's no need to terminate self-closing tags in this way.

This applies to <img src="img.png" />, <br />, <hr /> etc.

I.e. Just use <img src="img.png">, <br> and <hr>.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img for your reference
