### ISSUE TITLE
Svelte kit 1.0 guide - PostCSS configuration not working

### ISSUE THREAD

**Issue by eflatz** [tailwindlabs/tailwindcss.com#1540]
Hi,

following SvelteKit [installation guide](https://tailwindcss.com/docs/guides/sveltekit) I had issue with PostCSS config. 
I posted configuration file on sveltekit github repo [here](https://github.com/sveltejs/svelte-preprocess/issues/470#issuecomment-1385758143) that worked for me.

Cheers,
e.

**Comment by thecrypticace** [comment]
@eflatz Can you provide a github repo that reproduces errors that you're having? I just followed the guide step-by-step and everything is working as expected.

**Comment by eflatz** [comment]
@thecrypticace thanks for the follow up. It looks like it was fixed in the later versions of sveltekit.
