### ISSUE TITLE
Documentation does not mention flex properly it confuses the user

### ISSUE THREAD

**Issue by khanakia** [tailwindlabs/tailwindcss.com#1547]
I was looking for the flex properly and it does not have `display:flex` property mentioned in docs however tailwindcss does have `flex` class so we should add that so it doesn't confuse the new user.

https://tailwindcss.com/docs/flex

**Comment by adamwathan** [comment]
Hey! The display property is documented on the display page:

https://tailwindcss.com/docs/display#flex
