### ISSUE TITLE
tailwindui.com - component code error

### ISSUE THREAD

**Issue by amcd-dev** [tailwindlabs/tailwindcss.com#1552]
Hi Tailwind team,

Just letting you know there is an error in the code snippet for the very last component (With Checkboxes) on this page https://tailwindui.com/components/application-ui/lists/tables

The error is on line 51 (the first div)

`<div class="px-4 sm:px-6 lg:px-8">`

should be

`<div className="px-4 sm:px-6 lg:px-8">`

otherwise React throws a console error about 'class' being used

**Comment by bradlc** [comment]
Hey @amcd-dev, thanks for letting us know, this has now been updated 👍
