### ISSUE TITLE
Docs for rotate missing negative values

### ISSUE THREAD

**Issue by justingolden21** [tailwindlabs/tailwindcss.com#1553]
Docs here: https://tailwindcss.com/docs/rotate

Don't have negative values such as `-rotate-90` even though those values are perfectly valid and default TailwindCSS behavior.

**Comment by adamwathan** [comment]
Hey! The docs for negative values are on that page right here:

https://tailwindcss.com/docs/rotate#using-negative-values

We don't document negative values in the table at the top of the page for any utilities if that's what you mean — instead we document negative values as a sort of modifier you can apply to any of the positive value utilities.
