### ISSUE TITLE
Grammatically incorrect sentence on site

### ISSUE THREAD

**Issue by veritymedia** [tailwindlabs/tailwindcss.com#1557]
In the [CSS Variables section ](https://tailwindcss.com/docs/customizing-colors#using-css-variables) on the TW site there is a grammatically incorrect sentence.

"Don't include the color space function or opacity modifiers won't work" 
Should remove "wont work" or just add an "as it".

"Don't include the color space function or opacity modifiers as it won't work" 

I don't want to be that guy, and though its a small issue still wanted to bring it up.

**Comment by adamwathan** [comment]
Hey! The sentence is correct, it is saying that the opacity modifier feature won't work if you include the color space function.

"Don't include the color space function, because if you do it will prevent the opacity modifiers from working" is the verbose way of saying what that sentence says.

**Comment by veritymedia** [comment]
@adamwathan No no, I get the meaning. Its just the sentence is not grammatically correct as its currently written.  It just reads strangely. "Don't include X wont work".

But hey, if it work it works. :)
