### ISSUE TITLE
Flex example reports flex-1 but flex-none is also applied

### ISSUE THREAD

**Issue by ivan94fi** [tailwindlabs/tailwindcss.com#1568]
https://github.com/tailwindlabs/tailwindcss.com/blob/022919b63050e8aa72a6e108f699353837c9993a/src/pages/docs/flex.mdx?plain=1#L109

In [`flex-none` docs](https://tailwindcss.com/docs/flex#none), the code block reports that the third `div` has `flex-1`, but the example is rendered with `flex-none` as the third div does not shrink or grow, as in the following screenshot:

<details>
    <summary>Screenshot</summary>

![03-04-2023_09-38-56](https://user-images.githubusercontent.com/30447023/229430543-8890fc8a-6b4e-4af9-886d-404be85ad2b9.png)

</details>

I think it is enough to edit the docs text to reflect the code.

**Comment by reinink** [comment]
Hey thanks for the heads up on this, I've corrected this: https://github.com/tailwindlabs/tailwindcss.com/commit/46d6cf5ac4eb096aa5687b2c8dfbbfdb13ec0690 🤙
