### ISSUE TITLE
Tailwindcss documentation does not explain how to access properties defined under theme.extends

### ISSUE THREAD

**Issue by projektorius96** [tailwindlabs/tailwindcss.com#1571]
Let's consider a [grid-template-columns](https://tailwindcss.com/docs/grid-template-columns) example as follows:
```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      gridTemplateColumns: {
        // Simple 16 column grid
        '16': 'repeat(16, minmax(0, 1fr))',

        // Complex site-specific column configuration
        'footer': '200px minmax(900px, 1fr) 100px',
      }
    }
  }
}
```

**LET ME ASK YOU** : Is it so difficult to give a simple example aside as you go by reading the docs over, rather than googling, stackoverflowing reading some people examples out of between-the-lines, that accessing properties defined within `theme.extend.defaultKey.arbitrary_name` alike signature could be achieved just by doing the following i.e.:

```html
<div class="grid grid-cols-16">
    <!--  -->
</div>

<div class="grid grid-cols-footer">
    <!--  -->
</div>
```

The only implicitly mentioned thing is:
> Use the grid-cols-{n} utilities to create grids with n equally sized columns
> OP: _at least then say that -{n} could be also used as reference to some arbitrary-value defined under theme.extend.defaultKey_

[List of defaultKey (Default Keys)](https://tailwindcss.com/docs/theme#configuration-reference)

The following does not contain information about what I've just mentioned above . 
> Learn more about customizing the default theme in the [theme customization](https://tailwindcss.com/docs/theme#customizing-the-default-theme) documentation.

**Comment by projektorius96** [comment]
I will be looking forward to hearing more updates from this . Thanks for a prompt reply. Cheers !

**Comment by JoaoJulio-hub** [comment]
Hello! I noticed that the example for acessing themes.extends properties is missing from the Tailwind documentation. I would love to contribute to the project by adding this missing example.

Before I start, could you provide more information about the specific feature that needs to be demonstrated in the example? Also, is there any specific format or style that I should follow when creating the example?


Thank you for your help, and I'm excited to contribute to the Tailwind community!

**Comment by DavideFrancescon** [comment]
@adamwathan I'd like to add the example for it, I think it's safe to say that after 3 and a half months @JoaoJulio-hub is not going to do it...

**Comment by thecrypticace** [comment]
Hey, thanks for the suggestion (and the initial version @DavideFrancescon)!

We've rewritten the whole extending section to better explain how it works in general and provide more detail.

The updates are now live here: https://tailwindcss.com/docs/theme#extending-the-default-theme

Thanks again! ✨
