### ISSUE TITLE
Spacing documentation doesn't list all usages

### ISSUE THREAD

**Issue by justingolden21** [tailwindlabs/tailwindcss.com#1573]
I removed `8` from my spacing config and the whole project crashes because I have -8 top position: `-top-8`

> By default the spacing scale is inherited by the padding, margin, width, height, maxHeight, gap, inset, space, and translate core plugins.

- https://tailwindcss.com/docs/customizing-spacing

**Comment by justingolden21** [comment]
We should update the docs to list **all** usages

**Comment by thecrypticace** [comment]
Hey! So there's two things to note here:
- The `top` utility comes from the `inset` core plugin which covers the `inset`, `inset-x`, `inset-y`, `top`, `right` `bottom`, `left`, `start`, and `end` utilities.
- "negative" versions of utilities are generated on the fly from your config. For example, if you have `spacing: {foo: "12px"}`, then `-top-foo` will exist and use a value of `-12px`.

When you removed `spacing.8` from your config it also removed the ability to generate `-top-8` as that utility no longer exists.

To fix this you can either:
1. Add `8` back to the `spacing` config
2. Add `8` as an `inset`-specific config value

I [prepped a Tailwind Play](https://play.tailwindcss.com/9iXn35ACVr) showcasing how to do the 2nd option if that's something that could work for you.

Hope that makes sense! Let me know if you have any more questions.

**Comment by justingolden21** [comment]
Thanks for explaining this in such a detailed yet understandable manner @thecrypticace !

I'd suggest adding something similar into the docs as well.

Maybe replace:

> By default the spacing scale is inherited by the padding, margin, width, height, maxHeight, gap, inset, space, and translate core plugins.

with:

> By default the spacing scale is inherited by the padding, margin, width, height, maxHeight, gap, inset, space, and translate core plugins. (Note that the inset core plugin includes inset-x, inset-y, top, right, bottom, left, start, and end utilities)

May be worth mentioning negative values as well as listing the other plugin utilities. I think it might save some devs some time, and the docs are generally very easy to read yet comprehensive and I think it would benefit people for them to be comprehensive here, even though of course on the inset page it already lists the utilities used.

Thanks again!
