### ISSUE TITLE
Un-necessary step in sveltekit docs

### ISSUE THREAD

**Issue by mikeyhogarth** [tailwindlabs/tailwindcss.com#1588]
https://tailwindcss.com/docs/guides/sveltekit

Regarding step 3, Enable use of PostCSS in <style> blocks.

The SvelteKit generator already puts these lines in for you now so this step is no longer necessary. Happy to send a PR if you agree this can go, but thought it best to check first!

**Comment by adamwathan** [comment]
The less steps the better! Let’s do it 👍🏻
