### ISSUE TITLE
ESM and TypeScript support missing in documentation

### ISSUE THREAD

**Issue by Zercerium** [tailwindlabs/tailwindcss.com#1604]
I know since tailwindcss v3.3 it is possible to configure it with TypeScript or ESM. (Source: [Blog](https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-type-script-support)) In the official Documentation I cannot find a reference to it. I think it would be nice to document this feature and update  or expand some of the install instructions.

**Comment by brandonmcconnell** [comment]
I noticed this as well and have often needed to Google "tailwindcss esm ts support" to find the relevant blog article:
https://tailwindcss.com/blog/tailwindcss-v3-3

**Comment by iampaandey** [comment]
Can you please assign this issue to me @Zercerium
