### ISSUE TITLE
Bug about "hover-focus-and-other-states"

### ISSUE THREAD

**Issue by CreateSun** [tailwindlabs/tailwindcss.com#1605]
When i input something in Styling based on sibling state's input and blur my cursor, If my input value was not a valid email like "george@krugerindus.", my page will automatic scroll to the "Form states"
<img width="774" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/47080570/76dd282d-7e38-4a08-81aa-9bc6e4228601">
<img width="783" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/47080570/37b81a4d-90aa-47e9-a49b-449b81685cdb">

**Comment by adamwathan** [comment]
Thanks! Fixed here: https://github.com/tailwindlabs/tailwindcss.com/commit/60bc4062063d175e9f247226b35c08f7ff811479
