### ISSUE TITLE
Make warning more prominent for peer order

### ISSUE THREAD

**Issue by mmailaender** [tailwindlabs/tailwindcss.com#1609]
Please make this warning for `peer` order more prominent. (e.g. red container) The first time I missed the cross, I thought I could also solve it that way. It took me over an hour to realize that I misread the documentation.
![image](https://github.com/tailwindlabs/tailwindcss.com/assets/87228994/993f35f7-f4bf-46c2-96d4-176f3f243a8f)

https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state

**Comment by adamwathan** [comment]
Thanks for the feedback will take it into consideration! Going to close as no concrete plans to make any specific changes here right now but I appreciate the input.
