### ISSUE TITLE
Vite - Cannot find module '@tailwindConfig' from 'src/components/icons/Icon.tsx'

### ISSUE THREAD

**Issue by padrone1225** [tailwindlabs/tailwindcss.com#1612]
Hi.
By defining an alias in vite.config.js, tailwind.config.js is modularized and used.

However, when unit tests are applied, the following errors appear.
Cannot find module '@tailwindConfig' from 'src/components/icons/Icon.tsx'
![image](https://github.com/tailwindlabs/tailwindcss.com/assets/93643291/1bc2bf1d-89bb-4adc-a01b-c9f58cd1caca)

How should I solve this error?

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
