### ISSUE TITLE
Exposed Keys

### ISSUE THREAD

**Issue by Alain1405** [tailwindlabs/tailwindcss.com#1616]
Sure I must be missing something but it appears like you have committed your (I guess) Algolia API key?

https://github.com/tailwindlabs/tailwindcss.com/blob/d78584431db5454ed27df395f6fd6ed5fa151a2c/src/components/Search.js#L10-L12

**Comment by adamwathan** [comment]
Hey! Those are all public keys, equally available by watching the requests in dev tools even if they weren’t in the repo so nothing to worry about here.
