### ISSUE TITLE
Concerning amount of scripting and memory usage on a completely idle page

### ISSUE THREAD

**Issue by Inwerpsel** [tailwindlabs/tailwindcss.com#1624]
I noticed that even if nothing is happening at all (no elements being rendered, no animations present on the page, no user interaction), something is running exhausting about a third of the performance budget on https://tailwindcss.com/docs/hover-focus-and-other-states

![tailwindbadperf](https://github.com/tailwindlabs/tailwindcss.com/assets/7604138/51a1fcc7-d651-4641-b814-6c2f3245db92)

Even if a lot of things were happening in that time frame, the amount of time spent scripting would be concerning. But in this case it's a completely idle page with nothing happening. Surely this is avoidable.

It could be related to this effect being hit all the time, but the source of it rerunning could be somewhere else.

https://github.com/tailwindlabs/tailwindcss.com/blob/d78584431db5454ed27df395f6fd6ed5fa151a2c/src/layouts/ContentsLayout.js#L146C20-L146C20

It seems like all pages of the site are affected by this, but only in case of the linked page it's a third of the budget. On other pages it's much less (around a tenth with less style recalculation). Nevertheless it still seems completely wasted tasks with no effect, so probably some things get invalidated constantly for no reason. It also triggers a lot of GC.

**Comment by thecrypticace** [comment]
Whoops — thanks for pointing this out! My CPU usage for the page has gone from a consistent 80–100% when idle to below 1%.
