### ISSUE TITLE
Type values have undocumented values.

### ISSUE THREAD

**Issue by NakajimaTakuya** [tailwindlabs/tailwindcss.com#1629]
Type values have undocumented values.
The documentation describes only the following four types

* length
* color
* angle
* list

https://v2.tailwindcss.com/docs/just-in-time-mode#:~:text=Ambiguous%20values

However, the test cases show that there are many other possible values, such as `url:` and `image:`.

https://github.com/tailwindlabs/tailwindcss/blob/615c157a271d0a043d9f45471850aaa49d081604/tests/arbitrary-values.test.html#L211

Is there any reason not to describe them?

**Comment by adamwathan** [comment]
Hey! Those are the docs for v2 which are no longer updated or maintained. In the v3 docs we just link to the list of CSS data types maintained by MDN:

https://tailwindcss.com/docs/adding-custom-styles#resolving-ambiguities

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types

Would be great to add our own documentation for that stuff but just hasn't risen to the top of the priority list — only so much time to work every day and so far there's always been something more important to do with that time. Happy to look at a good PR that meets our standards for style and grammar for it though 👍 

Going to close as not an error or bug and no concrete plans to do anything here right now.

**Comment by NakajimaTakuya** [comment]
@adamwathan 
Yeah, it's true. Sorry.
I was thinking of filing a PR if it was an omission, but the link to the css data type is very clear.
Thanks for taking the time to let me know.
