### ISSUE TITLE
sticky position example is missing B and C

### ISSUE THREAD

**Issue by ianengelbrecht** [tailwindlabs/tailwindcss.com#1631]
In the interactive example, heading A is present but B and C are missing.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This is unfortunately a Chrome rendering bug, we've filed an issue on the Chromium bug tracker (https://bugs.chromium.org/p/chromium/issues/detail?id=1459318). Going to close this for now and hopefully the bug gets fixed soon. Once there is more info I'll comment on this issue as well.

Related:
- https://github.com/tailwindlabs/tailwindcss/issues/11220
- https://github.com/tailwindlabs/tailwindcss/issues/11509
