### ISSUE TITLE
Next.js framework guide overwrites their existing postcss configuration

### ISSUE THREAD

**Issue by NashJames** [tailwindlabs/tailwindcss.com#1634]
You can read about it here: https://nextjs.org/docs/pages/building-your-application/configuring/post-css#customizing-plugins

Seems like if you wish to suggest editing the postcss config file, the guide will need updating to include installing the additional lost plugins and configuration.

Love the project!

**Comment by adamwathan** [comment]
Hey! Yeah you can add those plugins back if you want but I personally wouldn't. `postcss-flexbugs-fixes` only fixes a few IE11 bugs that are no longer relevant, and you don't really need `postcss-preset-env` unless there are specific modern CSS features you want to use that you need to polyfill. None of our Next.js templates use either of those plugins 👍 

Going to close as the configuration steps in the docs are what we intend them to be (and also what you get if you select Tailwind CSS as an option when creating a project with `create-next-app`) but hope that explanation is helpful.
