### ISSUE TITLE
Install Tailwind CSS with Angular Tutorial

### ISSUE THREAD

**Issue by maxiwer** [tailwindlabs/tailwindcss.com#1640]
[Install Tailwind CSS with Angular Tutorial](https://tailwindcss.com/docs/guides/angular) - `npx tailwindcss init` doesn't appear on right place.

**Comment by adamwathan** [comment]
Hey! This looks like the right place to me — where should it be in your opinion?

<img width="1130" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/4323180/dbe2ab77-2b7d-40fd-ac83-a02d2cb3e202">

**Comment by adamwathan** [comment]
Going to close this for now since it's not clear what the issue you're reporting is or what the recommended change is. If you still think this is an issue don't hesitate to open another issue that provides the necessary detail 👍
