### ISSUE TITLE
Incorrect Cursor on Search Bar Hover

### ISSUE THREAD

**Issue by Shreyashingale** [tailwindlabs/tailwindcss.com#1642]
Descripiton: When I hover over the search bar, the cursor changes to the "pointer" cursor instead of the expected "text" cursor. This behavior is confusing for users, as they would normally anticipate the "text" cursor when interacting with a search input field.

Steps to Reproduce:

Open the application or website with the search bar.
Move the mouse cursor over the search bar.

Expected Behavior: The cursor should change to the "text" cursor, indicating that the search bar is ready for text input.

Current Behavior: The cursor changes to the "pointer" cursor, which is not the standard behavior for a text input field.

Screenshots/s:
![image](https://github.com/tailwindlabs/tailwindcss.com/assets/85663556/31be6900-4fa3-4e5b-b9fd-431d7ae8cbca)

Proposed Solution:
To address this issue and display the "text" cursor when hovering over the search bar, we can apply the following CSS to the search input field:
The proposed solution will ensure that when users hover over the search bar, the cursor transforms into the familiar "text" cursor, indicating that the search bar is ready for text input. Implementing this fix will enhance the user experience and make the search functionality more intuitive.

Assignees: @Shreyashingale

Thank you for addressing this issue. I believe fixing the cursor behavior will enhance the user experience. I would like to request to be assigned to this issue so that I can work on resolving it. Looking forward to contributing to the project!

**Comment by adamwathan** [comment]
Hey! It's not a text input, it's a button that opens a dialog, so the current cursor feels appropriate to me.

Same pattern as on the Stripe API docs:

https://stripe.com/docs/api
