### ISSUE TITLE
Space documentation doesn't mention it makes margin and padding not working

### ISSUE THREAD

**Issue by giancarloerra** [tailwindlabs/tailwindcss.com#1643]
The space- documentation should mention that if a parent has space- used, the childrens elements cannot correctly use things like mt- mb- or pt-pb- until space- is taken out from parent element.

**Comment by adamwathan** [comment]
Thanks for the suggestion! Going to close as we try to just use issues to capture things that are broken or incorrect in the documentation, but if this becomes a common point of confusion we can definitely consider adding it to the documentation.
