### ISSUE TITLE
text-overflow page should mention whitespace

### ISSUE THREAD

**Issue by sebilasse** [tailwindlabs/tailwindcss.com#1649]
Currently the examples for `text-overflow`, e.g. “ellipsis” mention the peer-dependency `overflow` like
`text-ellipsis overflow-hidden`
but whitespace is also needed: 
`text-ellipsis overflow-hidden whitespace-nowrap`

**Comment by adamwathan** [comment]
Hey! It's not actually needed in the example we use:

<img width="794" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/4323180/604735d2-edbb-45fc-acf1-70bcc27d83e7">

There the text does wrap and `text-overflow` still truncates the one word that is too long to fit. So going to close this for now as there's no change to make to any of these examples that wouldn't make them incorrect for what they are demonstrating.
