### ISSUE TITLE
How to do Static build in this project? 

### ISSUE THREAD

**Issue by chatgptguru** [tailwindlabs/tailwindcss.com#1657]
I wanted to do Static build in this project so that I can get html, js, css files and then use that in my local server. 
Can you please help me to do Static build in this project?
Thank you

**Comment by merzainc** [comment]
> I wanted to do Static build in this project so that I can get html, js, css files and then use that in my local server. Can you please help me to do Static build in this project? Thank you

Unfortunately, the project has grown large. You might find that a difficult task than just using available docs online. .

**Comment by adamwathan** [comment]
Hey! You can always clone the repo and run the project locally, doesn't need to be a static build to run locally.

Follow the instructions in the README to clone and run the project 👍
