### ISSUE TITLE
Explain whether `.bg-opacity-[x]` can be used alone

### ISSUE THREAD

**Issue by merchako** [tailwindlabs/tailwindcss.com#1664]
The [v3 upgrade guide](https://tailwindcss.com/docs/upgrade-guide#new-opacity-modifier-syntax) explains that Tailwind is moving away from expressing color opacity as its own class

```diff
- <div class="bg-black bg-opacity-25">
+ <div class="bg-black/25">
```

It would be very useful if I could change the opacity of a background without needing to specify its color, such as when I want to inherit or use the default color in a library like [DaisyUI](https://daisyui.com/docs/colors/). It _sounds_ like that functionality is being removed. But maybe I'm wrong.

I'm also coming into this with the expectation that color opacity performs better than [element opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity). It's also more difficult to ensure the [contrast accessibility](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#accessibility_concerns) of text when using element opacity, so I have a default preference toward color opacity.

I would appreciate these questions being answered in the article:
* Were v2 users ever able to specify color opacity without having to specify a color in the same place?
* Does the v3 syntax remove support for specifying color opacity independent of color?
* If not, how can we specify color opacity independent of color in v3 syntax?
* Does element opacity still take a bigger performance hit than color opacity in CSS? (I believe this was the case as recently as 5 years ago.)

**Comment by thecrypticace** [comment]
Hey, so the `bg-opacity-{number}` utilities modify a CSS variable that's used in the background-color CSS property. In CSS `background-color` is NOT inherited, AND, the bg-opacity variable is reset for every element. This means that setting `bg-opacity-{number}` could not children elements

> Were v2 users ever able to specify color opacity without having to specify a color in the same place?

No. `bg-{color}` utilities reset the opacity such that it must be specified on the same element.

> Does the v3 syntax remove support for specifying color opacity independent of color?
> If not, how can we specify color opacity independent of color in v3 syntax?
So the new syntax requires that you specify a color AND opacity. But you had to do that before too.

You _can_ use CSS variables to set them indepdently — for example `bg-red-500/[--my-bg-opacity]`. But changing the property on descendant elements isn't going to do anything unless that element also has a background color that references the opacity. This is becase `background-color` is not an inherited property — and even if it was the background of a child element would paint _on top of_ its parent.

> Does element opacity still take a bigger performance hit than color opacity in CSS? (I believe this was the case as recently as 5 years ago.

I can't speak to this definitively but as far as I know element opacity should theoretically be a *smaller* performance hit than color opacity. The reason being is that an element with an opacity can theoretically paint an entirely opaque representation and then control the alpha value of all of those pixels at once. Though in practice it might end up being the same performance wise. This all really depends on whether or not the GPU is involved in this step, how shaders are written, and other hardware specifics. This makes a blanket statement about this difficult to do with out thorough research.

However, generally, you need not ever worry about element vs color opacity performance. It's unlikely you'd be able to measure the performance difference without running software under a profiler that isolates the scenario and interfaces with special hardware counters.

For your situation, using something like DaisyUI, I'd recommend just re-stating what the background color is and using the new opacity syntax when you need to change it — even if it is the default.
