### ISSUE TITLE
Apparently someone didn't test their own documentation

### ISSUE THREAD

**Issue by BookOfCooks** [tailwindlabs/tailwindcss.com#1665]
1. Start a new SolidStart project
2. Follow the steps on tailwind.com to setup tailwind for solidjs
3. Try, fail, fight for 30 minutes, then arive here, why?

Because the docs are missing the world's most crucial step, **actually using tailwind**:
```
// edit the vite.config.ts or vite.config.js
import solid from "solid-start/vite";
import { defineConfig } from "vite";

export default defineConfig({
  css: {
    postcss: {
      plugins: [
          // This is what you're missing
          (await import("tailwindcss")).default
      ],
    },
  },
  plugins: [solid()],
});
```

This entire step is completely ignored in the [docs](https://tailwindcss.com/docs/guides/solidjs) for some reason, so if someone can add this, that'd be helpful for other a many poor souls.

After putting in the import("tailwindcss"), Close "npm run dev", run it again, and look at your new found success.
A little tip for future documenters. I know your job is tough, but at the very least, test your own shit, I don't want to drive a 3-wheeled Toyota.

Thank you.
BookOfCooks.

**Comment by adamwathan** [comment]
Just followed the documentation step by step and everything is working perfectly, no need to edit the `vite.config.js` file. The `npx tailwindcss init -p` command creates a `postcss.config.js` file that configures Tailwind as a PostCSS plugin for you automatically.

Here's the project after doing exactly what is in the documentation and nothing more:

https://github.com/adamwathan/solid-tailwind-setup-example

If you have any other issues in the future, please report them in a more mature and professional way.
