### ISSUE TITLE
Add svh, lvh, and dvh values to default theme 

### ISSUE THREAD

**Issue by Akira-Kuru** [tailwindlabs/tailwindcss.com#1666]
Related to this Pull Request [Add svh, lvh, and dvh values to default theme](https://github.com/tailwindlabs/tailwindcss/pull/11317) the documentation should be updated to include the large, small and dynamic viewports units.

So far we have been adding this manually and weren't aware that Tailwindcss supports this till we noticed the PR.

**Comment by adamwathan** [comment]
Hey! These aren't in a release yet which is why they aren't in the docs. We track every change to Tailwind internally and update all of the docs when the release actually comes out, so this will get updated when v3.4 is released 👍
