### ISSUE TITLE
Add example json file for all property values when overriding theme (theme.extend)

### ISSUE THREAD

**Issue by basickarl** [tailwindlabs/tailwindcss.com#1672]
While reading https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale is nice and the long list at the bottom is useful I will unfortunately have to manually add each and every one of those values to my config which is time consuming.

It would be better if you can somehow provide an overrides theme will all of the possible values in json format somehow.

1. Easier to see all of the options you have.
2. Easier to edit them and get rid of what you don't need.
3. Possible to write a test  for the current configuration against what tailwind has to offer (when updating tailwind version for example, you can detect if any new properties exist or has been taken away).

Example, I had to transform this:

> 0 | 0px | 0px |  
> -- | -- | -- | --
> px | 1px | 1px |  
> 0.5 | 0.125rem | 2px |  
> 1 | 0.25rem | 4px |  
> 1.5 | 0.375rem | 6px |  
> 2 | 0.5rem | 8px |  
> 2.5 | 0.625rem | 10px |  
> 3 | 0.75rem | 12px |  
> 3.5 | 0.875rem | 14px |  
> 4 | 1rem | 16px |  
> 5 | 1.25rem | 20px |  
> 6 | 1.5rem | 24px |  
> 7 | 1.75rem | 28px |  
> 8 | 2rem | 32px |  
> 9 | 2.25rem | 36px |  
> 10 | 2.5rem | 40px |  
> 11 | 2.75rem | 44px |  
> 12 | 3rem | 48px |  
> 14 | 3.5rem | 56px |  
> 16 | 4rem | 64px |  
> 20 | 5rem | 80px |  
> 24 | 6rem | 96px |  
> 28 | 7rem | 112px |  
> 32 | 8rem | 128px |  
> 36 | 9rem | 144px |  
> 40 | 10rem | 160px |  
> 44 | 11rem | 176px |  
> 48 | 12rem | 192px |  
> 52 | 13rem | 208px |  
> 56 | 14rem | 224px |  
> 60 | 15rem | 240px |  
> 64 | 16rem | 256px |  
> 72 | 18rem | 288px |  
> 80 | 20rem | 320px |  
> 96 | 24rem | 384px

Into this, manually, urgh:
```
      }
        0: '0px',
        px: '1px',
        0.5: '2px',
        1: '1px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        3.5: '14px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        14: '56px',
        16: '64px',
        20: '20px',
        24: '96px',
        28: '112px',
        32: '128px',
        36: '144px',
        40: '160px',
        44: '176px',
        48: '192px',
        52: '208px',
        56: '224px',
        60: '240px',
        64: '256px',
        72: '288px',
        80: '320px',
        96: '384px',
      }
```

Now imagine us doing that for _everything_. Not very developer friendly.

**Comment by adamwathan** [comment]
Hey! It sounds like what you really want is the `npx tailwindcss init --full` option:

https://tailwindcss.com/docs/configuration#scaffolding-the-entire-default-configuration

You can also find all of the default values here, as linked from the documentation:

https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/config.full.js

Hope that helps!
