### ISSUE TITLE
PurgeCSS for just tailwind

### ISSUE THREAD

**Issue by garygreen** [tailwindlabs/tailwindcss.com#168]
It would be good if there were an example in the docs on how to use PurgeCSS in webpack JUST to purge tailwind and not the rest of your bundle.

The reason why this is important is because PurgeCSS may end up getting rid of all your `node_modules` and other `@import` stuff in your bundle. For this reason, I would recommend to use an actual webpack loader such as `https://github.com/americanexpress/purgecss-loader` to JUST operate on the tailwind bundle - that way it keeps your existing styles, third party stuff in node_modules intact.

Here's how I've managed to do it:

```js
const fg = require('fast-glob')

class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-Za-z0-9-_:\/]+/g) || [];
  }
}

const purgeCssPaths = fg.sync([
    'views/**/*.blade.php',
    'js/**/*.js',
    'js/**/*.vue',
    '!**/node_modules'
]);

module: {
  rules: [
    {
      test: /tailwind.css$/,
        use: ExtractTextPlugin.extract({
          fallback: styleLoader,
          use: [
            {
              loader: 'css-loader',
                options: {
                  importLoaders: 1,
                  minimize: prod,
                  sourceMap: sourcemap
                }
            },
            {
              loader: '@americanexpress/purgecss-loader',
              options: {
                paths: purgeCssPaths,
                extractors: [
                {
                  extractor: TailwindExtractor,
                    extensions: ["html", "js", "php", "vue"]
                  }
                ]
              },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: sourcemap
            }
          }
        ]
      })
    },
  ]
}
```

(this is for webpack 3, I'm not sure what the convention would be for webpack 4)

**Comment by adamwathan** [comment]
This is one of the reasons I'd like to integrate Purgecss into Tailwind itself, so we can make this possible more easily.

The hard part about doing it in user-land is that you shouldn't really have a separate Tailwind bundle, it really needs to be mixed in with all of your own custom CSS to avoid specificity issues.

My CSS files normally look something like this:

```css
@tailwind base;

/* any of my own custom base styles go here */
a {
  @apply text-blue-600 font-semibold;
}

@tailwind components;

/* any of my own custom component styles go here */

.btn {
  /* ... */
}

@tailwind utilities;

/* any of my own custom utilities go here */
@responsive {
  .rotate-90 { /* ... */ }
}
```

This is the only way to follow an [ITCSS](https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/) sort of approach and make sure classes are applied in the right order.

So because of that, you can't really purge just the Tailwind styles, because everything ends up mixed together.

What I normally do is make sure to add any JS plugins that include classes to my Purgecss template list. So I'll have things like `./node_modules/sweetalert/**/*.js` in there and stuff.

Alternatively you can use the `/* purgecss start ignore */` and `/* purgecss end ignore */` comments to make sure Purge is only targeting the Tailwind styles:

```css
@tailwind base;

/* purgecss start ignore */
@import "./custom-base"
/* purgecss end ignore */

@tailwind components;

/* purgecss start ignore */
@import "./custom-components"
@import "./vendor-components"
/* purgecss end ignore */

@tailwind utilities;

/* purgecss start ignore */
@import "./custom-utilities"
/* purgecss end ignore */

@tailwind screens;
```

You're right though it would be a good idea to add this example to the docs 👍

**Comment by jerguslejko** [comment]
@adamwathan any way I can help with this one? I'd love to see this included in Tailwind.

**Comment by aerni** [comment]
@adamwathan Does the method with `/* purgecss start ignore */` and `/* purgecss end ignore */` really work for you? I'm using Laravel Mix and it's not working. It might be, that the comments get stripped before the scss is processed by purgecss. [Similar issue here](https://github.com/FullHuman/purgecss/issues/90)

What are you using to build?

**Comment by aerni** [comment]
I actually made it work like this `/*! purgecss start ignore */` `/*! purgecss end ignore */`. Might be like this because im using `scss`. No idea, but it works :-)

**Comment by evdama** [comment]
It seems with an uprade to typescript 3.7.5 an error with class-based extractors in combination with purgecss becomes apparent https://github.com/FullHuman/postcss-purgecss/issues/55 ?

**Comment by andresgutgon** [comment]
I have a similar problem. When I do this:
``` scss
/*! purgecss start ignore */
 @import "tailwindcss/base";
/*! purgecss end ignore */
```

In development mode on my webpack I get this
``` scss
img,
video {
  max-width: 100%;
  height: auto;
}
```
But in production i get this:

``` scss
video{max-width:100%;height:auto}
```

Looks like PurgeCSS is not respecting properties concatenated with `,` maybe?

**Comment by garygreen** [comment]
@andresgutgon you might want to check your postcss plugins to see if any of them are interfering/stripping out the comments. They need to remain there in the correct place so purgecss can parse them properly.

**Comment by andresgutgon** [comment]
The thing is that I can see partially the normalize.css that's added by `@import "tailwindcss/base"` but PurgeCSS is removing `img,` from original code:
``` css
img,
video {
  max-width: 100%;
  height: auto;
}
```

**Comment by andresgutgon** [comment]
No it was solved with @aerni comment 👏 Thanks!

My change was from this:
``` css
/* purgecss start ignore */
 @import "tailwindcss/base";
/* purgecss end ignore */
```
To this:
``` css
/*! purgecss start ignore */
 @import "tailwindcss/base";
/*! purgecss end ignore */
```

The only change is in the format of SASS comments. With `!` you keep those comments in the build pipeline to be read by PurgeCSS and do its job. Awesome
