### ISSUE TITLE
vue-3-vite instructions don't work

### ISSUE THREAD

**Issue by surferjeff** [tailwindlabs/tailwindcss.com#1680]
I followed the instructions here:
https://v2.tailwindcss.com/docs/guides/vue-3-vite

As captured in this git commit:
https://github.com/surferjeff/ClickCount/commit/948315e4eb22691231e1eb24f27af45920cca7f7

And then [added some tailwind styling](https://github.com/surferjeff/ClickCount/commit/53baa7fa5ce7d9889bef7415f384beb8a3e8bef2), but they had no effect.

**Comment by RobinMalfait** [comment]
Hey!

You are looking at the docs for `v2`, but in your project you are using `v3` of Tailwind CSS.
Please use the v3 docs instead: https://tailwindcss.com/docs/guides/vite#vue

**Comment by surferjeff** [comment]
Thank You!
