### ISSUE TITLE
Link from 'Quick search..' item list opens a new tab and redirect the current page too

### ISSUE THREAD

**Issue by danivideda** [tailwindlabs/tailwindcss.com#1687]
When I click a result from Quick search, for example, 'Flex direction', it opens a new tab. 
It also redirect the current page to 'Flex direction'. 

I don't think this is an intended behavior

**Comment by bradlc** [comment]
Hey @danivideda, thanks for reporting this, it's now fixed 👍

**Comment by danivideda** [comment]
That was quick. Thank you!
