### ISSUE TITLE
Using Css Variables section with custom alpha channel for hsl colours has / instead of ,

### ISSUE THREAD

**Issue by kingrea** [tailwindlabs/tailwindcss.com#1690]
as title. On this page:
https://tailwindcss.com/docs/customizing-colors#using-css-variables

`    colors: {
      // Using modern `rgb`
      primary: 'rgb(var(--color-primary) / <alpha-value>)',
      secondary: 'rgb(var(--color-secondary) / <alpha-value>)',

      // Using modern `hsl`
      primary: 'hsl(var(--color-primary) / <alpha-value>)',
      secondary: 'hsl(var(--color-secondary) / <alpha-value>)',

      // Using legacy `rgba`
      primary: 'rgba(var(--color-primary), <alpha-value>)',
      secondary: 'rgba(var(--color-secondary), <alpha-value>)',
    }`

the / in hsl should be a comma. At least that hows I've been able to get it working with custom colours.

**Comment by RobinMalfait** [comment]
Hey!

This is the correct syntax, but you have to make sure that you setup the `--color-primary` value as the individual channels as described here: https://tailwindcss.com/docs/customizing-colors#using-css-variables (all the way at the bottom)
<img width="780" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/1834413/89e006ec-996c-48e9-b83f-172b4efb1805">

Here is a Tailwind Play example with that setup. Make sure to checkout the HTML, CSS and Config tabs: https://play.tailwindcss.com/VyjAeJhFWb
