### ISSUE TITLE
Please move `just-in-time-mode` section to v3 documentation!!

### ISSUE THREAD

**Issue by Nurai1** [tailwindlabs/tailwindcss.com#1704]
https://v2.tailwindcss.com/docs/just-in-time-mode.
I've killed myself several hours to know how to solve problem with arbitrary css variables for border or text.

**Comment by adamwathan** [comment]
Hey! Everything in there should be covered in the current documentation — what specifically were you looking for that you couldn't find in the new docs?

**Comment by adamwathan** [comment]
Going to close as no plans to bring that page over since all of the content has been integrated into the appropriate pages in the documentation but still would love to hear what you had a hard time finding so don't hesitate to reply 👍  Thanks!

**Comment by Nurai1** [comment]
@adamwathan Maybe you can say where can i find this text at least??
<img width="921" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/45640899/24ebdb88-8bdc-4a1f-9130-953c59004dcc">
