### ISSUE TITLE
Scrollbar styling

### ISSUE THREAD

**Issue by jithesh-poojari** [tailwindlabs/tailwindcss.com#1709]
Hello, I am making suggestions to style the scrollbar.

I don't know this issue is already given. If yes? Please Sorry

The scrollbar is default of chrome. I just wanted to website to have a styled scrollbar.
Because it's a css library. Right?

**Comment by reinink** [comment]
Hey! Currently Tailwind CSS doesn't provide utilities for styling scrollbars, although I suspect we'll eventually add them. Until then, maybe give this plugin a try: https://github.com/lukewarlow/tailwind-scrollbar-utilities

Good luck! 🤙

**Comment by jithesh-poojari** [comment]
Oh! That is also good. Thanks for giving plugin suggestion.

But What I said is about is the scrollbar is tailwind.com website.
Sorry for Not clearing it.
