### ISSUE TITLE
Lack of documentation on how to use tailwind in client side components

### ISSUE THREAD

**Issue by kasir-barati** [tailwindlabs/tailwindcss.com#1720]
Hi dear reader, I just followed this doc step by step: https://tailwindcss.com/docs/guides/nextjs

But still IDK why I cannot use tailwind classes in my client side components. I mean everything is cool in the server side components but not in the client side. I am not sure if this is a but so I thought maybe I am just missing something, therefore I though to open an issue in the doc first in favor of having a better doc and also if this is a bug then creating an issue in tailwind or nextjs repo.

Here you can see my setup: https://github.com/kasir-barati/my-nextjs-journey/tree/tailwind

Please note that I already read these issues and I am pretty sure since I do not have much of conf or code they are not really related:
- https://github.com/tailwindlabs/tailwindcss/issues/9954
- Althought this one looked a bit similar but still they are not same issue: https://github.com/tailwindlabs/tailwindcss/issues/10161

Looking forward to know why is this happening

**Comment by kasir-barati** [comment]
Also `npx tailwindcss init -p` step is unnecessary and "Configure your template paths" can be modified a bit to reflect the current behavior since we already have `tailwind.config.ts` file and there we probably wanted to configure our temp path

**Comment by RobinMalfait** [comment]
Hey!

You are mixing the `app/` router and `pages/` directory. You currently only setup Tailwind CSS in the `app/` directory.

Currently you only include `globals.css` in your `layout.tsx` inside of the `app/` folder. If you go to the `posts/` url then that code is not used at all.

To solve it, you can do multiple things:
1. The simplest thing to do is to add this import: `import '../app/globals.css';` in your `pages/_app.tsx` file.
2. You can also setup a `globals.css` in the `pages` file directory itself such that the `app/` and `pages/` folders are separated.

However, I would recommend to only use a single mechanism, I would suggest to _only_ us the `app/` folder. If you move the `posts/index.tsx` to `app/posts/page.tsx` and you remove the `pages` folder then this should still work as is.

Hope this helps!

**Comment by kasir-barati** [comment]
Thanks, It was helpful. I hope we could add this as a note [to this page](https://tailwindcss.com/docs/guides/nextjs) since it causes confusion IMO.

BTW do you mean use only `/apps` in my nextjs app and if I need client side component I should use `'use client'` in that component @RobinMalfait?

And is it a bad idea to have `/pages` and `/apps` at the same time in one project?
