### ISSUE TITLE
redirecting to related docs from the old versions

### ISSUE THREAD

**Issue by a0m0rajab** [tailwindlabs/tailwindcss.com#1723]
This happened to me when I was googling some tailwind stuff, google provided the legacy docs website in the first results. 

when I picked up the latest version of tailwind it redirected me to the main page, I would expect it to redirect me  to the related page in docs instead of going to landing page.

## Reproduce: 

- go to: https://v1.tailwindcss.com/docs/flex-wrap 
- change the version to tailwind 3 
- you will get redirected to landing page.

## Expectations: 

I would expect the redirection to happen to the related page: 

https://tailwindcss.com/docs/flex-wrap

Related component: 

https://github.com/tailwindlabs/tailwindcss.com/blob/3685ba98ce42f7db291fce34620ac5faaba3e1a6/src/components/VersionSwitcher.js#L72

**Comment by adamwathan** [comment]
Hey thanks for the suggestion! Would welcome a PR for this but unfortunately no chance this ever makes it to the top of the priority list internally, so going to close. Appreciate the feedback regardless!
