### ISSUE TITLE
Bug: `adding-base-styles` redirects to `adding-custom-styles#adding-base-styles`

### ISSUE THREAD

**Issue by camsteffen** [tailwindlabs/tailwindcss.com#1728]
**Steps to reproduce**

1. Go to https://tailwindcss.com/docs/preflight#headings-are-unstyled
2. Click on the link with the text "adding your own base styles".
3. Note the current url is https://tailwindcss.com/docs/adding-base-styles
4. Refresh the page

**Expected behavior**

The page stays the same

**Actual behavior**

The page redirects to https://tailwindcss.com/docs/adding-custom-styles#adding-base-styles

---

You can also reproduce by, instead of refreshing, click some link on the page and then navigate the browser _back_.

I also noticed that the first page doesn't have a corresponding link in the left side nav, so it seems like an abandoned page.

I wonder if the proper fix is to reconcile the difference between the two pages/sections and combine them into once place.

**Comment by adamwathan** [comment]
Thanks for catching this, old links to a page that should've been deleted since we've been redirecting it for a while! Fixed here: https://github.com/tailwindlabs/tailwindcss.com/commit/ac2cebe6685fe7ebf59f613ca51c12e21eb624ef
