### ISSUE TITLE
Provide an example for spacing between list items

### ISSUE THREAD

**Issue by sdavids** [tailwindlabs/tailwindcss.com#1758]
Instead of:

```html
<ul>
  <li>A</li>
  <li class="mt-2">B</li>
  <li class="mt-2">C</li>
  <li class="mt-2">D</li>
  <li class="mt-2">E</li>
  <li class="mt-2">F</li>
</ul>
```

One can do:

```html
<ul class="[&_li+li]:mt-2">
  <li>A</li>
  <li>B</li>
  <li>C</li>
  <li>D</li>
  <li>E</li>
  <li>F</li>
</ul>
```

I think this is a common use case and it should be documented.

It avoids needless repetition.

**Comment by adamwathan** [comment]
Hey! We have a whole set of built-in utilities for this actually with a dedicated page:

https://tailwindcss.com/docs/space

Thanks for the feedback.
