### ISSUE TITLE
Install Tailwind CSS with Vite for typescript's command should be added to the documentation.

### ISSUE THREAD

**Issue by hossain45** [tailwindlabs/tailwindcss.com#1768]
> The user seeks guidance on installing Tailwind CSS with Vite using TypeScript. But documentation has vite installation only for reactjs.

### Solution:

The follwing command initializes a new Vite project named my-project with the React and TypeScript template. 

`npm create vite@latest my-project -- --template react-ts`

**Comment by adamwathan** [comment]
Thanks for the feedback! Right now I think it makes more sense for this sort of thing to live in the Vite documentation — I think it would be a little much if we included examples with all of the different possible templates you can use with Vite. If this becomes a really common problem we hear about from a lot of people then we can reconsider including specific instructions for more templates in the docs.
