### ISSUE TITLE
Next.js guide is missing a step to import css file

### ISSUE THREAD

**Issue by brabeji** [tailwindlabs/tailwindcss.com#1769]
From the guide, it really looks like the `globals.css` file is imported by default and the integration seems to not work at all.

**Comment by brabeji** [comment]
Yup, as the first step states:

> Start by creating a new Next.js project if you don’t have one set up already.

I had my Next.js project already created. Possibly I've removed the then unnecessary import a long time ago when I was using another styling solution (i.e. CSS-in-is). I think that the guide should account for this case.

**Comment by adamwathan** [comment]
Okay makes sense! It's really tricky to write the guides in a way that can account for changes someone has made to the default state of a scaffolded project, especially without the guides becoming extremely noisy and verbose, so at the moment at least we keep the instructions focused on the changes you need to make after creating a new project.

Appreciate the feedback and will keep it mind — if this becomes a really common struggle we can rethink how we teach this.
