### ISSUE TITLE
[Proposal] Restoring the @screen directive description to the documentation

### ISSUE THREAD

**Issue by skrzepij** [tailwindlabs/tailwindcss.com#1780]
Hello! 

At the beginning, just want to say, I understand that you recommend using the `screen()` function, instead of using the directive of the same name. 

You wrote about this over a year ago with the PR updating the documentation (https://github.com/tailwindlabs/tailwindcss.com/pull/1431), where you also mentioned that you are considering marking the `@screen` directive as deprecated, as it is less supported. 

However, it turns out that currently there is no possibility to use the `screen()` method in combination with Sass (or just it's not written down) because entry like: 

```SCSS
@media screen(md) { 
  ...
} 
```

Returns an error with the content: 
> SassError: expected "{". 

Meanwhile, defining styles like:
```SCSS
@media (min-width: theme('screens.sm')) { ... } 
```
It is incredibly long, compared to what the Tailwind has accustomed us to and what we can get using the `@screen` directive.

Having used the `@screen` directive in various SCSS-based projects for several years, I have never had a problem with it and records of this type are much neater: 
```SCSS
@screen md { .. }
```

If the `@screen` directive works and, as you can see, sometimes even better than the `screen()` function, can we just add it to the documentation as it is still a supported alternative? 
Let the information remain that you recommend using the function, but it seems to me that leaving a choice in case of occurred problems is better than writing code that looks like some kind of workaround.  

Thanks for your time! 
Best regards

**Comment by reinink** [comment]
Hey! Thanks for this suggestion, and while I totally understand where you're coming from, as a general rule Tailwind is moving in a direction where we have less custom functions and directives, simplifying the overall API surface area.

While these custom functions and directives are handy, they risk conflicting with real CSS features that get added in the future. For example, in Tailwind CSS v4.0 we're working on removing our custom `@layer` directive as it conflicts with this new CSS directive.

Further, as our documentation [recommends](https://tailwindcss.com/docs/using-with-preprocessors#using-sass-less-or-stylus), we generally think it's better to not use Tailwind with preprocessors like Sass, Less, or Stylus.

As CSS continues to evolve with the addition of features like nesting, layers (and potentially even [custom functions and mixins](https://github.com/w3c/csswg-drafts/issues/9350)), the need for preprocessors is going away. In fact, related to the `@screens` directive, CSS is adding a native `@custom-media` directive ([see here](https://www.w3.org/TR/mediaqueries-5/#custom-mq)) where you can use CSS variables in your media query definitions:

```css
@custom-media --md (min-width: 768px);

@media (--md) {
  .foo { color: blue; }
}
```

So given that I think we should probably leave the `@screen` directive out of the Tailwind CSS docs. In fact I'm now realizing that this directive is still mentioned on the "Using with Preprocessors" page, so I'm going to make a note to remove it from there as well.

---

That all said, for what it's worth, you technically can use the `screen()` function with Sass, you just need to wrap it in parentheses, like this:

```scss
@media (screen(md)) { 
  .foo {
    color: blue;
  }
} 
```

[Here's an example](https://sass-lang.com/playground/#eJwzNHTITU3JTFTQKE4uSk3N08hN0dRUqFbgUlDQS8vPV6gGMhQUkvNz8ousFJJySlOtgQK1XLUKAOKXEBw=) using the Sass playground. Technically this results in an extra set of parentheses, but this still works fine in Tailwind, as you can [see here](https://play.tailwindcss.com/6oc4adsBB1).

Hope that helps! 💪

**Comment by skrzepij** [comment]
Hi @reinink! 
Thank you very much for the explanations. Now everything is clear to me and your approach makes sense. 😄  

You helped me realize that modern CSS can accomplish numerous tasks on its own and how much I was behind the edge too much focusing on Sass 😆 
 
Additionally, the path you have taken within the Tailwind team has led me to consider using pure CSS in my upcoming projects as well. Maybe even on the current one. There are some good tips here 🙌🏻 

All the best!

**Comment by reinink** [comment]
@skrzepij awesome, glad I could help! 💪
