### ISSUE TITLE
Is there going to be any border-1 for border-width?

### ISSUE THREAD

**Issue by theuiguru** [tailwindlabs/tailwindcss.com#1782]
According to the docs for border-width, https://tailwindcss.com/docs/border-width, there seems to be no support for border-width of 1px, is there going to be or sticking with even numbered widths?

I know that we can include our own styles using tailwindcss config but in case for vanilla html/css apps, a border-1 would be helpful since it provides a more thinness to the border outline for buttons.

**Comment by adamwathan** [comment]
Hey! The `border` class adds a 1px border.

**Comment by theuiguru** [comment]
So I just add class="border..." and that's it?

**Comment by theuiguru** [comment]
Never mind, just tested it out and it works now, thanks Adam for the clarification!
