### ISSUE TITLE
Mobile: Changing page doesn't scroll to top

### ISSUE THREAD

**Issue by mrleblanc101** [tailwindlabs/tailwindcss.com#1785]
Hi,
When you change page using the sidebar in mobile, the scroll doesn't get reset. So if you were at the very bottom of the page, you'll need to scroll back to the top every time after changing the page which is very annoying.

**Comment by amrahs02** [comment]
can you elaborate more about this issue , or if you can explain with video example to understand better.

**Comment by mrleblanc101** [comment]
Changing page doesn't bring you to the top. I fail to see how I can make this clearer.
https://github.com/tailwindlabs/tailwindcss.com/assets/17392251/a1bf60e9-3546-4934-aaa0-ed26fb803537

**Comment by mrleblanc101** [comment]
Any news ? This seems like an easy fix.

**Comment by mrleblanc101** [comment]
I notice this only happens when I click links inside the burger menu, but not with links inside the page or the `Next section` and `Previous section` links at the bottom of the page, so there must be something different with the links inside the burger menu.

**Comment by amrahs02** [comment]
I'm still looking into the problem to figure out what's causing it. I'll let you know as soon as I make some progress.

**Comment by amrahs02** [comment]
It looks like everything is working fine on my machine.

Chrome - 
[Screencast from 2024-03-18 08-41-29.webm](https://github.com/tailwindlabs/tailwindcss.com/assets/65103353/5f3b6109-5e4c-498a-8eca-ca7f31886945)

firefox - 
[Screencast from 2024-03-18 08-40-44.webm](https://github.com/tailwindlabs/tailwindcss.com/assets/65103353/daaafb8c-4cb8-4877-9bee-797841b15cd7)

ms-edge - 
[Screencast from 2024-03-18 08-39-31.webm](https://github.com/tailwindlabs/tailwindcss.com/assets/65103353/c6d4e44b-38d9-41c4-81e3-f1dab2289b39)

**Comment by mrleblanc101** [comment]
Must be something Safari related then, I'm on an iPhone (iOS 17.4).
Or maybe something that doesn't show up in the browser mobile emulator.

**Comment by adamwathan** [comment]
> Any news ? This seems like an easy fix.

Just because an issue has been opened, it doesn't automatically become the number one priority for the team. Will take a look when we have time to take a look.

**Comment by mrleblanc101** [comment]
@adamwathan  oh yeah I know, just that I have the video he asked and didn't hear back.

**Comment by reinink** [comment]
Hey! Thanks for making us aware of this issue, this has been resolved in #1800 👍

**Comment by mrleblanc101** [comment]
Indeed it work, thank you
