### ISSUE TITLE
Adding a custom font

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindcss.com#1788]
I find that the way to add a font is not complete. I have been to this page (https://tailwindcss.com/docs/font-family) but I think it is missing how to import a fonts.css file.

What do you think ? :)

**Comment by adamwathan** [comment]
Thanks for the feedback, added a short section about it here to make sure people don't think Tailwind magically sets up your custom font files for you or anything:

https://github.com/tailwindlabs/tailwindcss.com/commit/b3f7d95e3414a33dcd823928bfc5df8d9c30febc

**Comment by seb-jean** [comment]
Thanks Adam :)
