### ISSUE TITLE
The `align-items` property is not set to 'center'.

### ISSUE THREAD

**Issue by perterHUAN** [tailwindlabs/tailwindcss.com#1806]
While reading through https://tailwindcss.com/docs/utility-first, I noticed that custom CSS styles were not reflecting the `align-items: center` setting on the `.chat-notification` element, which differs from the intended centered appearance in the demo. When employing Tailwindcss, however, the `items-center` utility class was utilized.
```diff
.chat-notification {
    display: flex;
+  align-items: center; 
    max-width: 24rem;
    margin: 0 auto;
    padding: 1.5rem;
    border-radius: 0.5rem;
    background-color: #fff;
    box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
  }
```

Additionally, the `padding-top: 0.25rem` declared on the `.chat-notification-content` is found to be unnecessary, as it does not visibly affect the design in the demonstration, and similarly, this padding adjustment was not implemented when configuring the element with Tailwindcss utilities.
```diff
.chat-notification-content {
    margin-left: 1.5rem;
-   padding-top: 0.25rem;
}
```

**Comment by adamwathan** [comment]
Thanks, updated!
