### ISSUE TITLE
[doc] Installation Guide / Framework / Vite: Should Mention `import 'style.css'`

### ISSUE THREAD

**Issue by Saplyn** [tailwindlabs/tailwindcss.com#1813]
## The Problem

The [Installation Guide (v3) of Vite/Vue](https://tailwindcss.com/docs/guides/vite#vue) is missing an important step: adding `import './style.css'` to the `main.{js,ts}` file.

## Possible Fix

Adding a step between 4 and 5:

````md
**Importing Tailwind CSS File in `main.{js,ts}`**

Ensure your CSS file is being imported in your `./src/main.{js,ts}` file:

```js
// import './assets/main.css'
import './style.css'

import { createApp } from 'vue'

import App from './App.vue'

const app = createApp(App)
app.mount('#app')
```
````

## Background

I'm kind of new to frontend and tried following the [installation guide for vue with vite](https://tailwindcss.com/docs/guides/vite#vue), but found it not working. After some research I found [the tailwind v2 doc](https://v2.tailwindcss.com/docs/guides/vue-3-vite) which mentioned that I should `import './index.css'` in my `./src/main.ts`:

> Finally, ensure your CSS file is being imported in your `./src/main.js` file:
>
> ```js
> // src/main.js
> import { createApp } from 'vue'
> import App from './App.vue'
> import './index.css'
> 
> createApp(App).mount('#app')
> ```
>

Which is missing in the v3 doc.

**Comment by adamwathan** [comment]
Hey! I just created a brand new Vite/Vue project following the instructions and the `style.css` file is already being imported in `main.js` by default:

<img width="1143" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/4323180/34090758-2538-4bdd-a3cd-d6752c0607df">

What steps did you follow to create your project?

**Comment by Saplyn** [comment]
I created the vue project with `vite@latest` and `Customize with create-vue` option, tool used is bun:

```
$ bun create vite@latest
...
✔ Select a variant: › Customize with create-vue ↗
...
```

Here's the entire reproduction (with some clean up):

```
$ bun create vite@latest
✔ Project name: … reprod_tailwind_vue
✔ Select a framework: › Vue
✔ Select a variant: › Customize with create-vue ↗

Vue.js - The Progressive JavaScript Framework

✔ Add TypeScript? … No / [Yes]
✔ Add JSX Support? … [No] / Yes
✔ Add Vue Router for Single Page Application development? … No / [Yes]
✔ Add Pinia for state management? … No / [Yes]
✔ Add Vitest for Unit Testing? … [No] / Yes
✔ Add an End-to-End Testing Solution? › No
✔ Add ESLint for code quality? … [No] / Yes
✔ Add Vue DevTools 7 extension for debugging? (experimental) … No / [Yes]

Scaffolding project in /home/saplyn/codespace/reprod_tailwind_vue...

Done. Now run:

  cd reprod_tailwind_vue
  bun install
  bun dev

$ cd reprod_tailwind_vue

$ bun install
bun install v1.1.3 (2615dc74)

 + @tsconfig/node20@20.1.4
 + @types/node@20.12.6
 + @vitejs/plugin-vue@5.0.4
 + @vue/tsconfig@0.5.1
 + npm-run-all2@6.1.2
 + typescript@5.4.4
 + vite@5.2.8
 + vite-plugin-vue-devtools@7.0.25
 + vue-tsc@2.0.11
 + pinia@2.1.7
 + vue@3.4.21
 + vue-router@4.3.0

 184 packages installed [123.00ms]

$ bun install -D tailwindcss postcss autoprefixer
bun add v1.1.3 (2615dc74)

 installed tailwindcss@3.4.3 with binaries:
  - tailwind
  - tailwindcss
 installed postcss@8.4.38
 installed autoprefixer@10.4.19 with binaries:
  - autoprefixer

 89 packages installed [35.00ms]

$ npx tailwindcss init -p

Created Tailwind CSS config file: tailwind.config.js
Created PostCSS config file: postcss.config.js

$ nvim tailwind.config.js

$ bat tailwind.config.js
───────┬────────────────────────────────────────────────────────
       │ File: tailwind.config.js
───────┼────────────────────────────────────────────────────────
   1   │ /** @type {import('tailwindcss').Config} */
   2   │ export default {
   3   │   content: [
   4   │     "./index.html",
   5   │     "./src/**/*.{vue,js,ts,jsx,tsx}",
   6   │   ],
   7   │   theme: {
   8   │     extend: {},
   9   │   },
  10   │   plugins: [],
  11   │ }
  12   │
───────┴────────────────────────────────────────────────────────

$ nvim ./src/style.css

$ bat ./src/style.css
───────┬────────────────────────────────────────────────────────
       │ File: ./src/style.css
───────┼────────────────────────────────────────────────────────
   1   │ @tailwind base;
   2   │ @tailwind components;
   3   │ @tailwind utilities;
───────┴────────────────────────────────────────────────────────

$ bat ./src/main.ts
───────┬────────────────────────────────────────────────────────
       │ File: ./src/main.ts
───────┼────────────────────────────────────────────────────────
   1   │ import './assets/main.css'
   2   │
   3   │ import { createApp } from 'vue'
   4   │ import { createPinia } from 'pinia'
   5   │
   6   │ import App from './App.vue'
   7   │ import router from './router'
   8   │
   9   │ const app = createApp(App)
  10   │
  11   │ app.use(createPinia())
  12   │ app.use(router)
  13   │
  14   │ app.mount('#app')
───────┴────────────────────────────────────────────────────────
```

some supplementary info, may be helpful:

- `bun --version`: 1.1.3
- `node --version`: v20.11.1
- OS: Ubuntu 22.04 jammy
- Shell: zsh

I have also tried again with npm & node with the same steps as above, but the `style.css` is still not auto-imported. Am I doing it the wrong way? Sorry if this is my problem.

**Comment by thecrypticace** [comment]
Hey! So this is happening because when you ran the create command you didn't specify the Vue template like it does in our docs:

`npm create vite@latest my-project -- --template vue`

Here we specify `-- --template vue` to sidestep the selection / customizations when creating a Vite project. 

Our guides are written such that you run all the commands exactly as specified. The reason for this is that when you select a different template, apply customizations, or run the commands any differently you will inevitably run into some differences. Sometimes the differences are minor and inconsequential, but sometimes they can be more significant. We can't possibly account for every iteration of every possible customization which is why we have a few options that we show on the docs (React, Vue, and Svelte) and pass in the template option in the command.

In your case I'd edit `./assets/main.css` instead of creating/editing a new `style.css` file because the `./assets/main.css` file is the one that's already imported in `src/main.ts`.

Hope that helps! ✨
