### ISSUE TITLE
UWU 

### ISSUE THREAD

**Issue by AugustinMauroy** [tailwindlabs/tailwindcss.com#1825]
https://github.com/SAWARATSUKI/KawaiiLogos
https://x.com/sawaratsuki1004/status/1792148262574776564

**Comment by adamwathan** [comment]
Cool, thanks for sharing! Not planning to do anything with it here though.

**Comment by AugustinMauroy** [comment]
what do you thinks to do something like https://react.dev/?uwu=true ?
