### ISSUE TITLE
Incomplete Vite setup instructions

### ISSUE THREAD

**Issue by knivets** [tailwindlabs/tailwindcss.com#1830]
https://stackoverflow.com/a/77830926/1491475

**Comment by adamwathan** [comment]
Hey! I just followed all of the steps from the documentation line for line and everything works as expected. Here's the project:

https://github.com/adamwathan/my-vite-tw-project

**Comment by knivets** [comment]
Thanks for the quick reply! Apologies, I was porting my app from CRA to Vite and forgot to run the `npx tailwindcss init -p` which generates the postcss config file!
