### ISSUE TITLE
Use of Project as a Starting Point for Course Website in University

### ISSUE THREAD

**Issue by lausannel** [tailwindlabs/tailwindcss.com#1842]
Hi,

I am reaching out to ask about the possibility of using this project as a **starting point for a course website** I am involved with. We appreciate that the source code is made available as an educational resource, as stated in the project's README.

Before proceeding, we would like to ensure that this aligns with your guidelines and restrictions. The course website would be strictly for educational purposes, and there will be **no commercial use under any circumstances**.

Could you please confirm if using the project in this manner would be acceptable, or if there are specific conditions we should adhere to? Additionally, I want to state clearly that if our proposed use is not permissible, we fully respect your rights and will refrain from using the project.

Your guidance on this matter would be greatly appreciated. Thank you!

**Comment by lausannel** [comment]
Hi, if there has been a chance to look into it?

**Comment by adamwathan** [comment]
Hey! If it's a private project you are working on and submitting as part of course work or something I don't see an issue but if it's actually going to be published to the internet publicly that wouldn't be something we could permit. Better to just study the source and borrow some ideas for how to solve the things you need to solve in your project as needed in that case.
