### ISSUE TITLE
No class name for styling word-break: break-word

### ISSUE THREAD

**Issue by SwapnilRaj1708** [tailwindlabs/tailwindcss.com#1846]
I went through the documentation and tried all the text-overflow class names possible in Tailwind, but none could provide the same CSS property `word-break: break-word` provides.

Also the Tailwind class name `break-words` could not solve the problem either. I had to write this property in the style attribute in React to make it work.

I tested all these class names on different browsers such as Chrome, Chrome Canary, Firefox, and Opera but found the same results on all.
This is my 5th project where I felt the need for a class name to exist for this property.

I hope the team at Tailwind will update this soon.

**Comment by adamwathan** [comment]
Hey! Check out the discussion for this feature here:

https://github.com/tailwindlabs/tailwindcss/discussions/2213

Going to close since not an issue with the docs but thanks for the feedback!
