### ISSUE TITLE
Overscroll bug across entire site, especially on the docs navbar

### ISSUE THREAD

**Issue by Jauharmuhammed** [tailwindlabs/tailwindcss.com#1847]
<img width="1440" alt="Screenshot 2024-07-23 at 3 53 00 PM" src="https://github.com/user-attachments/assets/8c5e21e9-36e7-4919-8dac-fd5873757508">

Browser : Chrome
OS: macOS,

**Describe your issue**

there is an overscroll behaviour bug across the entire https://tailwindcss.com/ website. on the docs section navbar look really weird on scroll.

**Comment by Jauharmuhammed** [comment]
Solved the issue, and raised a pr

https://github.com/tailwindlabs/tailwindcss.com/pull/1848

**Comment by adamwathan** [comment]
Hey! Going to just live with this for now for the reasons mentioned in the PR comment but thanks for raising regardless.
