### ISSUE TITLE
Broken homepage (cannot expand the demo)

### ISSUE THREAD

**Issue by gitcnd** [tailwindlabs/tailwindcss.com#1862]
It blocks at this wide, never letting us reach XL or 2XL

![pic_2024-08-14_21 14 39_816](https://github.com/user-attachments/assets/e2944a9f-1c10-40ac-bf6b-94b4f8106ec5)

**Comment by adamwathan** [comment]
Hey! This is just the design, the demo width maxes out at same width as the rest of the content on the page. The other breakpoints in the background are just there as a hint to show you all of the default breakpoints in the framework.
