### ISSUE TITLE
Getting started - Postcss npx init command

### ISSUE THREAD

**Issue by TearingMoon** [tailwindlabs/tailwindcss.com#1867]
In the getting started tab of docs, inside the "Using postcss" section , the first instruction could be more accesible if instead of `npx tailwindcss init` you had `npx tailwindcss init -p` to also generate the required Postcss config file.
From this: 
![imagen_2024-08-30_131503916](https://github.com/user-attachments/assets/5c539022-d43f-409b-82bb-a90e492ab493)
To this:
![imagen_2024-08-30_131633821](https://github.com/user-attachments/assets/b7331a8e-cb9f-4d9f-be8e-c9269dadd82a)

Hope it was helpfull, have a nice day!

**Comment by adamwathan** [comment]
Hey! We did this on purpose expecting most people using that guide to already be using PostCSS and therefore already have a config file, but still appreciate the feedback and will consider this change if it seems like this is an issue for a lot of people.
