### ISSUE TITLE
Install Tailwind CSS with Vite Using React missing vite config

### ISSUE THREAD

**Issue by lydamian** [tailwindlabs/tailwindcss.com#1874]
Missing documentation:
Vite config needs these fields to work properly

```
  css: {
    postcss: {
      plugins: [tailwindcss()],
    },
  },

```

Steps to reproduce
Follow the steps in this link here https://tailwindcss.com/docs/guides/vite
Snapshot here for history
<img width="555" alt="Screenshot 2024-09-12 at 4 07 20 PM" src="https://github.com/user-attachments/assets/101a6cb2-ae41-4746-b811-4efd8c03cb76">

See relevant discussion here https://stackoverflow.com/a/77557221

**Comment by adamwathan** [comment]
Hey! This is unnecessary if you use `npx tailwindcss init -p` (like we do in the guide) which creates a `postcss.config.js` file with Tailwind preconfigured. Vite will read that file, the config doesn't need to be in the Vite config file for it to work 👍
