### ISSUE TITLE
Add font-display: swap; to avoid blank texts

### ISSUE THREAD

**Issue by tobimori** [tailwindlabs/tailwindcss.com#1883]

**Comment by adamwathan** [comment]
We used to have it but it caused layout shift so removed it. Going to stick with how it is now until there's another solution to the layout shift stuff.

**Comment by tobimori** [comment]
Have you taken a look at https://github.com/unjs/fontaine?

**Comment by tobimori** [comment]
For me, the site takes around 2-3s to load which is very long. 😄
