### ISSUE TITLE
Consider Removing `space-between` utilities from the 'Core Concepts' Docs

### ISSUE THREAD

**Issue by sebastiancarlos** [tailwindlabs/tailwindcss.com#1887]
The page [Utility First](https://tailwindcss.com/docs/utility-first) contains an example that uses `space-between` utilities like `space-x-4`.

Since most users should be using the `gap` property instead (which works with both Flexbox and Grid, as mentioned in the limitations section of the [Space Between Utilities](https://tailwindcss.com/docs/space#limitations) documentation), I believe this example (and likely others in the early documentation) should be updated to use `gap` instead.

This page is particularly important because it provides the first detailed Tailwind example for someone reading the documentation sequentially.

Thanks for your time!

**Comment by adamwathan** [comment]
Thanks, pushed that change 👍
