### ISSUE TITLE
Building docs fails

### ISSUE THREAD

**Issue by bart** [tailwindlabs/tailwindcss.com#19]
Unfortunately I'm getting a similar issue. Updated node and NPM to latest version. This is my log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development' ]
2 info using npm@5.8.0
3 info using node@v9.11.1
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @~predevelopment: @
6 info lifecycle @~development: @
7 verbose lifecycle @~development: unsafe-perm in lifecycle true
8 verbose lifecycle @~development: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/bart/Code/docs/tailwindcss/node_modules/.bin:/Users/bart/Code/docs/tailwindcss/node_modules/.bin:/Users/bart/.config/yarn/link/node_modules/.bin:/Users/bart/Code/docs/tailwindcss/node_modules/.bin:/Users/bart/.config/yarn/link/node_modules/.bin:/usr/local/lib/node_modules/yarn/updates/0.17.10/bin/node-gyp-bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/Users/bart/.composer/vendor/bin:./vendor/bin:/Users/bart/Code/spark-installer:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @~development: CWD: /Users/bart/Code/docs/tailwindcss
10 silly lifecycle @~development: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack --progress --hide-modules --env=local --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @~development: Returned: code: 1  signal: null
12 info lifecycle @~development: Failed to exec development script
13 verbose stack Error: @ development: `cross-env NODE_ENV=development webpack --progress --hide-modules --env=local --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid @
15 verbose cwd /Users/bart/Code/docs/tailwindcss
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/9.11.1/bin/node" "/usr/local/bin/npm" "run" "development"
18 verbose node v9.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ development: `cross-env NODE_ENV=development webpack --progress --hide-modules --env=local --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the @ development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by adamwathan** [comment]
Similar issue to what? I'm not sure what you're talking about here, what are you trying to do, build the docs? Happy to help but need a lot more information.

**Comment by bart** [comment]
Hey @adamwathan Yes, exactly. I tried to build the docs. Looks like the initial comment has been removed. That's why my question looks so weird.

I set everything up but when I run yarn run dev I'm getting the error from above. Node and NPM are on the latest version.
