### ISSUE TITLE
docs- *container* - missing example with configuring "screens"

### ISSUE THREAD

**Issue by Nikita0x** [tailwindlabs/tailwindcss.com#1929]
Hi. 
Correct me if I am wrong but in the docs I only found examples of how to configure *container* utility class for *padding* and *center* fields, but not *screens*. I'm not sure if its a *bug* or not.

https://tailwindcss.com/docs/container#basic-usage

![image](https://github.com/user-attachments/assets/96fbccca-5681-4cc4-a994-5b2ea9e9d291)

**Comment by adamwathan** [comment]
Hey! Yeah this is something we've left out purposely because it's a feature I regret adding and consider deprecated (in fact none of these options exist in the v4 beta), and we always exclude deprecated features from the docs.
