### ISSUE TITLE
Maybe add horizontal scroll bar for code snippet?

### ISSUE THREAD

**Issue by Nothing-Works** [tailwindlabs/tailwindcss.com#206]
![screenshot-tailwindcss com-2019 05 14-13-53-38](https://user-images.githubusercontent.com/18606648/57665388-c3253400-764f-11e9-83f2-adf62a94c018.png)

**Comment by Nothing-Works** [comment]
![screenshot-tailwindcss com-2019 05 14-14-03-17](https://user-images.githubusercontent.com/18606648/57665709-1481f300-7651-11e9-8b15-e54c537e6c3a.png)

Same thing here, after resizing the textarea, I can not resize back.

**Comment by missmatsuko** [comment]
What page is the first screenshot from? 

I see the code snippets are scrollable, although the scroll bar is not actually visible.

Second screenshot issue would be fixed if they swap overflow-hidden to overflow-auto. I'm not sure if they had a reason to use overflow-hidden here, though.

**Comment by hacknug** [comment]
Scroll bar was hidden by Adam to prevent it from overlapping code snippets if I remember correctly. Not sure about the second issue though.
