### ISSUE TITLE
The website doesn't respond (perhaps in Iran)

### ISSUE THREAD

**Issue by mrmowji** [tailwindlabs/tailwindcss.com#220]
First of all thanks for this great work.

I was trying to reach the website and read the Doc. But it doesn't work.
I get these familiar error messages:
**This site can’t be reached.**
**tailwindcss.com took too long to respond.**

It works when I use Tor but it's slow. So it seems my IP or perhaps IPs from my country (**Iran**) is kind of blocked. Yet I couldn't understand why this could be the case.

**P.S.** I know lots of websites have blocked us.

**Comment by simonswiss** [comment]
@mrmowji, are you able to access the Tailwind docs site these days?

It is now hosted on Vercel - wondering if it's accessible from Iran?

I sure hope so! ❤️

**Comment by mrmowji** [comment]
@simonswiss Wow. Thanks man. It works now. Really appreciated. Algolia still blocks us, but no problem. We're one step closer.
