### ISSUE TITLE
[Feature Proposal] Instructions for Angular 7 and Angular Universal Starterkit.

### ISSUE THREAD

**Issue by Ballpin** [tailwindlabs/tailwindcss.com#229]
I was earlier going to give a tailwindcss a go. For my part i was going to use it with Angular Universal Starterkit (Angular v7). I saw that many people (including me) had a bit hard to make it work. 

In the end i succeded to get it up and running through Tailwindcss Instructions and with two other dependencies. I would like to share this knowledge with others through your documentation. So even more people in the community can use it with Angular 7 and Angular Universal. Will it be alright if i add it to the documentation?

EDIT: I saw this ticket https://github.com/tailwindcss/tailwindcss/issues/481 and you can actually get it to work through Postcss. Plus ng-tailwind is not needed at all as dependicy, what you need is actually something that allows you to edit webpack without ejecting.

**Comment by Ballpin** [comment]
Sweet! :-) I have now added instructions, would be great if someone could try them and confirm they work as intended. 

However as mentioned in my MR, just recently version 8 of Angular was released. So i have not tried it on that version.

**Comment by adamwathan** [comment]
I've captured this in our internal roadmap for our integration guides, so going to close 👍🏻 Thanks.
