### ISSUE TITLE
Add input add-on example

### ISSUE THREAD

**Issue by royvanv** [tailwindlabs/tailwindcss.com#275]
I was watching [Adam's stream](https://www.youtube.com/watch?v=0aTRN9CSCY0) and he was building a search input with an icon in. It would be nice to see this example in the docs.

Here's a little code example I took and simplified (took out the responsive stuff and focus styles) from the Workcation project:

```html
<div class="relative">
    <div class="absolute inset-y-0 left-0 flex items-center pl-3">
        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 fill-current text-gray-600">
            <path d="M16.32 14.9l1.1 1.1c.4-.02.83.13 1.14.44l3 3a1.5 1.5 0 0 1-2.12 2.12l-3-3a1.5 1.5 0 0 1-.44-1.14l-1.1-1.1a8 8 0 1 1 1.41-1.41l.01-.01zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z"></path>
        </svg>
    </div>
    <input placeholder="Search" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-500 rounded py-3 px-4 mb-3 leading-tight pl-10 pr-4 py-2">
</div>
```

**Comment by RolandStuder** [comment]
Where would you put something like this though? This seems more appropriate for a library of components to play around with, not really as part of the general documentation.

You could submit it to https://tailwindcomponents.com/

**Comment by royvanv** [comment]
A great place for it would be under [Components > Form](https://tailwindcss.com/components/forms/).

It would a good example of what is possible with Tailwind.

**Comment by simonswiss** [comment]
Hey!

Doing a little "end of the year" cleanup, and trying to keep only real _issues_ (bugs, incorrect documentation etc) in the issues list.

FWIW there are a few examples of inputs with an icon inside it in Tailwind UI, which the `/components` URL now goes to, and is in a way a showcase of what you can do with Tailwind CSS.
