### ISSUE TITLE
Feature for the documentation: Dark mode

### ISSUE THREAD

**Issue by JayBox325** [tailwindlabs/tailwindcss.com#310]
I'm currently working on a very dark site with an off-black background and it's pretty jarring jumping between that and the Tailwind docs. A dark mode theme for the documentaion would be phenomenal.

**Comment by benknight** [comment]
I'd like to throw another vote on the pile for this. Tailwind is one of the only docs site I reference that doesn't support dark mode.

**Comment by suprafly** [comment]
I agree with @benknight - I am just coming to Tailwind and found it a bit disconcerting that the front page says, 'Don’t want to be one of those websites that blinds people when they open it on their phone at 2am?', but then the docs don't have a dark mode.

**Comment by adamwathan** [comment]
Would be great to have I agree, unfortunately we are only a handful of people with a million things to work on.

**Comment by rraihansaputra** [comment]
Understandable, but for the time being, does anybody have a Stylus .css that's workable with the Tailwind docs? The 'Dark Mode' plugin doesn't work too well on the docs.

**Comment by benknight** [comment]
@adamwathan it sounds like you're de-prioritizing dark mode as if it's just bonus programmers-only feature for funsies. In my opinion dark mode is a core accessibility feature, and it should be prioritized the same as other a11y features like keyboard accessibility, focus states, legible font sizes, etc. Either way, as times goes on things that _don't_ support dark mode will feel outdated (if they don't already) which is contrary to Tailwind's marketing efforts I'm sure, so I'm sure we'll have it eventually. Also I would image that dark mode on the docs has the double benefit of also communicating clearly to designers that they can use it to support dark mode in their own apps. Anyway thanks for the consideration.

**Comment by reinink** [comment]
Hey ya'll, the docs website [is now available](https://twitter.com/tailwindcss/status/1472945416035520519) in dark mode 🙌

[![image](https://user-images.githubusercontent.com/882133/146788599-94a8a7d8-6428-46c3-a097-caa942a80c87.png)](https://tailwindcss.com/)

**Comment by benknight** [comment]
Great work guys!
