### ISSUE TITLE
Add links to next/previous article

### ISSUE THREAD

**Issue by ghost** [tailwindlabs/tailwindcss.com#330]
It would be great if there were links at the bottom of each page to the next/previous article just like it is for example in [Vue guide](https://vuejs.org/v2/guide/). Right now navigating through documentation on mobile looks like this: after scrolling down/reading article I have scroll back to the top, tap menu icon and find a next article on the list which is time consuming and a little bit annoying. Adding those links would improve usability and reading experience not only on mobile but also on desktop.

**Comment by adamwathan** [comment]
Great idea, would happily accept a PR for this.

**Comment by nicolaspayot** [comment]
Hi there! 👋 I'd happily give a try on that feature request if it's still available to take.
