### ISSUE TITLE
Update docs for plugin changes in v1.2

### ISSUE THREAD

**Issue by swanson** [tailwindlabs/tailwindcss.com#341]
Update the plugin docs to incorporate new functionality added in v1.2: https://github.com/tailwindcss/tailwindcss/releases/tag/v1.2.0-canary.4

**Comment by simonswiss** [comment]
Hey 👋

I know this issue is **very old**, but would you like to have a go at opening a PR to add this missing bit of documentation?

**Comment by swanson** [comment]
@simonswiss I've not written any plugins myself so I'll defer those docs to someone who can better explain it. :)

If memory serves me, I wrote some other docs for the v1.2 release but left this breadcrumb for someone else to pick up.

**Comment by adamwathan** [comment]
Added docs for `withOptions`, thanks.
