### ISSUE TITLE
Scroll to a specific part on sidebar when searched through homepage

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss.com#353]
If I search for `Transition` from homepage, it sure gives me that page but what I want is for it to scroll to that particular section on the sidebar so I have easy access to other transition-related properties.

Now I have to scroll a lot to find it because the docs have gotten to big. It would be cool if the docs, just scroll down automatically to that part like https://www.gatsbyjs.org/ site does if u search for “tailwind” on https://www.gatsbyjs.org/docs

**Comment by simonswiss** [comment]
This is a great suggestion that improves UX a lot 👍 

We are at the early stages of a website redesign internally, so definitely taking note of this as something to consider!

**Comment by adamwathan** [comment]
This actually happens now! Brad built it last week 😄

**Comment by deadcoder0904** [comment]
@adamwathan No, it doesn't. I typed `/` to go to search & typed `grid` & it showed `grid auto rows` but it didn't scroll to `grid auto rows` on the sidebar

**Comment by deadcoder0904** [comment]
I see https://github.com/tailwindlabs/tailwindcss.com/issues/536 opened which is the same thing I want. Idk why this issue was closed tho 🤔
