### ISSUE TITLE
[Recommendation for docs] Button for rem -> px

### ISSUE THREAD

**Issue by codex-zaydek** [tailwindlabs/tailwindcss.com#361]
Often when I see values on the docs, such as:

.max-w-xs | max-width: 20rem;
-- | --
.max-w-sm | max-width: 24rem;

https://tailwindcss.com/docs/max-width/#app

I need to open the Spotlight calculator to convert `rem`s  to `px`s to make sense of the values. I’m sure this gets easier over time, but it would be nice to have and could help new users more quickly starting using Tailwind.

**This is not a feature request for Tailwind** — this applies exclusively to the docs.

**Comment by simonswiss** [comment]
We have had discussions within the team about adding `px` values in the Tailwind Intellisense extension, so you're definitely not the only person thinking about this.

We are in the initial phase of a docs website redesign internally, and I have captured this suggestion as something to consider when we revisit some of the ways data is being displayed on the docs.

Thanks for the suggestion! 👍
