### ISSUE TITLE
Tool to help generate color shades

### ISSUE THREAD

**Issue by oliverpool** [tailwindlabs/tailwindcss.com#366]
Hi,

quoting the [docs](https://tailwindcss.com/docs/customizing-colors/#generating-custom-color-palettes) regarding **Generating custom color palettes**

> A common question we get is "how do I generate the 100–900 shades of my own custom colors?".
>
> Bad news: color is complicated and we've yet to find a tool that does a good job generating these sorts of color palettes. We picked all of Tailwind's default colors by hand, balancing them by eye. Sorry!

I just found out about https://javisperez.github.io/tailwindcolorshades/ (made by @javisperez)which I find amazing!
Surely it is not as good as an "eye-adjusted-palette", but it is a nice help for people without such an eye.

As far as I understood [the code](https://github.com/javisperez/tailwindcolorshades/blob/master/src/scripts/components/palette.vue#L121-L170), it sets the given color to `500` and generates 4 lighter tints and 4 darkers shades (to have the full `100-900` palette).

Would it be possible to link to this tool in the doc? (or is it against some policy to recommend 3rd party tools?)

Something like this for instance:
> A common question we get is "how do I generate the 100–900 shades of my own custom colors?".
>
> Bad news: color is complicated and we've yet to find a tool that does a good job generating these sorts of color palettes. We picked all of Tailwind's default colors by hand, balancing them by eye. 
> You could try your luck with some tailwind-friendly color generators (https://javisperez.github.io/tailwindcolorshades/ for instance)

**Comment by simonswiss** [comment]
That's a great tool indeed! 🎉

I don't think we'll add it to the docs, since there are many great tools built by the community, and we don't want to accidentally send the message that we're endorsing or promoting specific ones.

Lists like https://github.com/aniftyco/awesome-tailwindcss are great for community-built tools like this! 👍
