### ISSUE TITLE
Add docs URL to docs repo

### ISSUE THREAD

**Issue by hacknug** [tailwindlabs/tailwindcss.com#370]
This repo is _missing_ a link to the docs site. Would be great if it could be added as it would save users landing on this repo a couple clicks or typing it manually. No biggie though 👍

**Comment by royvanv** [comment]
Also a link back to this would be nice. Something like "Improve this page on Github" I see other documentation sites use.

**Comment by simonswiss** [comment]
Looks like the repo now has a link to tailwindcss.com 👍

As per the "edit on GitHub" link, we're receiving a large amount of docs update suggestions already. Worried an on-page link would bring large volumes of PR to review for our small team 😅 

We'll discuss it internally though. In the early stages or a website redesign, so it's a good time to revisit this idea!
