### ISSUE TITLE
[Feature Proposal] Make code snippets in documentation editable

### ISSUE THREAD

**Issue by mderazon** [tailwindlabs/tailwindcss.com#373]
Documentation site is very good!
I think it will be very cool if the code in the examples was editable and changes were reflected directly in the view above.

This gives newcomers a simple way to experiment, sort of a playground

**Comment by simonswiss** [comment]
That's a great suggestion, thanks for sharing!

We've captured this internally, and if there is enough demand for it that we can justify de-prioritizing other projects, we'll consider implementing it 👍
