### ISSUE TITLE
Add documentation section with official purgecss extractors configuration for Vue

### ISSUE THREAD

**Issue by rightaway** [tailwindlabs/tailwindcss.com#380]
The Tailwind docs have a section about purgecss configuration for extractors here https://tailwindcss.com/docs/controlling-file-size/#writing-purgeable-html, and the Vue docs have it herehttps://purgecss.com/guides/vue.html#usage, but they are different from each other. So as a user of both Tailwind and Vue I don't know whether I should use one or the other or a combination of them somehow.

Could a small section for Vue (and possibly other frameworks) be added to the Tailwind documentation page I linked saying what the official recommendation is for a purgecss extractor when using Tailwind and Vue together?

**Comment by codex-zaydek** [comment]
Here’s what I’m doing:

```js
const purgecss = require("@fullhuman/postcss-purgecss")({
	content: [
		"./public/**/*.html",
		"./src/**/*.js",
	],
	defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
	whitelistPatterns: [/^[a-z]+:grid-cols-\d+$/],
})

module.exports = {
	plugins: [
		require("tailwindcss"),
		require("autoprefixer"),
		...process.env.NODE_ENV === "production"
			? [purgecss]
			: [],
	],
}
```

Essentially, all I’ve added is `"./public/**/*.html"` to `content` to target classes in my base `index.html` page, and `whitelistPatterns: [/^[a-z]+:grid-cols-\d+$/]` to cover all grid classes. I haven’t needed to touch `defaultExtractor` once.

Does that help?

I started using PurgeCSS very quickly after adopting TailwindCSS. I find it’s a really elegant solution. Here’s the whole repo for the sample in question: https://github.com/codex-src/filesystem-prototype.

**Comment by simonswiss** [comment]
Hey!

We now have an integration guide with Vue3, which contains the info on setting up PurgeCSS to work properly.

Doing some "end of the year cleaning". I will close this issue now as things have changed a bit since then, and handling purge happens within the Tailwind config file.

Thanks everyone for your input 👍
