### ISSUE TITLE
feature: Provide vanilla css converted from markdown.less

### ISSUE THREAD

**Issue by mark-hahn** [tailwindlabs/tailwindcss.com#387]
I just discovered docs/blob/master/source/_assets/less/markdown.less and it contained some less code for markdown that would be really useful to me.  Having a vanilla css version would be greatly appreciated.  It would be a bit of an effort for me to learn enough less to install less and compile it.

I tried online converters and they all choked.  I assume it is the less nesting.

**Comment by simonswiss** [comment]
I don't think that's a thing anymore in the new NextJS website, unfortunately. 😅

I suggest asking in the community discord or in our [Tailwind GitHub discussions](https://github.com/tailwindlabs/tailwindcss/discussions)!
