### ISSUE TITLE
Tiny navigation bug

### ISSUE THREAD

**Issue by KKSzymanowski** [tailwindlabs/tailwindcss.com#394]
Go here: https://tailwindcss.com/docs/pseudo-class-variants/
Click on some link in the navigation panel on the right, for example **Last-child**.
Click Back in the browser.

Page goes blank and a wild error in the console appears:
![image](https://user-images.githubusercontent.com/13980973/78664684-ce6ef700-78d4-11ea-8ba8-57ac0ac5c3b8.png)

Tested on latest Chrome and Firefox.

**Comment by simonswiss** [comment]
Looks like this is not an issue anymore in the NextJS site 👍
