### ISSUE TITLE
Copy paste does not work well for code snippets

### ISSUE THREAD

**Issue by jenstornell** [tailwindlabs/tailwindcss.com#406]
To quickly get a working syntax it can be tempting to copy/paste the code in the examples. It's not possible, at least not in a good way.

See the problem? I get the plusses and the minuses?

```
// tailwind.config.js
module.exports = {
  theme: {
    fontFamily: {
-     'sans': ['-apple-system', 'BlinkMacSystemFont', ...],
-     'serif': ['Georgia', 'Cambria', ...],
-     'mono': ['SFMono-Regular', 'Menlo', ...],
+     'display': ['Oswald', ...],
+     'body': ['Open Sans', ...],
    }
  }
}
```

### Solution 1

Add a tab with a copy/paste friendly textarea.

### Solution 2

Add a copy to clipboard button

--

Both solutions require that you actually have a copy/paste friendly version available.

## Update - Solution 3 - Add comments instead

On the breakpoints page I found a great code snippet that was possible top copy/paste. It has comments which can still be there without breaking anything.

```js
module.exports = {
  theme: {
    screens: {
      'tablet': '640px',
      // => @media (min-width: 640px) { ... }

      'laptop': '1024px',
      // => @media (min-width: 1024px) { ... }

      'desktop': '1280px',
      // => @media (min-width: 1280px) { ... }
    },
  }
}
```

**Comment by simonswiss** [comment]
That's a valid point!

We're in the early stages of a website redesign internally, and we'll definitely consider making the experiencer of copying code snippets better! 👍
