### ISSUE TITLE
Add a cheatsheet

### ISSUE THREAD

**Issue by jenstornell** [tailwindlabs/tailwindcss.com#407]
To quickly find the class name you just forgot, a cheat cheet is really helpful. The best one I've found is https://nerdcave.com/tailwind-cheat-sheet. However it does not provide new things from 1.3 what I can see.

**To me this is what makes a good cheat cheet**

- Compact
- Accordion to see syntax - to make it compact
- Reference links to the docs for deep information
- Show which version each command is added for
- Always up to date

From a tech perspective to do something like this you probably need to generate parts of it automatically, else it will be a pain to maintain.

**Comment by simonswiss** [comment]
Merging with https://github.com/tailwindlabs/tailwindcss.com/issues/81 👍
