### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mhyfritz** [tailwindlabs/tailwindcss.com#416]
In chapter https://tailwindcss.com/docs/pseudo-class-variants, paragraph

![tw-docs-p](https://user-images.githubusercontent.com/718983/81135982-77535500-8f5a-11ea-9b75-4b067fa963ad.png)

some links are broken. These are all sections that have a "version badge" in their header, e.g. `Group-focus v1.3.0+`. In that example, the link points to https://tailwindcss.com/docs/pseudo-class-variants#group-focus, however the ID of the `h2` tag is `id="group-focus-v1-3-0"`:

![tw-docs-h2](https://user-images.githubusercontent.com/718983/81135988-7b7f7280-8f5a-11ea-8c74-f1a84ad026fd.png)

In the `ON THIS PAGE` sidebar, the links are correct.

**Comment by psjishnu** [comment]
@mhyfritz  do I need to change id of every elements to  "group-focus"  or  change id of every elements to "group-focus-v1-3-0"

**Comment by psjishnu** [comment]
@mhyfritz It will be better to change   [group-focus](#group-focus)  to  [group-focus](#group-focus-v1-3-0)

**Comment by simonswiss** [comment]
This doesn't seem to be an issue anymore on that page, I will close this issue.

Thanks for reporting this initially! 👍
