### ISSUE TITLE
Colors and alpha channel

### ISSUE THREAD

**Issue by jonathan-s** [tailwindlabs/tailwindcss.com#422]
In here https://tailwindcss.com/docs/functions-and-directives/#theme you see an example of how to reference color from the theme. I think it would be good to also make a note that this won't work if you need to reference a color with an alpha channel. 

This was explained in an [old issue](https://github.com/tailwindcss/tailwindcss/issues/190#issuecomment-343746925). And it would be great to include that example in the docs.

**Comment by simonswiss** [comment]
Hey @jonathan-s 👋

Not sure I interpret this correctly, but it looks like using `theme()` to access an `rgba` color value works properly now.

Can you check this example and let me know if that's what you meant?

https://play.tailwindcss.com/m3rNhQxOF9

In there, I can reach for a color with alpha transparency via `theme` in my CSS, and it works just fine:


```js
// tailwind config
module.exports = {
  theme: {
    extend: {
      colors: {
        'semi-transparent': 'rgba(59, 130, 246, 0.5)',
      },
    },
  },
}
```

```css
.bg-semi-transparent-from-theme-function {
  background-color: theme("colors.semi-transparent");
}
```

**Comment by jonathan-s** [comment]
Cool, that works for me.
