### ISSUE TITLE
Inaccessible text colors

### ISSUE THREAD

**Issue by estevanmaito** [tailwindlabs/tailwindcss.com#425]
This issue was raised in the library repo, and I found that my comment (https://github.com/tailwindcss/tailwindcss/issues/1750#issuecomment-626950561) would fit better as an issue here.

The useful part is the following:

---
Category titles use `text-gray-500` over a white background. It results in a constrast ratio of 2.26, while the minimum should be 4.5 (AA) or 7.0 (AAA).  `text-gray-600` would result in a contrast ratio of 4.02 and still fail. `text-gray-700` would result in both AA and AAA passing, with 7.53.

Subcategories fail too. They are using `text-gray-600`, resulting in 4.02. `text-gray-700` would pass AA with 6.14 but fail AAA. `text-gray-800` would pass both tests with a CR of 9.79 and also still be a step above the gray scale of the category titles if implemented with the previous solution.

---

I could PR, but I understand that it's also a design decision, so you may find that just changing text to a darker gray wouldn't fit the current layout, so I'll wait for feedback.

**Comment by psjishnu** [comment]
@estevanmaito  Do the file that is to be modified ( Color change to text-gray-800 ) is in the repo   https://github.com/tailwindcss/docs/ ?

**Comment by estevanmaito** [comment]
Yes

**Comment by psjishnu** [comment]
![screen](https://user-images.githubusercontent.com/33541774/82121225-0d804a00-97a9-11ea-9d45-4214c4cc18e4.jpg)


@estevanmaito  So will the issue will be solved if both category and subcategory are given color text-gray-800 ?

**Comment by estevanmaito** [comment]
The last sentence of OP.

> I could PR, but I understand that it's also a design decision, so you may find that just changing text to a darker gray wouldn't fit the current layout, so I'll wait for feedback.

I'm waiting for maintainers to tell if my proposed solution would fit their design. If it fits, I can PR.

**Comment by simonswiss** [comment]
Hey! 👋

We're at the early stages of an internal Tailwind docs redesign, and we'll definitely pay close attention to color contrast and accessibility in that process! 👍

With this in mind and considering how busy we are pushing new exciting projects forward, I think a PR to revisit the color contrasts on the existing website will be hard to justify as a priority. 

That said, a11y is important. Can you make a screenshot of what your implementation would look like with stronger color contrasts?

**Comment by estevanmaito** [comment]
I think that just updating the color palette (to the experimental from TUI), would solve the problem.

This is the result of keeping the color classes (`text-gray-500` and 600), but using the respective TUI values:

![tailwind-a11y](https://user-images.githubusercontent.com/8527573/90847134-34b65c80-e340-11ea-8ba6-f08aadc67f2a.png)

**Comment by adamwathan** [comment]
Will be launching a redesign in the next few months and will make sure to keep this in mind then, thanks.
