### ISSUE TITLE
Logos are filling up the screen when the docs' css is loading

### ISSUE THREAD

**Issue by DCzajkowski** [tailwindlabs/tailwindcss.com#426]
When the CSS stylesheet is loading on a slightly slower Internet connection, the following is visible

<img width="1792" alt="Screen Shot 2020-05-18 at 1 01 52 AM" src="https://user-images.githubusercontent.com/4501047/82162462-08a0c080-98a5-11ea-8218-952d6751c781.png">

I think this causes an unpleasant experience and we should come up with some nifty solution to this problem :)

Currently, the only things I can think of is hiding everything until the CSS is loaded or show a splash screen with just a logo in it. But they are not ideal and I don't have better ideas for now.

**Comment by simonswiss** [comment]
We could give width or height attributes to the logo SVG to prevent it to ever show at this giant size! 😅

**Comment by DCzajkowski** [comment]
Yeah, the thing is all SVGs have this problem. 

Some solutions:
1. To all SVGs add a `max-width` or `max-height` using an inline CSS and override it back to `initial` in the stylesheet. When the stylesheet loads everything would be back to normal.
2. We can hide all SVGs using the strategy from point 1. They aren't that useful when there is no CSS loaded anyway.
3. Use `width` and/or `height` in an inline `style`.

Another thing:

For some reason the main CSS file has no `rel="preload"`, but all the JS on the page has. This causes the CSS to be loaded after the JS, causing the first render to be likely not styled. In my opinion the CSS is more important to the site's proper functioning than the JS, that drives animations (that are broken without CSS anyway) and search (that's maybe more important than CSS, but oh well).

**Comment by adamwathan** [comment]
We've totally rebuilt the site since this was reported and I don't see any of these issues anymore so going to close 👍🏻 If I've made a mistake please don't hesitate to open a new issue, thanks.
