### ISSUE TITLE
Border Color page is using bg instead of border

### ISSUE THREAD

**Issue by bernaferrari** [tailwindlabs/tailwindcss.com#430]
On Border Color, inside "Changing Opacity", I believe it should be either `border-blue-500` or `border border-blue-500` (to be the same way as Usage, on top), but not `bg-blue-500`. https://tailwindcss.com/docs/border-color/#changing-opacity-v1-4-0

![image](https://user-images.githubusercontent.com/351125/82735765-8415ce00-9cfa-11ea-9dcd-bf47d2b832cd.png)

**Comment by luukdv** [comment]
PR: https://github.com/tailwindcss/docs/pull/443

**Comment by simonswiss** [comment]
Thanks for reporting this and for the PR! 👍

Closing this, as it has been merged.

Thanks again!
