### ISSUE TITLE
Tag ie11 incompatible utility classes

### ISSUE THREAD

**Issue by stedekay** [tailwindlabs/tailwindcss.com#431]
I use the new `target: 'ie11'` mode in my tailwind config, but I can't easily find out which utility classes are no longer available for me in the docs.

Is it possible to e.g. tag the incompatible utility classes with a label like "ie11-incompatible" (The name sucks, I just don't come up with a better one right now).

Or is there already a way to find it out via the docs and I just didn't get it?

**Comment by stedekay** [comment]
Yeah, found that PR after a while. Thanks for your answer.
The problem I see is that this list will grow and this is something easy to forget checking when using new utility classes.
But for now I know where to look at. 
I'll leave this ticket open so the maintainers can decide if something has to be done.

**Comment by pqt** [comment]
Hey, a quick and dirty solution to find the differences might be to generate a complete stylesheet with and without the `target: 'ie11'` and then use gist version history.

https://gist.github.com/

If you put your first generate sheet in, then edit and paste in the second version you will get a complete diff generated so you can then at the very least keep it as a reference until a better solution comes about.

I made a quick `example.css` file and then edited the `.container` class to `.container-fluid` to creating a new revision, it gives me a complete diff.

**Example:**
![](https://i.imgur.com/L5ThMmI.png)

If you don't want it squished together in diffs with the container, you can also use the `github-wide` userstyle. (https://github.com/mdo/github-wide#why)

**Comment by pqt** [comment]
@stedekay 

Hey, a quick and dirty solution to find the differences might be to generate a complete stylesheet with and without the `target: 'ie11'` and then use gist version history.

https://gist.github.com/

If you put your first generate sheet in, then edit and paste in the second version you will get a complete diff generated so you can then at the very least keep it as a reference until a better solution comes about.

I made a quick `example.css` file and then edited the `.container` class to `.container-fluid` to creating a new revision, it gives me a complete diff.

**Example:**
![](https://i.imgur.com/L5ThMmI.png)

If you don't want it squished together in diffs with the container, you can also use the `github-wide` userstyle. (https://github.com/mdo/github-wide#why)

**Comment by weyert** [comment]
Yes, it would be great if these differences would get documented, especially, for newly introduces features as a lot of people still sadly need to support IE11

**Comment by simonswiss** [comment]
Hey!

Since we dropped support for IE11 in Tailwind 2, not sure how much effort we can realistically put in this.

I guess this is still relevant for Tailwind v1, but cannot imagine we'll be able to make updating the v1 docs a priority, unfortunately.

**Comment by adamwathan** [comment]
Since Tailwind 2 doesn't support IE11 we have no plans to make changes in this area 👍🏻
