### ISSUE TITLE
Issue in docs/transition-timing-function

### ISSUE THREAD

**Issue by handplant** [tailwindlabs/tailwindcss.com#434]
I was using Tailwind v1.4.6.
The following does not work as described in the documentation.

```
module.exports = {
  theme: {
    extend: {
      transitionTimingFunction: {
+       'ease-in-expo': 'cubic-bezier(0.95, 0.05, 0.795, 0.035)',
+       'ease-out-expo': 'cubic-bezier(0.19, 1, 0.22, 1)',
      }
    }
  }
}
```
This generates the following classes:
.ease-ease-in-expo
.ease-ease-out-expo

It should look like this

```
module.exports = {
  theme: {
    extend: {
      transitionTimingFunction: {
+       'in-expo': 'cubic-bezier(0.95, 0.05, 0.795, 0.035)',
+       'out-expo': 'cubic-bezier(0.19, 1, 0.22, 1)',
      }
    }
  }
}
```

Is that a bug or is that on purpose?

**Comment by simonswiss** [comment]
Closing this as it has been updated in the docs, thanks for flagging it! 👍

![image](https://user-images.githubusercontent.com/485747/90505003-43144500-e195-11ea-9da6-a099eaed7ba7.png)
