### ISSUE TITLE
Divide- examples are failed

### ISSUE THREAD

**Issue by RomainMazB** [tailwindlabs/tailwindcss.com#438]
Hi,
Just to report, in the new `divide-` documentation: 90% of the examples are failed:
![Capture d’écran de 2020-05-31 22-15-38](https://user-images.githubusercontent.com/53976837/83361803-63014d00-a38c-11ea-8d46-e5db7111cbe7.png)

It's simple enough though but I had to report :)

**Comment by nicolaspayot** [comment]
I think it's working fine now: <img width="694" alt="Capture d’écran 2020-08-03 à 09 20 16" src="https://user-images.githubusercontent.com/463319/89156240-9d44c180-d56a-11ea-83a2-34f42ca007d3.png">

**Comment by adamwathan** [comment]
Yeah went ahead and fixed this a while back, thanks!
