### ISSUE TITLE
tailwind.min.css File Size Way Off From What The Documentation Says

### ISSUE THREAD

**Issue by mudgen** [tailwindlabs/tailwindcss.com#456]
The [documentation for Tailwind CSS](https://tailwindcss.com/docs/installation#using-tailwind-via-cdn) says this:

> Note that while the CDN build is large (27kb compressed, 348kb raw), it's not representative of the sizes you see when including Tailwind as part of your build process.

But I measured the current 'https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css' file and here are the numbers I get: 
* 135kb compressed
* 1.36mb raw

**Comment by HonkingGoose** [comment]
This issue can be closed, as it has been fixed by commit https://github.com/tailwindlabs/tailwindcss.com/commit/b868b0b5bcfd4dc4186cd53557ba2048eb4a6248, which computes the file size at build time.
