### ISSUE TITLE
Order Docs Slightly Misleading

### ISSUE THREAD

**Issue by parker-codes** [tailwindlabs/tailwindcss.com#469]
Hey all! I noticed that the Order classes' page has many references to flex items. I just wanted to point out that the `order` property is for grid items as well!

I don't believe an example is needed, but here's [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/order). The top sentence is the highlight of this.

**Comment by adamwathan** [comment]
Updated, thanks.
