### ISSUE TITLE
Blocked cookies cause JavaScript error

### ISSUE THREAD

**Issue by spl** [tailwindlabs/tailwindcss.com#489]
It seems like some recent change produced this problem. I've had the browser open to various pages on `tailwindcss.com` for days, and I first encountered the problem yesterday.

In Chrome, Safari, and Firefox on macOS, when the browser is configured to block all cookies, the page loads initially and then disappears. The console shows repeated, never-ending error reports.

I ran `yarn dev` on `master`, and it also errors, though it doesn't loop infinitely. The error seems to point to something in Next.js, with which I'm unfamiliar. This is the Chrome error message:

```
next-dev.js?53bc:48 Error was not caught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at initializeBuildWatcher (webpack-internal:///./node_modules/next/dist/client/dev/prerender-indicator.js:47:38)
    at eval (webpack-internal:///./node_modules/next/dist/client/next-dev.js:54:37)
```

**Comment by bradlc** [comment]
Thanks for raising this @spl! Should be fixed on the live site now 👍
