### ISSUE TITLE
Missing tbody closing tag 

### ISSUE THREAD

**Issue by tejas456sawant** [tailwindlabs/tailwindcss.com#490]
https://tailwindcss.com/docs/border-collapse 

![image](https://user-images.githubusercontent.com/38217830/90069459-f1406a80-dd0f-11ea-9344-ba60a5b8e485.png)

**Comment by cweise** [comment]
I made a [Pull Request](https://github.com/tailwindlabs/tailwindcss.com/pull/491)

**Comment by simonswiss** [comment]
Thanks for your contribution, @cweise! 👍
