### ISSUE TITLE
Broken links to core plugins page

### ISSUE THREAD

**Issue by tnorthcutt** [tailwindlabs/tailwindcss.com#497]
On the theme page, there are two broken links with the text `core plugin` and `core plugins`:

https://github.com/tailwindlabs/tailwindcss.com/blob/75203438587e8d4b97dc022211d93b44627ab4e9/src/pages/docs/theme.mdx#L49

https://github.com/tailwindlabs/tailwindcss.com/blob/75203438587e8d4b97dc022211d93b44627ab4e9/src/pages/docs/theme.mdx#L369

That docs page (`/core-plugins`) doesn't exist. Not sure what exactly to do to fix this or I'd submit a PR along with this 😅

**Comment by simonswiss** [comment]
Hi @tnorthcutt - thanks for reporting this!

The link path for these 2 links should point to `/docs/configuration#core-plugins` instead of `/docs/core-plugins`, if you want to create a PR 👍

**Comment by tnorthcutt** [comment]
@simonswiss I LOVE that you didn't just say "ok thanks, fixing" but instead encouraged me to PR the change. Bravo for fostering and welcoming contributions ❤️

**Comment by tnorthcutt** [comment]
@simonswiss Also, this Netlify build plugin looks pretty interesting and would maybe catch something like this in the future: https://github.com/Munter/netlify-plugin-checklinks

**Comment by simonswiss** [comment]
@tnorthcutt this makes me happy!

Thanks for sharing the Netlify link - looks interesting. The docs site is hosted on Vercel since the NextJS rebuild, though.

Thanks for the PR, I see Adam merged it on Friday 👍
