### ISSUE TITLE
Add subtitles to TailwindCSS screencasts

### ISSUE THREAD

**Issue by HonkingGoose** [tailwindlabs/tailwindcss.com#514]
## Proposed change:

- Add good quality subtitles to all TailwindCSS screen-casts.

## Benefits:

- The content becomes accessible for those with hearing difficulties.
- Having subtitles means you also have a good transcript, that can be published with the screen-cast, for search-ability, and a quick (and precise!) overview of what the video will cover.
- Subtitles are not just for deaf people! This is also good for people in loud environments, or with bad quality loudspeakers or where they can't disturb others (sleeping people in the same room).
- Subtitles will also help those with [tinnitus](https://en.wikipedia.org/wiki/Tinnitus), or [hyperacusis](https://en.wikipedia.org/wiki/Hyperacusis).
- Subtitles will also help non-native English users understand what was said more easily.
- Goodwill benefits for being inclusive and accessible.

## Drawbacks:

- Creating subtitles yourself is an art and science rolled into one. It's hard to get this right without prior experience with and usage of subtitles. There are lot of gotchas that can catch out well meaning beginners.
- Creating subtitles manually is a large time investment.
- It will cost money to get this done professionally, though not as much as you might think.

## Discussion:

I highly recommend you watch [Making Games Better for the Deaf and Hard of Hearing | Designing for Disability](https://www.youtube.com/watch?v=4NGe4dzlukc) to get a quick overview and explanation on why good subtitles are helpful.

On a personal note: I have severe hearing loss, and use a hearing aid. Many people think that having a hearing aid fixes the disability, but this is not the case at all: I have to really focus on what is being said, and oftentimes guess at what is said. It's really tiring to have to focus on hearing things. I would really really like and benefit from having subtitles on the screen-casts!

## Minutes of video to be subtitled:

There's about 190 minutes of video in the 22 screen-casts published currently.
There are 19 videos planned, lets assume they also average 8.5 minutes runtime. So 19 screen-casts * 8.5 minutes = 161.5 minutes of video. Total runtime to be subtitled: 190 + 161.5 = 351.5, but lets round up to 352 minutes.

## Time investment estimate to do this manually:

Let's make a rough estimate. I would guess that subtitling one 10 minute Tailwind screencast would take me about an hour, because Tailwind uses a lot of technical terms like classnames, web dev jargon, etc.

352 minutes / 10 minutes of subtitles per hour of work = 35,2 hours work.

## Cost estimate of getting this done professionally:

It will cost about $1,25 per minute of video, to get good quality subtitles by a professional (like rev.com) that you can then plug into your Vimeo videos.

352 minutes * 1.25 dollars = 440 dollars. Let's round up to 450 dollars, and add some margin of safety (25%) because this is back of the envelope stuff. 450 * 1.25 = 562.50 dollars for the lot.

There's also a time investment to plug the subtitles into the video, I would estimate this to be between 1 and 3 hours to get this done after receiving the subtitles.

## References:

Read the [BBC subtitle guidelines](https://bbc.github.io/subtitle-guidelines/) to learn what it takes to make good subtitles.
[Rev blog post on adding subtitles on Vimeo](https://www.rev.com/blog/resources/how-to-add-closed-captions-or-subtitles-on-vimeo)
[Vimeo Zendesk support page on Captions and Subtitles](https://vimeo.zendesk.com/hc/en-us/articles/224968828-Captions-and-subtitles)
[Pricing information for professional subtitles from rev.com](https://www.rev.com/caption)

**Comment by adamwathan** [comment]
Hey! For now I would recommend watching the YouTube-hosted version if you need subtitles:

https://www.youtube.com/playlist?list=PL7CcGwsqRpSM3w9BT_21tUU8JN2SnyckR

They aren't perfect but they aren't bad either. I am planning to re-record the screencasts in a month or two when Tailwind 2.0 is released and will definitely consider investing in adding professional subtitles at that time.

**Comment by HonkingGoose** [comment]
Hi @adamwathan,

Thanks for responding.

I didn't realize the screen-casts are on YouTube as well. Unfortunately the automatic YouTube captioning is still not very good, especially with technical content such as yours. There still is no replacement for proper human created and audited subtitles. Also YouTube is removing the ability for others to add subtitles, so now it's all on the creators shoulders to add them.

> I am planning to re-record the screencasts in a month or two when Tailwind 2.0 is released and will definitely consider investing in adding professional subtitles at that time.

Thanks for considering investing in professional subtitles! :smile: :tada: 

Greetings,

HonkingGoose
