### ISSUE TITLE
:focus-visible support

### ISSUE THREAD

**Issue by mustafawm** [tailwindlabs/tailwindcss.com#518]
Hello,

I just saw [this retweet](https://twitter.com/rob_dodson/status/1301264088526331904) saying Chrome supports `:focus-visible` now!

And, for some reason, [MDN](https://twitter.com/rob_dodson/status/1301264088526331904) says it's been supported by Firefox, Edge, Chrome, and Opera for a while now!

Should we update the [focus-visible section](https://tailwindcss.com/docs/pseudo-class-variants#focus-visible) to reflect what MDN (or that tweet) says?

Does that mean i will it be supported (for those browsers) without the need for the polyfill?

**Comment by simonswiss** [comment]
The [caniuse](https://caniuse.com/?search=focus-visible) chart still has plenty of red in it, but it's nice to see Chrome joining the "green" team :)

Would you be keen to open a PR that updates the docs to mention Chrome alongside Firefox for the browsers that support this feature? I'll leave this open for a couple of days in case you want to, and do the change myself if not 👍

**Comment by mustafawm** [comment]
I added that [caniuse link](https://caniuse.com/?search=focus-visible) in case more browsers support so that reader will notify the team

**Comment by simonswiss** [comment]
Thank you! Merged 🎉
