### ISSUE TITLE
enhancement: Purge unused `@keyframes`

### ISSUE THREAD

**Issue by neupauer** [tailwindlabs/tailwindcss.com#519]
Hello,

the `purge` configuration option (PurgeCSS) do not remove unused animation `@keyframes` e.g. `@keyframes ping`, `@keyframes spin`... by default, even in `mode: "all"`. So I think it would be nice if it worked out-of-the-box or just mention it in the documentation.

**The solution is very simple**, but for those who do not know PurgeCSS very well, it can be helpful
```
purge: {
    mode: "all",
    content: ["./src/**/*.html"],
    options: {
        keyframes: true,
    },
},
```

**Comment by simonswiss** [comment]
Hey @neupauer 👋

Thanks for mentioning this - that indeed seems like a low hanging fruit. 

Checking with @adamwathan whether we want to make a note of this in the documentation, or change the default settings to purge keyframes as well.

**Comment by adamwathan** [comment]
Added a section to the docs explaining how to do this 👍🏻
