### ISSUE TITLE
Text and bg opacity caveat needs to be specified

### ISSUE THREAD

**Issue by jshimkoski** [tailwindlabs/tailwindcss.com#525]
https://tailwindcss.com/docs/customizing-colors#naming-your-colors

In that section, it says: "You could even define these colors using CSS custom properties (variables) to make it easy to switch themes on the client".

This is misleading as doing so will break text-opacity and bg-opacity rules. I believe the documentation needs to be updated to address this caveat.

**Comment by simonswiss** [comment]
Fair point @jshimkoski 👍

Would you like to have a stab at updating the docs with a PR that covers this caveat?

**Comment by jshimkoski** [comment]
Sure thing.

**Comment by sibbngheid** [comment]
Also good to note Adam's tweet about this topic: https://twitter.com/adamwathan/status/1305235704960688128

**Comment by adamwathan** [comment]
I've updated the docs with a link to the example repository showing how to set this up:

https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo

Thanks!
