### ISSUE TITLE
Link needs updating

### ISSUE THREAD

**Issue by dgwyer** [tailwindlabs/tailwindcss.com#532]
The following link in Using, Sass, Less, or Stylus needs to be updated: https://tailwindcss.com/docs/using-with-preprocessors#using-postcss-as-your-preprocessor

It should be: https://tailwindcss.com/docs/using-with-preprocessors#using-post-css-as-your-preprocessor

**Comment by simonswiss** [comment]
If you want to make a pull request with this change, I'll merge it and you'll become a `contributor` 🌟 

If you don't want, I will do the changes myself, but I thought it's always nice to _give credit_ to people helping out making the Tailwind CSS ecosystem better 👍

**Comment by dgwyer** [comment]
Thanks I'll see if I can do a PR soon.

**Comment by simonswiss** [comment]
Hey! 👋

No problem, happy to help you out! 👍

You are correct - this is a bit confusing. Since the rebuild to NextJS, the `docs` folder is now in `src/pages/docs`. Will update!

And yes, `npm i` will install your dependencies, and `npm run dev` will start your dev process.

**Comment by simonswiss** [comment]
Hey @dgwyer,

Do you need any more help with that? If you don't have time, I am happy to do the change myself.

Basically, all you need to do is update the link in `src/pages/docs/using-with-preprocessors.mdx`.

**Comment by dgwyer** [comment]
Thanks Simon. Just taking a look now.
