### ISSUE TITLE
Auto scroll left navigation to the selected menu section

### ISSUE THREAD

**Issue by ivosabev** [tailwindlabs/tailwindcss.com#536]
Use case:

I use the top search bar and type "border".

I select "Border Style"

What I get is the Border Style page with the left navigation staying at the top.
<img width="983" alt="Screen Shot 2020-09-17 at 4 32 09 PM" src="https://user-images.githubusercontent.com/103370/93477377-9e0b9a00-f903-11ea-9b8f-b163758b073f.png">

What I would like to get is the Border Style page with the left navigation auto scrolled to the appropriate menu section
<img width="987" alt="Screen Shot 2020-09-17 at 4 32 17 PM" src="https://user-images.githubusercontent.com/103370/93477464-b7144b00-f903-11ea-85ae-b64a87d98017.png">

The rationale is that you often have to look an additional related property. Examples would be grid, flex, border related things, etc.

It's a small improvement, but really annoying.

**Comment by simonswiss** [comment]
Hey!

We actually were in the process of fixing it - will check on the status for this. For now, I will consolidate this discussion with https://github.com/tailwindlabs/tailwindcss.com/issues/353 👍
