### ISSUE TITLE
Firefox Send link is no longer valid

### ISSUE THREAD

**Issue by benperiton** [tailwindlabs/tailwindcss.com#537]
On the installation page at the bottom it mentions that Firefox Send is built with Tailwind, but that page is no longer working as it has been discontinued.

"Sites that follow our best practices are almost always under 10kb compressed. For example, Firefox Send is built with Tailwind and their CSS is under 4kb compressed and minified."

https://support.mozilla.org/en-US/kb/what-happened-firefox-send

Not sure of another prominent site to use in its place, hence no PR.

**Comment by simonswiss** [comment]
Hey @benperiton - thanks for reporting this!

Not sure either what we could _replace_ this with, although there are plenty of good examples of prominent websites using Tailwind CSS out there.

In the meantime, do you want to open a PR that removes the last sentence (starting with `For example,`)?

I can do it, but I try to actively encourage community contributions, particularly where folks took the time to report an issue with a suggestion to fix it 👍

**Comment by simonswiss** [comment]
Thank you! Merged 🎉
