### ISSUE TITLE
Invalid Webpack Loader Configuration Example

### ISSUE THREAD

**Issue by ethanae** [tailwindlabs/tailwindcss.com#540]
The Webpack loader build tool example shows an invalid Webpack loader schema for postcss-loader. The tailwindcss documentation for Webpack is as follows:

```javascript
// webpack.config.js
module.exports = {
  // ...
  module: {
    rules: [
      {
        // ...
        use: [
          // ...
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
              plugins: [
                require('tailwindcss'),
                require('autoprefixer'),
              ],
            },
          },
        ],
      }
    ],
  }
}
```

The above produces the following Webpack error:
```
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }
```

The postcss-loader options should be under the `postcssOptions` key, as below: 

```javascript
{
  loader: 'postcss-loader',
  options: {
    postcssOptions: {
      ident: 'postcss',
      plugins: [
        require('tailwindcss'),
        require('autoprefixer')
      ],
    },
  }
}
```

**Comment by simonswiss** [comment]
Good catch @ethanae! Looks like version 4.0 of `postcss-loader` released 20 days ago brought some breaking changes that warrant our documentation to be updated.

Would you like to convert this into a pull request? I am happy to make the update myself, but it's always nice to welcome community contributions 👍

**Comment by ethanae** [comment]
Thanks @simonswiss! I'm happy to make a PR for this :+1:

**Comment by ethanae** [comment]
@simonswiss , I just made a PR:

https://github.com/tailwindlabs/tailwindcss.com/pull/543

**Comment by simonswiss** [comment]
Thank you! Merged 🎉
