### ISSUE TITLE
Z-Index page is missing info

### ISSUE THREAD

**Issue by IzMichael** [tailwindlabs/tailwindcss.com#544]
The Z-Index page doesn't mention that it requires the `absolute` class, along with the z-index class.

**Comment by simonswiss** [comment]
Hey @IzMichael, thanks for this suggestion!

In the examples, we don't always show all the classes that make the example - but rather try to only show what's relevant to what it demonstrates.

For example here, we don't show the `absolute` class, and neither do we show the `h-24 w-24` classes. We only show the z-index classes, and the margin/background color classes for context.

If we were to add the `absolute` classes, we should then also probably add a wrapper which has the `relative` class, etc.

Does it make sense?

**Comment by IzMichael** [comment]
It may just be me, but that doesn't make sense. The absolute class is required to have elements overlay. Can you explain further?

**Comment by IzMichael** [comment]
It may just be me, but that doesn't make sense. The absolute class is required, to have elements overlap. Can you (@simonswiss) explain further?

**Comment by simonswiss** [comment]
Hey!

Sure thing, will try to explain my train of thoughts 👍

For this particular example, a stack of squares overlapping each other and progressively offset from the top left, yes, you'll need to use an `absolute` position on each square, and a `relative` position on the parent that contains them.

But `z-index` **doesn't require** the `absolute` class in all situations.

For example, take 3 squares in a flex container, which overlap each other via negative margins:

```html
<div class="flex -space-x-8">
  <div class="w-20 h-20 shadow-sm bg-blue-400 rounded-md"></div>
  <div class="w-20 h-20 shadow-sm bg-pink-400 rounded-md"></div>
  <div class="w-20 h-20 shadow-sm bg-teal-400 rounded-md"></div>
</div>
```

![image](https://user-images.githubusercontent.com/485747/94776067-5a855580-0404-11eb-8c83-97dcb01a6f6e.png)

In this scenario, adding a `z-10` to the middle, pink square will make it sit over the other two squares:

```html
<div class="flex py-4 -space-x-8">
  <div class="w-20 h-20 shadow-sm bg-blue-400 rounded-md"></div>
  <div class="z-10 w-20 h-20 shadow-sm bg-pink-400 rounded-md"></div>
  <div class="w-20 h-20 shadow-sm bg-teal-400 rounded-md"></div>
</div>
```

![image](https://user-images.githubusercontent.com/485747/94776142-8274b900-0404-11eb-83a4-d5bba4b19283.png)

If the `absolute` class was a requirement in all cases for `z-index` classes to work (like the `transform` utility is a requirement for any  transform utilities to work), then it would definitely make sense to add it in all `z-index` examples.

The intent in these documentation examples is not to recreate the demo example, but try and isolate the code snippet to show the most relevant classes (in this context: the color of squares, and position offset with margins).

There is nothing fundamentally wrong with adding the `absolute` class to all these stack of squares examples, but then we'd probably want to add the wrapper container with the `relative` class, and it adds some noise to the code examples.

Hopefully that makes more sense now. 

If not, that's okay too - this is just my view on the current state of docs, and anything is up for discussion 👍

**Comment by IzMichael** [comment]
Hi, I understand what you're saying now, thanks! 👍🏻 

I had an idea for a solution, a note below the image. E.G:
![image](https://user-images.githubusercontent.com/57115702/94783225-e01afc80-0428-11eb-8f31-7f50bafe417f.png), (Just a rough idea)

Thoughts?

**Comment by IzMichael** [comment]
Hi, I understand what you're saying now, thanks! 👍🏻 

I had an idea for a solution, a note below the image. E.G:
![image](https://user-images.githubusercontent.com/57115702/94783225-e01afc80-0428-11eb-8f31-7f50bafe417f.png) (Just a rough idea)

Thoughts @simonswiss?

**Comment by simonswiss** [comment]
Hey, 

Again, my view on this is while this can be useful to someone who wants to recreate this particular example, the core mission of this documentation is to isolate focus on `z-index` here, not a particular layout implementation.

That note is sure helpful, but I also think it somewhat is _out of scope_.

**Comment by adamwathan** [comment]
Hey! Appreciate the suggestion but no plans to change this for the reasons Simon mentioned. Thanks!
