### ISSUE TITLE
Feature request: Add Custom Forms plugin to the "Official Plugins" section

### ISSUE THREAD

**Issue by daannijkamp** [tailwindlabs/tailwindcss.com#568]
The Tailwind CSS Custom Forms plugin is very useful. But is not mentioned on the website in the "Official Plugins" section.
Feature request: Add Custom Forms plugin to the "Official Plugins" section

**Comment by simonswiss** [comment]
This has changed in Tailwind 2.0 - there is a new plugin called `@tailwindcss/forms`, but this suggestion still stands 👍

**Comment by adamwathan** [comment]
Updated the sidebar with links to all official plugins 👍🏻 Eventually I'd like to make a little page for them so it shows up in the search but in the 5 minutes I have right now I can't think of a sensible place to put it.
