### ISSUE TITLE
Using Tailwind with Parcel Documentation

### ISSUE THREAD

**Issue by Kalaschnik** [tailwindlabs/tailwindcss.com#571]
There is a variety of different _How to Use Tailwind in Parcel_ on the web, and as there is no official documentation of how to do it, I would like to hear from others whats the recommended setup is.

Key takeaways I observed/experienced:
- some users install Tailwind as `dependency` while others install it as `devDependency`, what’s the “correct” way?
- Tailwind prefers `.postcssrc.json`, which is required to use Tailwind’s cache(?)
- I can name my main style file either `css` or `pcss`, and Parcel seems to be fine with both

Right now my config looks like this:
**`.postcssrc.json`**
```json
{
  "plugins": ["tailwindcss"]
}
```
**`package.json` (excerpt)**
```json
"scripts": {
  "dev": "parcel serve ./src/index.html",
  "build": "parcel build ./src/index.html --public-url='./'"
},
"dependencies": {
  "tailwindcss": "^1.9.5"
},
"devDependencies": {
  "parcel": "^2.0.0-beta.1",
  "postcss-modules": "^3.2.2"
}
```

I would love to hear your advice how you setup Parcel & Tailwind!
Thanks!

**Comment by adamwathan** [comment]
@simonswiss This would be a good one to write an integration guide for 👍🏻

**Comment by adamwathan** [comment]
I've captured this in our internal integration guides roadmap so going to close 👍🏻 Will put this together and publish it next time we work on that project (probably late February).
