### ISSUE TITLE
Update purgeCSS docs to use `safelist`

### ISSUE THREAD

**Issue by robhudson** [tailwindlabs/tailwindcss.com#572]
With the recent [upgrade](https://github.com/tailwindlabs/tailwindcss/commit/8e4e0a0eb8dcbf84347c7562988b4f9afd344081#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) to purgeCSS 3.x, the option `whitelist` has now become `safelist`.

The docs should be updated to reference this option and use the correct URL: https://purgecss.com/safelisting.html

**Comment by adamwathan** [comment]
Right now the docs are still correct since we haven't published a version of Tailwind that uses PurgeCSS 3 but we'll definitely update this as soon as we release Tailwind 2.0 👍🏻

**Comment by bradlc** [comment]
Hey @robhudson, it looks like this was addressed in the recent docs update 👍 https://tailwindcss.com/docs/optimizing-for-production#purge-css-options
