### ISSUE TITLE
Add tailwind.ink as a tool for generating custom palettes in the docs (customizing-colors)

### ISSUE THREAD

**Issue by cybervaldez** [tailwindlabs/tailwindcss.com#574]
In the docs, [Generating Custom Color Palettes](https://tailwindcss.com/docs/customizing-colors#generating-custom-color-palettes):

> A common question we get is "how do I generate the 100–900 shades of my own custom colors?".
> 
> Bad news: color is complicated and we've yet to find a tool that does a good job generating these sorts of color palettes. We picked all of Tailwind's default colors by hand, balancing them by eye. Sorry!

I recently stumbled on to [tailwind.ink](https://tailwind.ink) and I believe it qualifies as a great tool for the job!

**Comment by adamwathan** [comment]
Hey! We don't have a dedicated area for community resources currently so going to close this. Would instead recommend adding it here:

https://github.com/aniftyco/awesome-tailwindcss
