### ISSUE TITLE
Docs: Conflicting Advice About Purging

### ISSUE THREAD

**Issue by bdkjones** [tailwindlabs/tailwindcss.com#578]
Relevant page: https://tailwindcss.com/docs/controlling-file-size#purging-specific-layers

In the layers section, this appears:

    By default, Tailwind will purge styles in all of the base, components, 
    and utilities layers. If you'd like to change this, use the layers option:

Farther down the page, in the "Setting Up PurgeCSS manually" section, this appears:

    Finally, we recommend only applying PurgeCSS to Tailwind's utility classes, 
    and not to base styles or component classes.

Which one of these approaches is the correct one?

**Comment by adamwathan** [comment]
As a @bdkjones super fan you have caught me with my pants down and I am embarrassed. I would purge all layers these days, the risk before has been mitigated with the new `preserveHtmlElements` option which is enabled by default 👍🏻 

We're releasing v2.0 in about two weeks btw, not drastically different in any way really but since I know you're right in the middle of this stuff I will make sure to get you a draft of the upgrade guide by the end of the week in case it's helpful for you.

**Comment by adamwathan** [comment]
Actually re-reading all of this, there isn't actually any conflict — I still recommend only purging utilities to be safe if you are setting up PurgeCSS completely manually/externally. If you use our integrated PurgeCSS feature though we can safely purge all layers.

**Comment by bdkjones** [comment]
Ok, great. I got into this because running Tailwind without specifying any special purge configuration in `tailwind.config.js` produced a warning telling me that I should be using layers instead of the "old conservative approach". So I had to add my own config options for purge to get rid of that warning.

**Comment by adamwathan** [comment]
Ah yeah, we _just_ changed some stuff related to that and that messaging could be improved :/ Thanks for the feedback!

**Comment by adamwathan** [comment]
Here are the notes from the release that made this more confusing, I forgot about that purge warning when I did this:

https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.9.3

Basically there’s a “purgeLayersByDefault” flag we were telling people to opt in to that made sense alongside the warning you’re seeing, but for the reasons mentioned in those notes I decided to stop showing those warnings. I think I need to point to the “upcoming changes” docs in that warning you’re seeing which is the part that feels unclear now I think.

**Comment by bdkjones** [comment]
@adamwathan Ha, no worries. I tend to be the guy who exercises all the weird edge cases in all the tooling I touch.

**Comment by simonswiss** [comment]
Hey 👋

I feel like this issue can be closed now that Tailwind 2.0 is out, but please feel free to re-open if you see otherwise 👍
