### ISSUE TITLE
Add horizontal scrollbar in code snippets (example code in the doc)

### ISSUE THREAD

**Issue by abijithpradeep** [tailwindlabs/tailwindcss.com#582]
Some of the code snippets given in the doc are too long (horizontally) to be contained within their div tag (on laptop screen size - 15.6 inch)

[example1-hover section](https://tailwindcss.com/docs/gradient-color-stops#hover)
[example2-focus section](https://tailwindcss.com/docs/gradient-color-stops#focus)

**Screenshot of the 'Gradient Color Stops - Focus' section in the doc**   

![withoutScrollbar](https://user-images.githubusercontent.com/22325449/98319507-e9d6e780-2006-11eb-857c-a3f9fdd2986f.png)

<hr>

Since there is no scrollbar for the code snippet, a major part of the code is not visible.

<hr>

**Screenshot of the 'Gradient Color Stops - Focus' section in the doc after adding a horizontal scrollbar**   

![withScrollbar](https://user-images.githubusercontent.com/22325449/98320190-6f0ecc00-2008-11eb-97d2-c461dad01a5a.png)

<hr>

Providing a horizontal scrollbar with `overflow-x-auto` could solve this issue.

**Comment by simonswiss** [comment]
Hey!

Arguably not the right UX choice, but we've decided to hide the scrollbar on those code examples. They are still all scrollable 👍
