### ISSUE TITLE
Pseudo-class variants combined with responsive prefixes are not working

### ISSUE THREAD

**Issue by JavierMartinz** [tailwindlabs/tailwindcss.com#583]
I was trying to combine responsive prefixes with pseudo-class variants and I couldn't make it work. I thought I was doing something wrong, as I checked the documentation section and it looks like it's working there. However, I used the Developer Tools and I can see that the responsive prefixes are not in the HTML, so that's why it's "working" in the documentation.

If I didn't misunderstand anything, there are two bugs:
- Tailwind responsive prefixes not working if combined with pseudo-classes
- Documentation is missing the responsive prefixes

![Screenshot 2020-11-06 at 13 19 09](https://user-images.githubusercontent.com/1155507/98365771-2e787800-2033-11eb-81e5-3554cfa3c6dc.png)

**Comment by simonswiss** [comment]
Hey!

Nice catch on the example 👍 

We've now completely removed the responsive code samples on the new website.

Those "chaining" of responsive breakpoint + pseudo class variant do actually work:

```
<button class="px-4 py-2 rounded text-white font-semibold bg-pink-400 hover:bg-pink-500 sm:bg-green-500 sm:hover:bg-green-600">Click me</button>
```

will be `pink-400` (`pink-500` on hover) on mobile, and `green-400` (`green-500` on hover) from the `sm` breakpoint and up.

Be sure to put the responsive prefixt **before** the pseudo-class variant.

Here's a Tailwind Play example: https://play.tailwindcss.com/PTW3n3e4s5

**Comment by JavierMartinz** [comment]
Awesome, thanks Simon!
