### ISSUE TITLE
doc bug at adding-base-styles

### ISSUE THREAD

**Issue by xxholly32** [tailwindlabs/tailwindcss.com#585]
There is duplication of content `@font-face`

https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/adding-base-styles.mdx#font-face-rules

**Comment by bradlc** [comment]
Hey @xxholly32. Looks like this was resolved in the recent docs update. Feel free to open a new issue if I've missed something, thanks!
