### ISSUE TITLE
"PostCSS 7 compatibility build" Anchor does not work

### ISSUE THREAD

**Issue by patriksimms** [tailwindlabs/tailwindcss.com#587]
Hey, 

I just noticed that on the https://tailwindcss.com/docs/installation page, the Anchors to the "PostCSS 7 compatibility build" in the sections

Building your CSS
Install Tailwind via npm

do not work. It seems the anchors in the sections are

postcss-7-compatibility-build

where it should be 

post-css-7-compatibility-build

By the way, great work with v2.0 :)

**Comment by nickturrietta** [comment]
Ran into the same problem.

Took me a while to debug the "compatibility build" thing.

Depending on how many others experience this error, it may be worth adding this verbatim code block/notification `Error: PostCSS plugin tailwindcss requires PostCSS 8.` to the top of the [upgrade guide](https://tailwindcss.com/docs/upgrading-to-v2).

Echoing @patriksimms, thanks a million Adam and Tailwind team!

**Comment by spyridonas** [comment]
I fixed it on pr #593 !
