### ISSUE TITLE
README.md build steps outdated

### ISSUE THREAD

**Issue by d4g0** [tailwindlabs/tailwindcss.com#590]
Well there is no docs/ folder any more, this is a little one.  Congrats,  amaizing work with the new site.

**Comment by Mckenney17** [comment]
Clone the repo, In folder, **Right Click -> Open Bash here**, `mkdir docs`, `cd docs`, `yarn`, when the process is done, `yarn dev`

**Comment by Mckenney17** [comment]
![Screenshot 2020-11-19 102036](https://user-images.githubusercontent.com/37163297/99646647-06d0d900-2a51-11eb-9d31-8446b3196b4f.jpg)

That's it working on localhost:3000

**Comment by juukee** [comment]
but yarn build doesn't work。

**Comment by Mckenney17** [comment]
Download and Install yarn
Go into the folder **tailwindcss.com**
In the directory, run command `yarn`
After process is done
run command `yarn dev`

The ReadMe.md didn't specify a yarn build command

**Comment by juukee** [comment]
> Download and Install yarn
> Go into the folder **tailwindcss.com**
> In the directory, run command `yarn`
> After process is done
> run command `yarn dev`
> 
> The ReadMe.md didn't specify a yarn build command 

so if I need build or export files，`yarn build`  will catch a unknown error.

**Comment by d4g0** [comment]
I will recommend anyone that look closely a the package.json  since the real process to deploy it's there, just follow the steps there and you will be ok. At the end of the day, the docs website it's deployed just like that.

**Comment by juukee** [comment]
Thanks，Maybe my deployment method or way is different, I need run `yarn export` to compile to static file, and `yarn dev` can run in the local project,but i need export as static flie when i deploy it.
