### ISSUE TITLE
Upgrade Guide should document the font-weight changes from v1 to v2

### ISSUE THREAD

**Issue by msheakoski** [tailwindlabs/tailwindcss.com#604]
The new v2 release is awesome! Thank you for sharing such a wonderful framework with the world!

While performing the upgrade and removing the "future standardFontWeights" flag from my config, I noticed that the new font weights were not documented in the Upgrade Guide. This may catch some people off guard.

v1 font weights: https://v1.tailwindcss.com/docs/font-weight
v2 font weights: https://tailwindcss.com/docs/font-weight

**Comment by simonswiss** [comment]
Ah yep - this one fell through the cracks!

Thanks for pointing that out, we'll add this to the upgrade guide 👍
