### ISSUE TITLE
Landing page: Testimonial cards spawn without animation

### ISSUE THREAD

**Issue by claudiodekker** [tailwindlabs/tailwindcss.com#605]
On the landing page, the testimonial cards just 'pop in' at the end of the chain without an animation, which feels out-of-place given that the rest of the website nicely animated.

Example (taken less than 100ms apart):
![Screenshot 2020-11-19 at 18 45 51](https://user-images.githubusercontent.com/1752195/99703540-841f3c80-2a97-11eb-852f-c2579ac32299.png)
![Screenshot 2020-11-19 at 18 45 52](https://user-images.githubusercontent.com/1752195/99703552-87b2c380-2a97-11eb-8050-7e66bcc09212.png)

Congrats on the launch, by the way! The website looks amazing!

**Comment by simonswiss** [comment]
Hey!

Thanks for that. We'll probably revisit the animations at some point - I have also noticed that the tweets scroll very slowly on mobile (at least on Android + Chrome). The site was put together in record times by Brad, and there are likely a few things to polish.

Took good note of this, thanks for the detailed explanation + screenshots 👍

**Comment by adamwathan** [comment]
Going to close this as no real concrete plans to change it but would happily review a PR. Use a smaller monitor @claudiodekker jeez 😅
