### ISSUE TITLE
Remove .bg-code-highlight class from setting-up-purge-css-manually site

### ISSUE THREAD

**Issue by regenrek** [tailwindlabs/tailwindcss.com#606]
Hi,

don't think this was intentional:

![image](https://user-images.githubusercontent.com/5182020/99707299-8b951480-2a9c-11eb-9ada-500fddc75f22.png)

https://tailwindcss.com/docs/optimizing-for-production#setting-up-purge-css-manually

**Comment by bradlc** [comment]
Hey @regenrek. This is intentional, to represent the individual strings that PurgeCSS extracts from the content.
