### ISSUE TITLE
tailwindcss.com: "An unexpected error has occurred" on safari (mac and ios)

### ISSUE THREAD

**Issue by DamienFF** [tailwindlabs/tailwindcss.com#610]
Hi,
The new website tailwindcss.com results in a unexcepted error in Safari both on my mac and iPhone.
The website appears and disappears in less than a second.
Safari mac: 12.1.1
IOS version: 13.3

**Comment by r6203** [comment]
Same problem here on mobile (iOS). On desktop the site works fine.

**Comment by bradlc** [comment]
Thanks for the report! Pretty sure we have fixed this now by adding some polyfills. All looks good on iOS 12.1 and Safari 12.0 for Mac 👍
