### ISSUE TITLE
Space Between is out of order

### ISSUE THREAD

**Issue by bernaferrari** [tailwindlabs/tailwindcss.com#611]
It goes from space-y-0 to space-y-1... until space-y-96, then space-y-0.5, space-y-1.5.. It doesn't make sense. Same happens in space-x.
https://tailwindcss.com/docs/space#class-reference

![image](https://user-images.githubusercontent.com/351125/99763209-0da32e80-2ad9-11eb-8470-0f94f5fb1e91.png)

**Comment by bradlc** [comment]
Good catch, thanks! This has been fixed 🙌
