### ISSUE TITLE
Homepage example `shadow-offset-lime` not found

### ISSUE THREAD

**Issue by jlarmstrongiv** [tailwindlabs/tailwindcss.com#613]
![image](https://user-images.githubusercontent.com/20903247/99868057-2240fe80-2b8d-11eb-8d66-5c7241f87d40.png)
On the homepage, there is this cool shadow offset.  But I can’t find anything about it in the docs under box shadows, borders, or rings.  

Is the `shadow-offset-lime` part of the tailwind spec or is it custom?  If it’s custom, how could I go about making it?

**Comment by tance77** [comment]
Lime is not a default color. You would have to enable it in the config file.

```
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    colors: {
      lime: colors.lime,
    }
  }
}
```

**Comment by jlarmstrongiv** [comment]
Thanks!  Yep, lime is included in the 2.0 [extended color palette](https://tailwindcss.com/docs/customizing-colors#color-palette-reference).  

I’m especially interested in the `shadow-offset-[color]` utility.  Now that I look at it, there’s also the `shadow-offset-black` for the buttons, too.  You’re right—it definitely looks like an offset bg-color.  

I’m looking at the tailwindcss [config](https://github.com/tailwindlabs/tailwindcss.com/blob/e88dcdc02ea080e48fbd05272ca187916b725956/tailwind.config.js), but I can’t seem to find any reference to something like `shadow-offset-[color]`.  Plus, examining the css in the actual page, the class doesn’t seem to exist.  Here’s the code for the offset black button:
```html
<div class="relative">
  <div class="absolute bg-black top-0.5 -right-0.5 -bottom-0.5 left-0.5" style="transform-origin: 50% 50% 0px; border-radius: 0%;">
  </div>
  <div class="relative text-sm border cursor-pointer" style="height: 38px; background-color: rgb(190, 242, 100); border-color: rgb(0, 0, 0); transform-origin: 50% 50% 0px; border-radius: 0%;">
    <span class="absolute inset-0 flex items-center justify-center text-white font-medium" style="opacity: 0;">
    <span style="transform-origin: 100% 100% 0px;">Buy now</span>
    </span>
    <span class="absolute inset-0 flex items-center justify-center text-white Poppins-SemiBold_font__2w4Tf" style="opacity: 0;">
    <span style="transform-origin: 50% 100% 0px;">Buy now</span>
    </span>
    <span class="absolute inset-0 flex items-center justify-center text-white font-semibold tracking-wide uppercase" style="opacity: 0;">
    <span style="transform-origin: 0% 100% 0px;">
    Buy now
    </span>
    </span><span class="absolute inset-0 flex items-center justify-center text-black tracking-wide uppercase RobotoMono-Bold_font__226og" style="opacity: 1;"><span style="transform-origin: 50% 100% 0px;">Buy now</span></span>
  </div>
</div>
```
@tance77 can you find any trace of that class?  Or do you think it’s a sleight of hand, and building something like that in reality would require another element with absolute positioning?

**Comment by adamwathan** [comment]
Hey! We sort of faked this for the demo for reasons related to the animation stuff but you would add it yourself in your `tailwind.config.js` file, something like this:

https://play.tailwindcss.com/eb8qRCZyCa?file=config

```js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    extend: {
      boxShadow: {
        'offset-black': '2px 2px black'
      }
    },
  },
  variants: {},
  plugins: [],
}
```

**Comment by jlarmstrongiv** [comment]
Ahh alrighty.  I’ve been following tailwindcss, and was curious about that syntax I hadn’t read about in the release notes.  Even if it’s custom, it’s cool to see it all in action.  Thank you! 😄
