### ISSUE TITLE
Some color palette hexes are slightly off

### ISSUE THREAD

**Issue by sklawren** [tailwindlabs/tailwindcss.com#627]
I noticed that some of the colors in the palette have slightly mismatched hex values from what is actually rendered on the docs page and in tailwind itself.

https://tailwindcss.com/docs/customizing-colors#color-palette-reference

I'm using OSX Catalina on a 2020 MacBook Pro 16", Google Chrome, and an OSX utility called Color Slurp. I'm not sure where the discrepancy is coming from, but these are the hex values I am getting.

I'm not sure whether the color being rendered is incorrect or whether the hex value in the documentation is incorrect. I'll leave it to you to decide whether to update the color that is rendered to match what is in the docs or update the hex value in the docs to match what is rendered.

I did an audit on the entire palette in the docs and started to list where the documented hex value is different than what is rendered, but there are so many that are slightly off that I stopped at lime. I see many others which are off by a little after lime, but I'll leave it to you to do an audit on the rest.

Here are the eye-dropped values which do not match the documented hex value beneath them:
- blueGray-400: `#95A3B8`
- blueGray-600: `#485569`
- blueGray-800: `#1E293C`
- blueGray-900: `#10172A`
- warmGray-300: `#D5D3D1`
- warmGray-400: `#A8A29D`
- warmGray-600: `#57534F`
- warmGray-900: `#1B1917`
- red-200: `#FDE2E1`
- red-500: `#F04444`
- red-600: `#DC2625`
- red-700: `#BA1C1B`
- red-800: `#981C1B`
- orange-200: `#FED6AA`
- orange-300: `#FEBA74`
- orange-400: `#FC923C`
- orange-500: `#F97315`
- orange-600: `#EA580B`
- orange-700: `#C2400B`
- orange-800: `#993512`
- amber-50: `#FEFBEB`
- amber-100: `#FEF2C7`
- amber-300: `#FCD44C`
- amber-400: `#FCBF24`
- amber-500: `#F69E0B`
- amber-600: `#D97707`
- amber-700: `#B5530A`
- amber-800: `#92400D`
- amber-900: `#78360F`
- yellow-200: `#FFF089`
- yellow-400: `#FBCC14`
- yellow-500: `#EBB304`
- yellow-600: `#CB8A03`
- yellow-700: `#A06207`
- yellow-800: `#844D0F`
- yellow-900: `#713E12`
- lime-50: `#F6FFE7`
- lime-100: `#ECFBCB`

There are more in lime and after which do not match.

**Comment by bradlc** [comment]
Hey @sklawren. The colors are correct, but color pickers give different results for some reason. I'm not a color expert so I don't know the reason behind that but for example the [Contrast](https://usecontrast.com/) app says that `blueGray.400` is `#8392aa`. Here's the CSS for the `blueGray.400` block:

![image](https://user-images.githubusercontent.com/2615508/100344482-ca652600-2fd8-11eb-8f6f-36938d0e31b7.png)
