### ISSUE TITLE
Align Content only works with flex-wrap

### ISSUE THREAD

**Issue by mseele** [tailwindlabs/tailwindcss.com#629]
https://tailwindcss.com/docs/align-content (e.g. content-center) only works with `flex-wrap` added. The exampes don't list `flex-wrap`. This took me quite a while to discover. Would be good if `flex-wrap` is added in the examples...

Link to reproduce: https://play.tailwindcss.com/6cV6HKnG34

**Comment by simonswiss** [comment]
Hey!

Yeah, since we're talking about _multi-row_ flexbox, `flex-wrap` is somewhat implicit, but I agree that it would help making it more visible in the examples, since `align-content` won't work without it.

I'll merge your PR, thanks for that 👍
