### ISSUE TITLE
Installation Page (Gatsby): does not show adding gatsby-plugin-postcss

### ISSUE THREAD

**Issue by rabah** [tailwindlabs/tailwindcss.com#647]
Hi all. So...

The docs are correct on the Gatsby Installation page in everything including adding gatsby-plugin-postcss as a dependency, but it does not include the adding of the plugin to the gatsby config file. Tailwind won't work unless its added I believe. 

```javascript
module.exports = {
  plugins: [`gatsby-plugin-postcss`]
}
```

**Comment by simonswiss** [comment]
Hey 👋

Good catch - and looks like the PR below fixes it! 

https://github.com/tailwindlabs/tailwindcss.com/pull/653

**Comment by simonswiss** [comment]
Closing this issue as it's been merged - thanks again for pointing that out 👍
