### ISSUE TITLE
Nextjs documentation enhancement

### ISSUE THREAD

**Issue by adokce** [tailwindlabs/tailwindcss.com#648]
In [Next.js Tailwind docs](https://tailwindcss.com/docs/guides/nextjs), there are instructions of how to set up a Next.js project. In addition to this, it think it would be a cool idea if there is a template for next apps (and other frameworks too if they support it like next) via create next-app as described in [Nextjs documentation](https://nextjs.org/docs/api-reference/create-next-app).

We'd need to add a template project inside some existing or a new repo.
The command would look like 
`npx create-next-app -e https://github.com/tailwindlabs/tailwindcss.com/tree/master/templates/nextjs`
or
`yarn create next-app -e https://github.com/tailwindlabs/tailwindcss.com/tree/master/templates/nextjs`

If this is something tailwind team would like to have, I'd do the PR

**Comment by simonswiss** [comment]
Hey!

That's an interesting idea/approach. We have built some example code samples for the guides, but still thinking about what's the best way to make them available. They currently live in another repo.

I like the idea of `templates`, although everytime a handy abstraction like that is created, it runs the risk of becoming stale when one of the underlying technologies get updated.

That said, we're going to be maintaining these guides anyway, so maintaining the "companion template/example" is not adding a lot of extra burden.
