### ISSUE TITLE
Installation instructions for Webpacker (Ruby on Rails)

### ISSUE THREAD

**Issue by mingan** [tailwindlabs/tailwindcss.com#65]
Today, I installed Tailwind on a project using Webpacker (Ruby gem wrapping Webpack to work with Ruby on Rails). Webpacker uses PostCSS by default but it relies on `.postcssrc.yml` instead of `postcss.config.js`. It's not apparent how to apply the instructions to another format. The information is not impossible to find (e.g. [in this issue](https://github.com/tailwindcss/tailwindcss/issues/381#issuecomment-364788064) in another context) but I think it would be useful to mention it explicitly in the installation instructions.

My question is, if such a section would be welcome and where to place it? I'd go after Laravel Mix.

**Comment by simonswiss** [comment]
We started releasing integration guides on the new Tailwind CSS website. No Rails guide just yet, but there is one in the works.

**Comment by adamwathan** [comment]
I've captured this on our internal roadmap to add to the docs 👍🏻 In the mean time, check out this new official Rails project:

https://github.com/rails/tailwindcss-rails
