### ISSUE TITLE
focus:outline-none on search bar

### ISSUE THREAD

**Issue by iHildy** [tailwindlabs/tailwindcss.com#658]
![image](https://user-images.githubusercontent.com/25069719/101271766-77fbd600-374b-11eb-97f0-439c824459fa.png)

Can you please add `focus:outline-none` to the search bar?

Maybe you could replace it with a `ring` of some sort?

**Comment by bradlc** [comment]
Hey @iHildy, thanks for the suggestion. I don't think it is necessary to change the focus style here. Most links on the docs site are using the browser's default focus styles 👍
