### ISSUE TITLE
Updating Installation Docs for Laravel Mix

### ISSUE THREAD

**Issue by jdsimcoe** [tailwindlabs/tailwindcss.com#66]
Hey @adamwathan and Tailwind crew! I love Tailwind. I just did a fresh setup on a Statamic site and found that Jeffrey Way's [laravel-mix-tailwind](https://github.com/JeffreyWay/laravel-mix-tailwind) plugin was a bit simpler than the Installation instructions [found here](https://tailwindcss.com/docs/installation) for integrating Tailwind with Laravel Mix:

```js
var tailwindcss = require('tailwindcss');

mix.sass('resources/sass/app.scss', 'public/css')
  .options({
    processCssUrls: false,
    postCss: [ tailwindcss('./path/to/your/tailwind.js') ],
});
```

With the Mix plugin it simplifies to this:

```js
require('laravel-mix-tailwind')

mix
  .sass('resources/sass/app.scss', 'public/css')
  .tailwind()
```

Thought this might help other folks, but open to your thoughts.

**Comment by jdsimcoe** [comment]
FWIW, I'm happy to open a PR to change the documentation but wanted to discuss it with y'all first.

**Comment by simonswiss** [comment]
Hey!

I am aware that the reply is almost 2 years later 😅

While this makes the code a little cleaner, it also adds an extra layer of dependency, that may at some point become out of date, stop being maintained etc.

In this particular case, I don't think it would be hard to collaborate with Jeffrey if something needs to be updated, but as a general rule of thumb, we try to avoid adding layers of abstraction unless they bring significant added value.

While `laravel-mix-tailwind` is definitely neat, I don't think that the gains are big enough here to justify adding this dependency.

Now I know that both packages are built by the same person - Jeffrey - and this would probably be fine... I'm still going to make the call that it's not worth adding it in the official integration guides using Laravel Mix.

Thanks for the suggestions though, and apologies for the late, late reply 😅

**Comment by jdsimcoe** [comment]
All good! Honestly I don't really use Mix as much anymore, so good call. Tailwind has grown quite a bit since then.

**Comment by simonswiss** [comment]
Going to close this issue then - thanks for getting back 👍
