### ISSUE TITLE
What is the license of the code in the docs?

### ISSUE THREAD

**Issue by terrry5** [tailwindlabs/tailwindcss.com#665]
I've already posted this on the discussions page on the tailwindcss repository page but I found that this may be a better place to ask. 

I can't find any mention of license of the documentation, specifically the code examples included there. I want to use some of those code snippets verbatim in a program I'm writing for my dissertation (educational non-commercial use) and I'm not sure if it's ok.

**Comment by adamwathan** [comment]
Hey! Any examples in the documentation are totally fine to use anywhere, consider them MIT licensed. This actual website is not MIT licensed though, so it's a bit tricky to bake that information into the repository. Totally free to use those examples though.
