### ISSUE TITLE
Doc version selector for v2 missing on v1 website

### ISSUE THREAD

**Issue by fvanwijk** [tailwindlabs/tailwindcss.com#668]
On tailwindcss.com there is a version selector to view the docs for latest v1.
When you click it will switch the website to v1.tailwindcss.com.

It is not possible to navigate back to v1 because the version selector on that website does not contain the v2 option.

**Comment by simonswiss** [comment]
Yeah, the v1 website is litereally the same than it was before v2 existed (and therefore no link to v2).

Same happens with v 0.x which doesn't have a dropdown at all so you're stuck there.

I might have a look into it 👍

**Comment by bradlc** [comment]
Merged #635 which added this 👍
