### ISSUE TITLE
Add Vue cli/UI install instruction

### ISSUE THREAD

**Issue by aparajita** [tailwindlabs/tailwindcss.com#67]
Those using vue-cli 3 or Vue UI will most likely install Tailwind through this plugin:

https://github.com/ky-is/vue-cli-plugin-tailwind

It would be good to put that in the Installation section of the docs.

**Comment by simonswiss** [comment]
Hey!

We have now added integration guides to the new Tailwind CSS 2.0 website, one of them being about Vue 3 (with Vite) 🎉

Considering the `vue-cli-plugin-tailwind` has been archived, I will now close this issue 👍
