### ISSUE TITLE
switch language

### ISSUE THREAD

**Issue by juukee** [tailwindlabs/tailwindcss.com#670]
cant we switch language now？

**Comment by simonswiss** [comment]
Hello!

What do you mean by switching language?

**Comment by juukee** [comment]
I mean multi language, for example, I need to translate into Chinese, Japanese。

**Comment by simonswiss** [comment]
Oh, of course, I see!

Currently, the documentation is only available in English.

**Comment by juukee** [comment]
> Oh, of course, I see!
> 
> Currently, the documentation is only available in English.
> 

next-i18next, like this,Will this be available in the future?

**Comment by adamwathan** [comment]
Unfortunately no plans to offer the documentation in multiple languages as I write all of the documentation and I only speak English, so I can't properly maintain them in other languages.
