### ISSUE TITLE
naming your colors with CSS custom properties results in "incomplete" util-classes

### ISSUE THREAD

**Issue by PutziSan** [tailwindlabs/tailwindcss.com#694]
In https://tailwindcss.com/docs/customizing-colors#naming-your-colors you say: 

> You could even define these colors using CSS custom properties (variables) to make it easy to switch themes on the client (...) tailwind.config.js: (...) `primary: 'var(--color-primary)'` (...) In your CSS (...) ` --color-primary: #5c6ac4;`

But  if I declare my variables like this, I cannot use tailwind-color-utilities which depends on variables (e.g. bg-opacity). 

I was able to get the color-primary stuff with css variables working with the following configuration:

```javascript
// tailwind.config.js
function toOpacityVar(opacityVariable) {
  // e.g. for background-image gradient utils opacityVariable is undefined, in this case use 1 as default (always 100% opacity per default)
  return opacityVariable ? `var(${opacityVariable})` : 1;
}

module.exports = {
  theme: {
    colors: {
      primary: ({ opacityVariable }) => `rgba(var(--color-primary-rgb), ${toOpacityVar(opacityVariable)})`,
      secondary: ({ opacityVariable }) => `rgba(var(--color-secondary-rgb), ${toOpacityVar(opacityVariable)})`,
      // ...
    }
  }
}
```

```css
/* In your CSS */
:root {
  --color-primary-rgb: 69, 145, 155;
  --color-secondary-rgb: 218, 18, 125;
  /* ... */
}

@tailwind base;
@tailwind components;
@tailwind utilities;
```

Maybe you want to add a hint in the docs, that with your configuration bg-opacity is not working. Or if you want you could also use the idea from above and add it to your docs :-)

If you have a lot of custom colors you could also extract this into another util function, like:

```javascript
// tailwind.config.js with helper-function
function toOpacityVar(opacityVariable) {
  // e.g. for background-image gradient utils opacityVariable is undefined, in this case use 1 as default (always 100% opacity per default)
  return opacityVariable ? `var(${opacityVariable})` : 1;
}
function toColorFromVariable(rgbValuesVariableName) {
  return ({ opacityVariable }) => `rgba(var(${rgbValuesVariableName}), ${toOpacityVar(opacityVariable)})`;
}

module.exports = {
  theme: {
    colors: {
      primary: toColorFromVariable("--color-primary-rgb"),
      secondary: toColorFromVariable("--color-secondary-rgb"),
      // ...
    }
  }
}
```

**Comment by adamwathan** [comment]
I've added a note to the docs to link to this example repository that shows how to do what you've described:

https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo

Thanks!
