### ISSUE TITLE
Proposal: Document considerations around CSS Grid

### ISSUE THREAD

**Issue by brasilikum** [tailwindlabs/tailwindcss.com#70]
I propose we add the conclusion coming from here https://github.com/tailwindcss/tailwindcss/issues/32.

The section could be called `A note on CSS Grids` so that folks find it when they search the documentation.

I can contribute a pull request if the maintainers think it's a good idea.

**Comment by schmidtflo** [comment]
Maybe also add a direct link in this section to the CSS Grid Plugin.
