### ISSUE TITLE
Why I can't change property on focus

### ISSUE THREAD

**Issue by Winexcel** [tailwindlabs/tailwindcss.com#704]
I want to change border width by focus, on my input

`<input id="emailAddress2" class="bg-gray-500 border border-white focus:outline-none focus:border-2" type="text">`

but i can't do it because this class doesn't exists. 

Of course i can create some new element for this thing but in actually why it wasn't be add?

Thanks in advance fo the reply!

**Comment by josempineiro** [comment]
We have the same issue!
It seems that focus:border-n styles are not being generated
