### ISSUE TITLE
Would you consider writing a Chinese document ?

### ISSUE THREAD

**Issue by Gitsifu** [tailwindlabs/tailwindcss.com#705]

**Comment by natedunn** [comment]
I literally came here to see if there was an issue/discussion for this (or internationalization in general) and just my luck this was posted a few days ago. I think Chinese documentation would be great, followed by Spanish. However this would likely be a huge undertaking that Adam and the team would likely need to hire out for, or some native/experienced speaker would need to put in a lot of effort to contribute. That being said, the team might have some great ideas already in place, so I don't want to speak for them. This is just my take.

**Comment by adamwathan** [comment]
Hey! Unfortunately we can't maintain any official translations as I only speak English, and there would be no way for us to keep the translations up to date if a contributor who does speak another language decided to stop maintaining it. Community members are welcome to maintain third-party translations though, we just can't make any first-party promise to maintain them.
