### ISSUE TITLE
Update guide 404's

### ISSUE THREAD

**Issue by colbygarland** [tailwindlabs/tailwindcss.com#717]
I am on version `^1.8.7` and when I run `npm run prod`, I get the notice of the upcoming breaking changes (great!) 

However, when I follow the link provided in the terminal (https://tailwindcss.com/docs/upcoming-changes) I get a 404 page.

**Comment by adamwathan** [comment]
Good catch, I've just deployed a redirect that sends that to the v1 docs 👍🏻 Thanks.
