### ISSUE TITLE
Suggestion to clarify string concatenation issue for class names in production

### ISSUE THREAD

**Issue by AdrianwithaW** [tailwindlabs/tailwindcss.com#719]
Just spent a bit of time debugging some dynamic class names I was generating which weren't working in production, eventually discovering the note about PurgeCSS requiring a class name in its entirety to work.

![Screen Shot 2021-01-20 at 10 02 36 PM](https://user-images.githubusercontent.com/3616913/105151762-37c1ad00-5b6b-11eb-8492-c7156167bbb4.png)

The documentation is correct but would just like to suggest also adding the below syntax as being one that doesn't work (using a Vue computed variable as an example of implementation):

```
computed: {
  computedClass() {
    var rand = Math.random();
    return `concat-class-${rand}`;
  }
}
```

Appreciate it's pretty similar but I've run into this issue before with another project (I forget the tool in use) where the currently documented method doesn't work, but the above example *did* so didn't anticipate this was the issue at first.

Obviously just a suggestion ¯\_(ツ)_/¯ love Tailwind, keep up the great work 👍

**Comment by adamwathan** [comment]
Thanks for the suggestion! Like you mentioned I don't think this is adding anything that's not already explained and I hesitate to add too much Vue-specific stuff to the docs so I think will just leave as-is for now, but would be happy to review a pull request if someone has ideas on how to explain this in a more clear/obvious way without turning it into too much of a wall of a text.
