### ISSUE TITLE
Add documentation for cli `build` command's new `--no-autoprefixer` flag

### ISSUE THREAD

**Issue by rsimp** [tailwindlabs/tailwindcss.com#722]
Please add the new `--no-autoprefixer` flag for the `build` command into your documentation. Often autoprefixer is not wanted. The CLI does not minify (despite the website saying it does if NODE_ENV is set to production), and if you're using autoprefixer via create react app or via your own configuration you don't want tailwindcss to be running it as well.

It was not obvious that this flag even existed until I read the source code, and it's very useful.

**Comment by adamwathan** [comment]
Added.
