### ISSUE TITLE
Remove documentation stating that the tailwindcss cli will minify your css

### ISSUE THREAD

**Issue by rsimp** [tailwindlabs/tailwindcss.com#723]
Even when you set NODE_ENV=production the cli will not minify your css output. Yet the website specifically says: 

> "This will make sure Tailwind removes any unused CSS and minifies the CSS file for best performance. Read our separate guide on optimizing for production to learn more."

Even if that behavior is the intent of tailwindcss, it should be removed from all 2.0.X documentation versions until the bug is fixed. If there is no intent to have the cli tool minify, it can just be removed and never added back.

**Comment by adamwathan** [comment]
Updated thanks.
