### ISSUE TITLE
Better Create React App Installation documentation

### ISSUE THREAD

**Issue by rsimp** [tailwindlabs/tailwindcss.com#724]
The create react app installation guide instructs using craco to rewire create react app. This is a pretty extreme solution and not actually necessary. While Rewiring is still zero config, doing so wipes responsibility of new bugs from the much larger react team and moves it to the craco project. Rewiring or ejecting should not be your default installation instructions if you can help it. Instead it should be under advanced usage or something of that nature.

Instead just instruct users to use the built-in cli to build their tailwind css into a source folder (making sure to use the "--no-autoprefixer" flag). Then simply import the generated css file in `index.js`. Create react app will then handle vendor prefixing (for dev and prod) and minimizing (for prod) the generated css. You can then instruct users to source control the built css, or modify the `build` and `start` commands in `package.json` to build this css before running the corresponding `react-scripts`

Alternatively you could have the user skip create react app altogether by outputting into the `public` folder and adding a link to the file in `index.html`. However if this is the case you'd want the cli to be able to minify the css as well, which it currently is not. This may just be a bug I'm not sure.

**Comment by adamwathan** [comment]
We've tried lots of different approaches including this one and unfortunately just deem the developer experience too poor to recommend this approach. Having to manually rebuild your CSS every time you change it or run two separate processes (one for the CRA server and one for watching your CSS) just sucks :/ When writing the framework-specific integration guides we are trying to do it in a way that truly integrates Tailwind into the existing build process. You are of course welcome to build your own CSS however you want though — if you prefer doing it the way you've outlined then go for it 👍🏻
