### ISSUE TITLE
[feature] SvelteJS guide

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [tailwindlabs/tailwindcss.com#728]
[SvelteJS](https://svelte.dev) is a rapidly growing JavaScript compiler framework, that leaded the latest [State of JS survey](https://2020.stateofjs.com/en-US/technologies/front-end-frameworks/). It would be nice to have some 'official' guide to use tailwind with svelte because it's a little bit difficult for a beginner to get started with both because of the special configuration you have to do with svelte to get tailwind up and running. 

If there are any objections to this please let me know 🙂

**Comment by adamwathan** [comment]
Hey good suggestion! We have one already started and it's on the list for the next batch of guides we hope to publish in the next month or so 👍🏻 Going to close as we've got it captured on our roadmap internally.
