### ISSUE TITLE
Dark mode does not come out of the box and configuration is in fact required

### ISSUE THREAD

**Issue by Sainan** [tailwindlabs/tailwindcss.com#732]
![image](https://user-images.githubusercontent.com/63328889/105837502-12033080-5fcf-11eb-8b27-734a60b19211.png)

Wow, that sounds good, let's click "Learn more"!

![image](https://user-images.githubusercontent.com/63328889/105837508-162f4e00-5fcf-11eb-8e00-dde4db2b8b40.png)

It does not come out of the box, and configuration is in fact required.

**Comment by adamwathan** [comment]
lol the decision to disable it by default was made after I wrote this copy, good catch 😅  Fixing.
