### ISSUE TITLE
Commas are missing in "Creating a preset" example configuration

### ISSUE THREAD

**Issue by dance2die** [tailwindlabs/tailwindcss.com#734]
## Issue

Commas are missing in [Creating a preset](https://tailwindcss.com/docs/presets#creating-a-preset) example.  
The error occurs when copy-pasted in play.tailwind.css (https://play.tailwindcss.com/JzAw1ijTfB?file=config)

![image](https://user-images.githubusercontent.com/8465237/105913130-67086c00-5ffa-11eb-8b7d-bd0ab26b79a9.png)

## Suggested Fix

Commas need to be added for extended `flexGrow` and `zIndex` configurations.

```js
    extend: {
      flexGrow: {
        2: '2',
        3: '3'
      },
      zIndex: {
        60: '60',
        70: '70',
        80: '80',
        90: '90',
        100: '100'
      },
    }
```

**Comment by adamwathan** [comment]
Fixed, thanks.
