### ISSUE TITLE
Pink Excluded?

### ISSUE THREAD

**Issue by erik06** [tailwindlabs/tailwindcss.com#751]
I'm having trouble understanding this part of the documentation about excluding colors. In the documentation it says it excludes "Pink" but "Pink" is shown in the code example. Very confused, is this a typo? 

https://tailwindcss.com/docs/customizing-colors#disabling-a-default-color

**Comment by adamwathan** [comment]
Definitely a mistake in the docs, pink shouldn't be there! Whoops.

**Comment by erik06** [comment]
Thanks Adam!

**Comment by adamwathan** [comment]
Thanks for the fix!
