### ISSUE TITLE
Green Colors from V1 are wrong

### ISSUE THREAD

**Issue by erik06** [tailwindlabs/tailwindcss.com#752]
The provided Green colors in the v1 config are not from v1. 

I'm seeing that `green-400` should be: `#31c48d` not `#68d391` - I suspect that all the green values, if not more are completely wrong. Or maybe the Tailwind UI colors are not being shown here? Are there any v1 configs available for Tailwind UI?

Specifically I'm upgrading a v1 Tailwind UI project to vanilla Tailwind 2 and having all sorts of issues.

From:
https://tailwindcss.com/docs/upgrading-to-v2#configure-your-color-palette-explicitly

**Comment by adamwathan** [comment]
Hey! Tailwind CSS v1 does not use the same colors as the @tailwindcss/ui plugin, correct. We discovered that the original v1 colors were not good enough when building Tailwind UI, which is the main reason we ended up shipping that plugin with the different palette.

Here are the colors from the plugin:

https://unpkg.com/browse/@tailwindcss/ui@0.7.2/colors.js

Hope that helps!

**Comment by erik06** [comment]
Spent two days trying to figure out why the green looked just so off! Hahaha, this makes total sense, my apologies!!!
