### ISSUE TITLE
Bug: Divide Color page of the doc only shows gray for all divide borders

### ISSUE THREAD

**Issue by ghost** [tailwindlabs/tailwindcss.com#755]
[Divide Color](https://tailwindcss.com/docs/divide-color) page only shows gray for all the divide borders.

By looking at the source code I figured lines 26 & 27 of **src/pages/docs/divide-color.mdx** could be the problem.

By replacing **--divide-opacity** with **--tw-divide-opacity** fixes the bug, like below

```diff
borderColor: Array.isArray(css['border-color'])
-               ? css['border-color'][0].replace('var(--divide-opacity)', '1')
-               : css['border-color'].replace('var(--divide-opacity)', '1'),
+               ? css['border-color'][0].replace('var(--tw-divide-opacity)', '1')
+               : css['border-color'].replace('var(--tw-divide-opacity)', '1'),
```

Can send a **Pull Request** if you guys accept.

**Comment by adamwathan** [comment]
Ah good catch yeah would love a PR!
