### ISSUE TITLE
Add note on Gatsby install about FOUC in dev

### ISSUE THREAD

**Issue by alanwsmith** [tailwindlabs/tailwindcss.com#764]
I went through the documentation for how to install Tailwind 2 on Gatsby. 

    https://tailwindcss.com/docs/guides/gatsby

The install went fine, but I saw a flash of unstyled content when I fired up the site in dev.

I expected the site to behave the same in dev and prod. So, I thought this was an issue and tried fo find a solution. Luckily, a discord user clued me into the fact that it might not be issue in prod. Sure enough, when I did `gatsby build` the issue appears to have been resolved. 

I'm new to both Gatsby and React, so that may be expected behavior but it certainly threw me. 

I suggest adding a note to the end of the docs letting folks know that they might see the issue in dev.

**Comment by adamwathan** [comment]
Hey! Will definitely keep this in mind and if it comes up again we can think of a good way to incorporate it into the docs. I would have to set up a Gatsby site to reproduce this to try and understand what's even happening so I can document it properly, and I don't think I'm going to have a chance to do that any time soon so for now will just let Google help people find this issue if they search "tailwind gatsby fouc". Again if it becomes a recurring thing people are bringing up we can definitely document it 👍🏻
