### ISSUE TITLE
Vite - no example for "Referecning in JavaScript"

### ISSUE THREAD

**Issue by mickeyvip** [tailwindlabs/tailwindcss.com#765]
Hello, and thank you!

I was wondering whether it's possible to add an example for referencing the theme in JavaScript in Vue3 Vite setup.

I tried to follow the general instructions, but since `tailwind.config.js` is CommonJS module and Vite works with ES6 modules, I get an exception:

```
Uncaught SyntaxError: The requested module '/tailwind.config.js' does not provide an export named 'default'
```

My setup:

```js
// src/theme.js
import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from '../tailwind.config.js'

export default resolveConfig(tailwindConfig)
```

```vue
<!-- src/components/HelloWorld.vue -->
<template>
  <button @click="state.count++">count is: {{ state.count }}</button>
</template>

<script setup>
import { reactive } from 'vue'
import theme from '../theme'

console.log(theme)

const state = reactive({ count: 0 })
</script>

<style scoped>
</style>
```

Tank you in advance.

**Comment by mickeyvip** [comment]
Got an answer from https://github.com/schelmo at the "Didcussions":

In order to reference local files that are in CommonJS format we need to configure Vite to have an alias for them and import them as Node module + extension:

```js
// vite.config.js
// --------------

import path from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      'tailwind.config.js': path.resolve(__dirname, 'tailwind.config.js'),
    },
  },
  optimizeDeps: {
    include: [
      'tailwind.config.js',
    ]
  }
})
```

```js
// src/theme.js
// ------------

import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from 'tailwind.config.js' // IMPORTANT that the path is NOT relative, only the file name

export default resolveConfig(tailwindConfig)
```

```vue
<!-- src/components/HelloWorld.vue -->

<template>
  <button @click="state.count++">count is: {{ state.count }}</button>
</template>

<script setup>
import { reactive } from 'vue'
import theme from '../theme'

console.log(theme) // logs the imported theme!

const state = reactive({ count: 0 })
</script>

<style scoped>
</style>
```

Still, would be great to have this example in the docs.

Thank you.

**Comment by adamwathan** [comment]
Hey glad you found an answer! If this is a common issue people run into then can definitely consider adding it to the docs. To me it sounds more like a generic "how do I import CJS into an ESM project?" type of question though which isn't really Tailwind specific, and although it would be great to cover as much stuff as possible in our own docs we do have to make sure we are prioritizing the stuff that's uniquely a Tailwind problem since we're only a handful of people, and the docs are really just me. Can definitely reconsider expanding that documentation if it's a common problem though 👍🏻

**Comment by mickeyvip** [comment]
Hi @adamwathan.

Thank you for the reply.

I am not sure the solution to importing `theme.js` is a problem of importing CJS into an ESM, because each bundler has its own way of doing it and Vite has a fasade for Rollup so doing it in Vite is probably not the same as in Rollup.

Also, I tried to google "import commonjs into ESM" and didn't really find an answer.
I tried searching the same and the specific error message on Vite's GitHub and also didn't see anything that I found helpful.

As I see it - adding this section to the documentation is something that fully completes the section of using Tailwind with Vite.

On the other hand - it there are no reactions to this issue, people might not need it, or they know how to do it, or they used it and didn't react :)

Anyhow, whether you will be able to add this to the documentation or not - I am grateful for your and your team's work!

Thank you for creating such a great tool!

**Comment by ChrisEdgington** [comment]
The solution described above works for me in vite dev mode, but trying to produce a build still results in a problem with the missing default export: 

```
vite v2.7.0 building for production...
transforming (13) node_modules/object-assign/index.js
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
transforming (1644) node_modules/lodash/_mapToArray.jsError when using sourcemap for reporting an error: Can't resolve original location of error.
✓ 1670 modules transformed.
'default' is not exported by tailwind.config.js, imported by src/pages/page-query.tsx
file: /Users/cedgington/repos/zinc/smidgen/src/pages/page-query.tsx:8:7
 6: import locale from "react-json-editor-ajrm/es/locale/en";
 7: import resolveConfig from "tailwindcss/resolveConfig";
 8: import tailwindConfig from "tailwind.config.js";
           ^
 9: const twConfig = resolveConfig(tailwindConfig);
10: const editorColors = {
error during build:
Error: 'default' is not exported by tailwind.config.js, imported by src/pages/page-query.tsx
    at error (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:158:30)
    at Module.error (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:12382:16)
    at Module.traceVariable (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:12767:29)
    at ModuleScope.findVariable (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:11559:39)
    at Identifier.bind (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:6419:40)
    at CallExpression.bind (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:5021:31)
    at CallExpression.bind (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:9396:15)
    at VariableDeclarator.bind (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:5025:23)
    at VariableDeclaration.bind (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:5021:31)
    at Program.bind (/Users/cedgington/repos/zinc/smidgen/node_modules/rollup/dist/shared/rollup.js:5021:31)```

**Comment by dmaynard24** [comment]
Hey @ChrisEdgington I was running into the exact same problem. After some digging (and reading Adam's idea that this is more of an issue of "how do I import CJS into an ESM project?"), I found a way to resolve that error. You need to treat the **tailwind.config.js** file like a CommonJS import by adding this to your Vite config:

```js
build: {
  commonjsOptions: {
    include: ['tailwind.config.js', 'node_modules/**'],
  },
},
```

So, your Vite config will look something like this:
```js
// vite.config.js
// --------------

import path from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      'tailwind.config.js': path.resolve(__dirname, 'tailwind.config.js'),
    },
  },
  optimizeDeps: {
    include: [
      'tailwind.config.js',
    ]
  },
  build: {
    commonjsOptions: {
      include: ['tailwind.config.js', 'node_modules/**'],
    },
  },
})
```

If Vite continues gaining popularity, this may be worth adding to the official documentation. Maybe on this page or something: https://tailwindcss.com/docs/guides/vite

**Comment by Psycarlo** [comment]
Using the solutions above and still get:

```
Could not find a declaration file for module 'tailwindcss/resolveConfig'
Cannot find module 'tailwind.config.js' or its corresponding type declarations
```

My Vue component (script setup):
```
...
import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from 'tailwind.config.js'
...
```

_Everything seems to function fine when I run in development tho. When I try to build, other the other hand..._

**Comment by lobo-tuerto** [comment]
@dmaynard24 Solution works like a charm. Thank you.

**Comment by lobo-tuerto** [comment]
I wrote a blog post for those wanting to have something to point people to: https://lobotuerto.com/notes/import-tailwind-config-in-vite

**Comment by lobo-tuerto** [comment]
@Psycarlo You are using TypeScript, so that's the TypeScript compiler complaining about something not being right.

Try adding this to your `vite-env.d.ts` file (or add a new one):

```ts
declare module 'tailwind.config.js' {
  const config: Config
  export default config
}
```

I touch on that on the blog post I linked above.

**Comment by manudefrutosvila** [comment]
> Using the solutions above and still get:
> 
> ```
> Could not find a declaration file for module 'tailwindcss/resolveConfig'
> Cannot find module 'tailwind.config.js' or its corresponding type declarations
> ```
> 
> My Vue component (script setup):
> 
> ```
> ...
> import resolveConfig from 'tailwindcss/resolveConfig'
> import tailwindConfig from 'tailwind.config.js'
> ...
> ```
> 
> _Everything seems to function fine when I run in development tho. When I try to build, other the other hand..._

same here

works in dev, but when build and serve I have error

`ReferenceError: module is not defined`

**Comment by lobo-tuerto** [comment]
@manudefrutosvila Have you tried going through the full solution in the post linked above?

You might have a misconfiguration in your `tsconfig.json` file :thinking: 
Try setting up a new environment and then do a minimal reproduction as outlined in the blog post above.

If you need a guide on seting up a new Vite + Vue 3 + TypeScript environment you can follow [this guide.](https://lobotuerto.com/notes/build-a-vue3-typescript-dev-environment-with-vite)

If you follow that guide, and the post above afterwards it'll work in dev and no problems when building.

**Comment by manudefrutosvila** [comment]
> @manudefrutosvila Have you tried going through the full solution in the post linked above?
> 
> You might have a misconfiguration in your `tsconfig.json` file 🤔 Try setting up a new environment and then do a minimal reproduction as outlined in the blog post above.
> 
> If you need a guide on seting up a new Vite + Vue 3 + TypeScript environment you can follow [this guide.](https://lobotuerto.com/notes/build-a-vue3-typescript-dev-environment-with-vite)
> 
> If you follow that guide, and the post above afterwards it'll work in dev and no problems when building.

Thanks for the answer.
I don't use typescript in this project. But I'll try again.

**Comment by lidorbt-esggo** [comment]
> @Psycarlo You are using TypeScript, so that's the TypeScript compiler complaining about something not being right.
> 
> Try adding this to your `vite-env.d.ts` file (or add a new one):
> 
> ```ts
> declare module 'tailwind.config.js' {
>   const config: Config
>   export default config
> }
> ```
> 
> I touch on that on the blog post I linked above.

it doesn't work for some reason. did you create a new file?

**Comment by lidorbt-esggo** [comment]
> I wrote a blog post for those wanting to have something to point people to: https://lobotuerto.com/notes/import-tailwind-config-in-vite

it doesn't work for some reason. did you create a new file?

EDIT: I've rewritte my code according to your instructions.
it throws `Cannot find module 'tailwind-config' or its corresponding type declarations.`

I tried to change it to `tailwind.config` but it still doesn't seem to work. do you have any idea?
* note -  it works when I run it locally but fails on build
thanks!
