### ISSUE TITLE
Order of @tailwind directives breaks responsive features, but this is not documented.

### ISSUE THREAD

**Issue by codemile** [tailwindlabs/tailwindcss.com#766]
The following styles should hide the `<div>` on small screens, and make it *flex* on all other screens.

```
<div class="hidden md:flex"></div>
```

This functionality does not work if the `@tailwind` directives are in the wrong order. If the `screens` directives are applied first in the CSS, then `hidden` takes selector priority and `md:flex` will have no effect.

*wrong:*

```
@tailwind base;
@tailwind components;
@tailwind screens;
@tailwind utilities;
```

*correct:*

```
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind screens;
```

This side effect is not documented.

https://tailwindcss.com/docs/functions-and-directives

It should show as a priority **warning** to readers that the order is very important to use the library, and functionality is broken if the directives are in the wrong order.

**Comment by adamwathan** [comment]
Hey! This is the designed behavior, the `@screens` directive specifically exists to override where the responsive utilities are injected. If you inject them before the utilities that's where they will end up, and your CSS will behave accordingly. 

We explain what it does here:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/4323180/109420667-b21ef180-79a1-11eb-9721-ecf78f1ea6bb.png">

I've personally never actually used this directive in a project, it's best to let Tailwind handle it for you automatically. That exists only as an escape hatch for a couple of power users.

This is the first time this has come up in the 3.5 years the framework has been around so I don't think this is a common enough thing people run into to be worth adding additional noise to the documentation.
