### ISSUE TITLE
Your website says KB, it should say kB

### ISSUE THREAD

**Issue by themrflibble** [tailwindlabs/tailwindcss.com#780]
### Describe the problem:

Your website states how little storage it needs, and says KB. This is Kelvin Bytes, it makes no sense. It should say kB, or KiB (if 1024 bytes).

### Link to a minimal reproduction:

See above

**Comment by adamwathan** [comment]
Thanks, next time though you want the "Documentation Issue" button:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/4323180/110729264-631c5c00-81ec-11eb-96e9-e509fb2691e5.png">
