### ISSUE TITLE
Implement OpenSearch for documentation search

### ISSUE THREAD

**Issue by mklein994** [tailwindlabs/tailwindcss.com#789]
Browsers such as [Firefox][firefox-opensearch] and [Chrome][chrome-opensearch] provide ways to add custom search engines that can be triggered with keywords. Websites can expose this functionality by implementing the [OpenSearch][opensearch] specification.

This would allow one to start searching the documentation directly from the address bar.

It would be great if this could be implemented on https://tailwindcss.com, since that Algolia has documentation on how to do that:

https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/opensearch/react/

[firefox-opensearch]: https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox
[chrome-opensearch]: https://support.google.com/chrome/answer/95426
[opensearch]: https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by mklein994** [comment]
I see this was already attempted before in pull #107. Was there a reason this was declined?

**Comment by adamwathan** [comment]
Hey! Yeah weird I have no recollection of why that was closed — I never close PRs without at least a comment so there must have been more to the story there 🤔 Might just be because that PR was still open when we rewrote the site in Next.js and it was no longer relevant.

I'm open to a PR for this still, but am probably not going to be able to prioritize it myself any time soon.

Going to close as a "not going to work on myself" but again totally open to seeing a PR for it 👍🏻

**Comment by mklein994** [comment]
I did a bit of digging and found out some more information about Algolia. The tailwindcss.com website uses [DocSearch](https://docsearch.algolia.com), a service from Algolia that provides search capabilities for websites with little hassle. DocSearch will scrape the website daily, then create an index which can be queried using their API. Algolia provides the UI integration and infrastructure [all for free](https://docsearch.algolia.com/docs/faq#how-much-does-it-cost). Pretty nifty.

Since the magic is on Algolia's side, I don't really know what the `template` attribute on `<Url>` should be:

```xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>shortName</ShortName>
  <Description>description</Description>
  <Url type="text/html" method="get" template="https://mysite.com?q={searchTerms}"/>
                                          <!-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ what goes here? -->
  <InputEncoding>UTF-8</InputEncoding>
  <Image height="32" width="32"type="image/png">linkToImage</Image>
</OpenSearchDescription>
```

I found a [blog post](https://www.algolia.com/blog/ux/taking-documentation-search-to-new-heights-with-algolia-and-autocomplete/) briefly mentioning OpenSearch support coming to Algolia:

> ## What’s next?
>
> We’re thrilled to be releasing this experience, and we see it as the first step of building best in class search experience that helps and inspires our users. Here are ideas we already have in the pipe:
>
> - 🎙 **Algolia Answers & Voice Search support** with the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API)
> - 💻 **OpenSearch support** to search in the Algolia docs from your browser’s URL bar
>
> This makes us confident about releasing the v1 of [Autocomplete](https://autocomplete.algolia.com/), as we’ve now used it in several projects with high visibility.
>
> We’re also working on bringing all the features of the new Algolia documentation search into [Autocomplete](https://autocomplete.algolia.com/) in the form of plugins. This way, you’ll be able to create a similar experience with your [DocSearch](https://docsearch.algolia.com)-powered documentation site, or using the library directly. Stay tuned on our [Discourse](https://discourse.algolia.com/tag/autocomplete) forum!
>
> *([Algolia UX Blog](https://www.algolia.com/blog/ux/taking-documentation-search-to-new-heights-with-algolia-and-autocomplete/), Dec 14th 2020)*

If I'm reading this correctly, it seems it may be possible in the future to enable OpenSearch support by using a plugin. DocSearch is built on top of Autocomplete, so in theory this might work once it's available. I'll leave this one alone for now, unless they announce an update on this.

**Comment by LXSMNSYC** [comment]
Any updates on this? Kinda helpful to use this feature every time I forgot the class names 😅

**Comment by adamwathan** [comment]
> I'm open to a PR for this still, but am probably not going to be able to prioritize it myself any time soon.
> 
> Going to close as a "not going to work on myself" but again totally open to seeing a PR for it 👍🏻

**Comment by LXSMNSYC** [comment]
Oh sorry, didn't notice it earlier. Looking forward to this feature.
