### ISSUE TITLE
JIT docs are a bit incomplete

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss.com#800]
The new blog & the JIT docs need a bit of work.

Earlier, I had installed `@tailwindcss/jit` so I was able to follow along but new users won't be able to without reading `@tailwindcss/jit` Github README.

Mainly, 2 things are missing from the new blog & JIT docs:

### Installing `@tailwindcss/jit` as a dev dependency

```bash
$ npm i -D @tailwindcss/jit
```

### Adding `@tailwindcss/jit` to `postcss.config.js`

```js
module.exports = {
  plugins: {
    '@tailwindcss/jit': {},
    autoprefixer: {},
  },
}
```

**Comment by adamwathan** [comment]
You don't need that library anymore, JIT is part of Tailwind 2.1 👍🏻 the instructions here are right:

https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode

Just have to install regular `tailwindcss` and set the `mode` option in your config file 👍🏻

**Comment by deadcoder0904** [comment]
Well, I'm using Next.js & the CSS was all gone when I removed `@tailwindcss/jit` after reading the post. I had no styles at all. Therefore, I added it again.

Here's my `tailwind.config.js`:

```js
module.exports = {
  mode: 'jit',
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  .
  .
  .
 }
```

And `postcss.config.js`:

```js
module.exports = {
  plugins: {
    '@tailwindcss/jit': {}, // i should remove this, right?
    autoprefixer: {},
  },
}
```

Anything else to change? Blog mentions to include `purge` script for `public/index.html`. Do I need it for Next.js?

**Comment by adamwathan** [comment]
You need to replace `@tailwindcss/jit` with regular `tailwindcss` and just make sure you are on version 2.1 👍🏻

**Comment by adamwathan** [comment]
The Tailwind website is a Next app too and set up the same way, can take a peak at our source if you need a reference 👍🏻

**Comment by deadcoder0904** [comment]
> You need to replace @tailwindcss/jit with regular tailwindcss and just make sure you are on version 2.1 👍🏻

Oops, I totally forgot that. It works now, thanks & congrats 🎉
