### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by julienallexandre** [tailwindlabs/tailwindcss.com#802]
Hello 🖐,

There is a problem in the documentation with the use of variant customisation which causes an error during compilation. 

It says to add the plugin with: 
`require('tailwindcss-interaction-variants')(), `
but you have to remove the () at the end so that it gives 
`require('tailwindcss-interaction-variants'),`

[https://tailwindcss.com/docs/configuring-variants#using-custom-variants](https://tailwindcss.com/docs/configuring-variants#using-custom-variants)

![tailwindcss-interaction-variant](https://user-images.githubusercontent.com/58303569/113950682-3589f900-9812-11eb-8a2c-0a9a4eefeb65.PNG)

**Comment by simonswiss** [comment]
Hey!

Thanks for pointing that out - I can see that the README in the plugin itself was updated here:

https://github.com/benface/tailwindcss-interaction-variants/commit/ee2a38a6c2c420e721ca0155110dac63e2cecec1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Would you like to open a PR with this change?

If you don't have time for it, no problem, happy to do it, but I wanted to give you a chance to contribute if you're up for it 👍
