### ISSUE TITLE
Edit this page on GitHub

### ISSUE THREAD

**Issue by cajakre** [tailwindlabs/tailwindcss.com#821]
I'd like a link to the respective docs page on GitHub, to propose changes conveniently.

Like Gatsby does: [https://www.gatsbyjs.com/docs/quick-start/](https://www.gatsbyjs.com/docs/quick-start/)

Opinions?

**Comment by adamwathan** [comment]
Hey! Would be open to a PR for this if implemented nicely 👍🏻 Going to close though just because no plans to prioritize this myself.
