### ISSUE TITLE
Plugin documentation: Modifying config

### ISSUE THREAD

**Issue by joneslloyd** [tailwindlabs/tailwindcss.com#823]
Hello,

I've taken a read through the documentation (and even the Tailwind source code) and I can't work out how to _modify_ the config programatically via a plugin.

I was expecting a `modifyVariant` (or similar), like the `addVariant` function.

Are you able to provide any info on this?

**Comment by adamwathan** [comment]
Hey! What would `modifyVariant` actually do, can you explain the specific thing you're actually trying to accomplish?

Plugins can modify the config by providing their own config object to be merged with the user's config:

https://tailwindcss.com/docs/plugins#providing-default-options

**Comment by joneslloyd** [comment]
Hey! Thanks for the super-quick response!

I'm creating an embeddable widget and because of rem-related font size issues (specifically, not being able to know the base font size on the embedding site's `<html>` node) I need to use px.

My plan was to loop through all of the config in a plugin, spot `rem` and convert to `px`.

I was just wondering if there was a way to filter/modify the final config object(?) but it seems, based on your response, that it's best to provide defaults?

Or maybe I can simply iterate the config and then `addVariant`, overwriting the existing ones?

**Comment by adamwathan** [comment]
Variants are for stuff like `hover`, `focus`, dark mode, etc., nothing really to do with pixels vs. rem. Do you actually need to modify other people's config files or do you really just need a config file for your widget project? Another feature you could use is our presets feature which lets you provide a custom base configuration.

Another approach would be to use a PostCSS plugin, there's already one out there that converts rem to pixels:

https://www.npmjs.com/package/postcss-rem-to-pixel

Just stick it after Tailwind in your PostCSS configuration.

**Comment by joneslloyd** [comment]
I see, okay!

I wanted to make it a bit more robust, as I'll be creating other widgets (and will have the same px-to-rem need). Therefore I thought that putting it into a plugin and making it something that can be included in each project would be a bit more 'DRY'.

Presets looks good, but I wanted to be able to handle any `rem` value that I don't know about in advance, in a "set and forget" way. I thought that dynamically modifying whichever config exists would be the best way of achieving this.

I did see that postCSS plugin actually! However I have no idea how to apply it to Tailwind...! So I was going to dynamically modify the config instead (but need to figure out how to save the modified config).

**Comment by joneslloyd** [comment]
Just FYI, I have this so far as a crude implementation of what I wanted to achieve:
```
plugins: [
        require('./rem-to-px.js')({
            baseFontSize: 16,
            toModify: [
                'all'
            ]
        }),
    ],
```
    
And the plugin file itself:
```
const plugin = require('tailwindcss/plugin');

const remToPx = (rem, base) => {
    return rem * base;
};

const makePixelsForThemePart = function (data, base) {

    const pixelData = [];

    for (const [key, value] of Object.entries(data)) {
        if (value.includes('rem')) {

            const num = parseFloat(value, 10);
            const pxNum = remToPx(num, base).toString() + 'px';

            pixelData.push([
                key, pxNum
            ]);
        }
        else {
            pixelData.push([
                key, value
            ]);
        }
    }

    return Object.fromEntries(pixelData);
};

module.exports = plugin.withOptions((options) => {
    const { baseFontSize = 16, toModify = ['all'] } = options;
    return function ({ config }) {
        const theme = config('theme');
        for (const [key, value] of Object.entries(theme)) {
            if ('all' === toModify[0] || toModify.includes(key)) {
                const updatedData = makePixelsForThemePart(value, baseFontSize);
                //UPDATE CONFIG
            }
        }
    };
});
```

**Comment by joneslloyd** [comment]
Re-reading everything, perhaps the question I should actually be asking is:

How can I use postcss plugins in Tailwind?

**Comment by adamwathan** [comment]
How are you building your project currently, using the Tailwind CLI? Tailwind itself is a PostCSS plugin so most people have it configured as part of their `postcss.config.js` file, where you can add any other plugins you need.

**Comment by joneslloyd** [comment]
I am actually using Tailwind via [Twin](https://github.com/ben-rogerson/twin.macro), so there isn't a `postcss.config.js` file.

Having said that, I can try creating one and see if this works.

**Comment by adamwathan** [comment]
Ah ok so that won't work then since you're not _actually_ using Tailwind at all in that case. Twin is a total reimplementation so I can't speak to what's possible there or not.

**Comment by joneslloyd** [comment]
It does use Tailwind, as everything I'm doing in my `tailwind.config.js` file is applied to the site, and all classes work as normal (etc), as well as sample Tailwind plugins.

Without wanting to take up too much of your time, which of the methods (using a plugin as the fix) would you say is best as the solution here?

**Comment by joneslloyd** [comment]
My bad; you’re completely right that Twin reimplements a lot of Tailwind functionality (exposing many of the same APIs). Sorry!
