### ISSUE TITLE
[accessibility] Use <code> or <pre> or translate="no" for table inline code fragments.

### ISSUE THREAD

**Issue by NikitaIT** [tailwindlabs/tailwindcss.com#828]
## Use `<code>` or `<pre>` for table inline code fragments. And `translate="no"` for code-like nav menu items.
A simple example of finding out that something went wrong is google-translate chrome built-in plagin(you may need to switch the operating system language for the built-in translator to appear in chrome).

## Example 1 (code still in eng):
![broken names](https://user-images.githubusercontent.com/16810067/116842146-e69a6e00-abdb-11eb-8a23-65f173d57363.png)

## Example 2 (code still in eng):
![image](https://user-images.githubusercontent.com/16810067/116843255-a9d07600-abdf-11eb-905e-aa182cc4870e.png)

In this example, of course, I did not correctly, correctly `td > code`.

## `code` role (copy-paste from W3C aria code spec)
A section whose content represents a fragment of computer code.

The primary purpose of the code role is to inform assistive technologies that the content is computer code and thus may require special presentation, in particular with respect to synthesized speech. More specifically, screen readers and other tools which provide text-to-speech presentation of content SHOULD prefer full punctuation verbosity to ensure common symbols (e.g. "-") are spoken.

## translate="no" (copy-paste from Whatwg html spec)

Similarly, a page author could write markup that provides information for a translation tool that they are intending to use:

```html
<p>The third <span data-mytrans-de="Anspruch">claim</span> covers the case of 
<span translate="no">HTML</span>
 markup.</p>
```
In this example, the "data-mytrans-de" attribute gives specific text for the MyTrans product to use when translating the phrase "claim" to German. However, the standard translate attribute is used to tell it that in all languages, "HTML" is to remain unchanged. When a standard attribute is available, there is no need for a custom data attribute to be used.

## Links
- [W3C: aria `code` spec](https://w3c.github.io/aria/#code)
- [Whatwg: html `code` spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element)
- [Whatwg: html `translate="no"` spec](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes)
- [MDN: translate attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate)

I can look for a link to w3c's translation guidelines. But I hope you take my word for it - this is important.

**Comment by adamwathan** [comment]
Fixed, thanks! Didn't know about the `translate` attribute, that's super cool.
