### ISSUE TITLE
[broken-example]: object-fit: fill not works with SVG

### ISSUE THREAD

**Issue by NikitaIT** [tailwindlabs/tailwindcss.com#829]
See [docs/object-fit](https://tailwindcss.com/docs/object-fit#fill).

Chrome 90.0.4430.85

![object: fill](https://user-images.githubusercontent.com/16810067/116855847-5d466400-abfa-11eb-9f92-dfb06091c0d2.png)

How to solve: Replace with png and add an explanation.

**Comment by adamwathan** [comment]
Fixed, thanks!
