### ISSUE TITLE
Feature Request: Add `gap` to flexbox section

### ISSUE THREAD

**Issue by alesso-x** [tailwindlabs/tailwindcss.com#830]
Add `gap` to flexbox section. There is a [gap](https://tailwindcss.com/docs/gap) section for Grid but `gap-{size}` is also supported in flexbox. The reasoning for this feature request is that it was not immediately clear that I can use the same utility.

https://play.tailwindcss.com/gyA2FxD9pN

**Comment by adamwathan** [comment]
Updated the docs, thanks.
