### ISSUE TITLE
Order of Width classes to show `w-px` a little more prominently

### ISSUE THREAD

**Issue by ahuggins** [tailwindlabs/tailwindcss.com#841]
Submitting this issue, because I almost missed this class, and thought maybe others might too.

If you go to https://tailwindcss.com/docs/width and see the big list of classes available for width, it starts with `w-0` and is ascending through `w-max`. Which makes sense, but the one class I was looking for was `w-px` (width: 1px).

It does exist, but is sort of lost in the scroll list.

I see the way the scroll list is populated is by some utility functions, so guessing there is not fine tuning for the sort.

I guess I would have expected the order to be `w-0` `w-px` `w-0.5` etc.

I realize that this is extremely extremely minor, but sometimes you need that 1px and it makes sense to me to list by order of value. (Though I realize ordering by value would mess the percentage widths order completely). So maybe this is the unfortunate way it has to be.

**Comment by adamwathan** [comment]
Updated it so the `px` value is sorted alongside the numeric values 👍🏻
