### ISSUE TITLE
Laravel installation failed

### ISSUE THREAD

**Issue by laraveladmin-cn** [tailwindlabs/tailwindcss.com#844]
root@e3caf14def40:/var/www/laravel/laraveladmin# npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat @tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9 --legacy-peer-deps
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "_autoprefixer": name cannot start with an underscore
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "_which": name cannot start with an underscore

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-14T03_27_52_327Z-debug.log

**Comment by adamwathan** [comment]
Hey! Best to ask for help with this sort of thing in our discussion forums or Discord server.
