### ISSUE TITLE
tailwindcss docs related to Angular is not up-to-date

### ISSUE THREAD

**Issue by SvenAtGit** [tailwindlabs/tailwindcss.com#847]
https://tailwindcss.com/docs/guides/angular

Angular 12 is released, they mention support for Tailwindcss. Sinds v11.2 release Angular added support for Tailwind CSS.  It's not needed to use custom-webpack any more.

Please update the tailwindcss documentation.

I followed next procedure to make it working, there is probably a cleaner way than the NODE_ENV
https://dev.to/arni1981/adding-tailwindcss-to-an-angular-11-2-project-kep

best regards S

**Comment by armedi** [comment]
Hi @SvenAtGit, I created a PR addressing this issue https://github.com/tailwindlabs/tailwindcss.com/pull/851

**Comment by adamwathan** [comment]
Hey! That Angular guide was actually never properly finished which is why we don't link to it anywhere in the docs, not sure how people even discovered it 😅

I've deleted the guide for now until we have time to actually write a proper one and verify it works.
