### ISSUE TITLE
Smart quotes in documentation

### ISSUE THREAD

**Issue by gingersoulrecords** [tailwindlabs/tailwindcss.com#849]
Wasn’t sure where to put this, but I’ve been poring over the Tailwind docs while also using a ‘smart quotes’ converter to write my own docs. 

So, I noticed that Tailwind isn’t using ‘smart quotes’ for contractions. 

![image](https://user-images.githubusercontent.com/8520042/119144177-69ae2780-ba16-11eb-9f1d-cdaa22a24f02.png)

It’s nickpicky AF but I figured a crew that sweats type enough to make a ‘prose’ class might appreciate a slight leveling up here. See https://smartquotesforsmartpeople.com/ for more on smart quotes.

I used https://www.smartquotes.info/converter.html to type this. Peace. 

Dave Bloom

**Comment by adamwathan** [comment]
Added a remark plugin to handle 99% of this, maybe some one-off stuff that still has it but whatever, not gonna crawl through hundreds of files to fine them, hah.

**Comment by gingersoulrecords** [comment]
Word. Kinda just wanted to know how you’d go about it. DB
