### ISSUE TITLE
angular guide seem to be broken

### ISSUE THREAD

**Issue by makuzaverite** [tailwindlabs/tailwindcss.com#853]
[this](https://tailwindcss.com/docs/guides/angular) returns  404

**Comment by simonswiss** [comment]
Hey!

Did you find a link to that URL from somewhere on the docs website? 

We don't have an angular guide on the [Integration Guides page](https://tailwindcss.com/docs/installation#integration-guides), mind sharing where you found that link?

Thanks in advance! 🙏

**Comment by makuzaverite** [comment]
Thanks for reaching out it was indexed on top of my google search yesterday `25/05/2021` by `tailwindcss setup with angular`

**Comment by simonswiss** [comment]
Oh, interesting. I can't find anything with the same search. We did have a guide in _draft_, which _may_ have been accidentally merged and indexed a while ago?

Anyway, thanks for letting me know. I'll take a look 👍

**Comment by adamwathan** [comment]
Yeah we had accidentally published an unfinished draft several months ago, and since it wasn't complete and very out of date I recently removed it completely. Hopefully can publish an up to date guide in the future 👍🏻
