### ISSUE TITLE
Transition property not present in the first example

### ISSUE THREAD

**Issue by alvarlagerlof** [tailwindlabs/tailwindcss.com#857]
https://tailwindcss.com/docs/transition-property 

The page above is about `transition-{properties} `, yet the first example does not have use it.

**Comment by adamwathan** [comment]
Hey! The docs example is correct, the `transition` class transitions several properties for you and is part of that category of utilities. Just like we have `shadow` with no suffix but also suffixed versions like `shadow-md`.

Can see it in the class table on that page, third one:

![image](https://user-images.githubusercontent.com/4323180/120078859-6999d180-c07f-11eb-9fe6-20212f4e6080.png)
