### ISSUE TITLE
Copying npm install tailwindcss Is Not Working on Safari

### ISSUE THREAD

**Issue by jyoo** [tailwindlabs/tailwindcss.com#865]
Hi!

When I tried to click the copy button to copy 'npm install tailwindcss' on the main page, I noticed that it is not working if I use Safari (v14.0.3). It works well on Chrome (v90) and Firefox (v89), so I think it is specifically related to Safari. While I think this is a relatively less important issue, does anyone know how to solve it?

Thank you :D

**Comment by adamwathan** [comment]
Hey, thanks, fixed now!

https://github.com/tailwindlabs/tailwindcss.com/commit/c6cc34b1ae27acbe6b2a03f63e707a514c964674
