### ISSUE TITLE
Container screens option is missing

### ISSUE THREAD

**Issue by royvanv** [tailwindlabs/tailwindcss.com#866]
On the documentation page for [container](https://tailwindcss.com/docs/container), there is no mention of the screens option.

The following configuration for creating a full width container (up until the `lg` breakpoint) works, for example:

```js
// tailwind.config.js
module.exports = {
    ...
    theme: {
        container: {
            screens: {
                xs: '100%',
                lg: '1024px',
            },
        },
    }
};
```

**Comment by adamwathan** [comment]
Hey! Yeah this is kind of intentional, I regret adding that option and it doesn't behave intuitively for most people so it's really only there to avoid introducing a breaking change but I don't want to encourage more people to use it.

If you need different behavior than what the container does by default, I would recommend just using the max width utilities directly:

```html
<div class="lg:max-w-screen-lg">
  <!-- ... -->
</div>
```

That does the same thing as the container based on your above configuration.

**Comment by royvanv** [comment]
Thanks for the lightning fast reply! 

The downside to that approach is that you need to explicitly define your paddings per breakpoint and center it with `mx-auto`.

**Comment by adamwathan** [comment]
Yeah in that case I would recommend just disabling the container plugin and writing your own container class that behaves the way you want:

```js
// tailwind.config.js
module.exports = {
  // ...
  corePlugins: {
    container: false
  }
}
```

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .container {
    @apply mx-auto px-4;
  }
  @screen lg {
    .container {
      @apply max-w-screen-lg px-8;
    }
  }
}
```

...or similar 👍

**Comment by adamwathan** [comment]
I forgot there's actually one more option for you — the container class has responsive variants, so you could also do this:

```html
<div class="lg:container">
  <!-- ... -->
</div>
```

That says "only behave like a container on lg screens and above", so below that, it'll just be a full width element.

Can also do this:

```html
<div class="container max-w-full sm:max-w-full md:max-w-full">
  <!-- ... -->
</div>
```

Verbose but just another option.
