### ISSUE TITLE
Typo in the 2.2.0 release notes

### ISSUE THREAD

**Issue by geisterfurz007** [tailwindlabs/tailwindcss.com#871]
In the [2.2.0 release notes](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#deprecate-blur-0-for-blue-none-in-the-default-theme) it says `blur-0` was deprecated for blu>e<-none which caught me off-guard for a moment.

It's just a tiny thing and I don't know how far people read these but maybe it could be updated (including the link to the header in [Changes and deprecations](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#changes-and-deprecations).

**Comment by adamwathan** [comment]
Hah thank you, fixed!
