### ISSUE TITLE
Tailwind "quick search" in the docs is not working

### ISSUE THREAD

**Issue by VyrekXD** [tailwindlabs/tailwindcss.com#873]
Go to https://tailwindcss.com/ and use control + k and try to search something, it doesnt work:

![test](https://vyrekxd.is-inside.me/d2mA4zNI.gif)

**Comment by adamwathan** [comment]
I think this was a temporary/network thing as it's working as expected here:

https://user-images.githubusercontent.com/4323180/122657919-9482bd00-d135-11eb-92ea-723fcf27c2ad.mov

Thanks for the heads up though regardless!
