### ISSUE TITLE
Missing Oficial Docs for Angular

### ISSUE THREAD

**Issue by searleser97** [tailwindlabs/tailwindcss.com#880]
I see tailwind has official documentation specific for some UI Frameworks. Why not include Angular as well ?

**Comment by adamwathan** [comment]
Hey! Just haven't had time to write the Angular one, same reason we are missing:

- Svelte
- Rails
- Django
- Phoenix
- Elm
- Adonis
- WordPress
- Symfony
- Express
- Meteor
- Spring
- Ember
- Sails
- Sinatra

...etc. Only a small team and have to always weigh priorities against each other, and right now have other things that are higher on the list.

In the mean time though there are tons of tutorials out there for setting Angular up with Tailwind, like this one:

https://dev.to/angular/setup-tailwindcss-in-angular-the-easy-way-1i5l
