### ISSUE TITLE
Request to add new section "How It Works" in docs

### ISSUE THREAD

**Issue by Iftakharpy** [tailwindlabs/tailwindcss.com#887]
Today, I was going through the parcel's doc page. I found it very easy to understand how the bundler works because they had a very good explanation for every section. There is another advanced section called "How It Works".

I think it would be a nice addition to TailwindCSS's docs page.

**Comment by adamwathan** [comment]
Hey thanks for the suggestion! I think this is a cool idea and will definitely keep it in mind for a future project as time permits 🙏 

Going to close as no concrete plans to do this right away, but I do appreciate the suggestion and hopefully can put something together down the road.
