### ISSUE TITLE
Typo in documentation#requirements

### ISSUE THREAD

**Issue by vjpr** [tailwindlabs/tailwindcss.com#892]
https://tailwindui.com/documentation#requirements

Component leaks through

![Screen Shot 2021-07-10 at 9 16 49 pm](https://user-images.githubusercontent.com/281413/125174244-355c1980-e1c4-11eb-93f3-b60a6b0ccda0.png)

**Comment by adamwathan** [comment]
Hey! This isn't actually the case as far as I can tell:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/4323180/126048487-4ee945c9-4dcd-48c1-9164-0e6b7f0631ca.png">

I suspect you have that Chrome extension installed that tries to convert code blocks on tailwindui.com to JSX maybe?

**Comment by vjpr** [comment]
Ah yes that's it. I have that Chrome extension. Will file a bug against it.
