### ISSUE TITLE
CSS purge example eats a lot of resources

### ISSUE THREAD

**Issue by Sly-Little-Fox** [tailwindlabs/tailwindcss.com#895]
When you scroll to that example (on main page), it starts doing something very heavy, eating near 100% of CPU. Maybe it's because my computer is very old, but why do you need to load devices with unnecessary operations? I suggest to add some button like "Start example".

**Comment by Sly-Little-Fox** [comment]
Bump

**Comment by adamwathan** [comment]
Hey! Sorry this is causing issues on your machine, unfortunately not a priority for us to make any changes here. It's definitely a heavy page that does a lot but that's just the trade-off we accepted when deciding to tell the story the way we have on that page.

**Comment by Sly-Little-Fox** [comment]
> 
> 
> Hey! Sorry this is causing issues on your machine, unfortunately not a priority for us to make any changes here. It's definitely a heavy page that does a lot but that's just the trade-off we accepted when deciding to tell the story the way we have on that page.

Sad....
