### ISSUE TITLE
WhiteSpace NoWrap

### ISSUE THREAD

**Issue by MNouroozi** [tailwindlabs/tailwindcss.com#906]
Wrong spec in documentation 

| Class | Properties |
|--|---|
| `.whitespace-no-wrap` | `white-space: nowrap;` |

Which must be:
| Class | Properties |
|--|---|
| `.whitespace-nowrap` | `white-space: nowrap;` |

**Comment by adamwathan** [comment]
Hey! What page is that showing up on incorrectly? Did a global search through the whole docs and it only appears in the upgrade guide, where it's correct.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/4323180/127708134-019d8ef7-7329-42b6-a9f9-0babc3b09b24.png">

**Comment by adamwathan** [comment]
Going to close as I can't find this error myself — if it's still an issue a PR would be great, there's an "Edit this page on GitHub" link at the bottom of every docs page, thanks ❤️
