### ISSUE TITLE
Not all `group-*` utilities are documented

### ISSUE THREAD

**Issue by royvanv** [tailwindlabs/tailwindcss.com#910]
The documentation does not mention that beside `group-hover` and `group-hover` you can use the same principle for the other pseudo selectors. I would have expected this information on the [Hover, Focus, & Other States](https://tailwindcss.com/docs/hover-focus-and-other-states) page.

For example the following code works out of the box in JIT mode (just pretend we are looping in something like Vue or Alpine):
```html
<!-- Visible output: "Riggs and Murtaugh" -->
<div class="group">
    Riggs 
    <span class="group-last:hidden">and</span>
</div> 
<div class="group">
    Murtaugh
    <span class="group-last:hidden">and</span>
</div>
```

The section [Creating custom variants](https://tailwindcss.com/docs/hover-focus-and-other-states#creating-custom-variants) also has an example for `required` which has been added to the framework.

**Comment by adamwathan** [comment]
Hey! Yeah none of the JIT-only stuff is documented outside of the main JIT page currently. When JIT is no longer in preview and becomes the default for v3, the docs will be thoroughly updated.
