### ISSUE TITLE
Add template for NextJS and TypeScript

### ISSUE THREAD

**Issue by Nautman** [tailwindlabs/tailwindcss.com#918]
Hi!

I think it would be very helpful if there was a template for TailwindCSS with NextJS and TypeScript. Currently there is a template for JavaScript, with [the reference on this docs page](https://github.com/tailwindlabs/tailwindcss.com/blob/bc63d339425a6eeec2e52493a295e13c0a126e9b/src/pages/docs/guides/nextjs.mdx).

I believe it wouldn't be very difficult to create such a template. Perhaps I can help in developing one? I would simply copy the JavaScript template and convert whatever I can into TypeScript.

Does anyone know if it would be worthwhile if I created a template?

Thanks!

**Comment by Nautman** [comment]
I just created a PR to add an example, see here: https://github.com/vercel/next.js/pull/28262

**Comment by Nautman** [comment]
I just closed my PR because they don't want unnecessary templates that make maintaining more difficult.

**Comment by adamwathan** [comment]
Hey! Yeah as you guessed the best place to submit an actual template is to Next itself, as we don't actually offer this ourselves. I think our integration guide for Next contains everything you need to know for the Tailwind side of things even if you are using TypeScript so going to close as I don't think there's any action to take here. Thanks for the suggestion though!
