### ISSUE TITLE
Update Create React App Installation docs

### ISSUE THREAD

**Issue by tim-phillips** [tailwindlabs/tailwindcss.com#920]
Create React App Installation doc can be updated to use latest `postcss` (v8) and `autoprefixer` (v10) versions.

https://tailwindcss.com/docs/guides/create-react-app

CRA currently uses `postcss@8.3.5` with which `autoprefixer@^10` is compatible:

https://github.com/facebook/create-react-app/blob/749a76d291d6b07681d0941eeb23112c6970d3c4/packages/react-scripts/package.json#L58

**Comment by adamwathan** [comment]
Hey thanks! It does on `main` but the latest actual release is from February and still uses old versions of everything:

https://github.com/facebook/create-react-app/releases/tag/v4.0.3

I don't think we can update these docs until CRA 5.0 is actually released?

**Comment by tim-phillips** [comment]
Ah, I see, thanks for the reply! Closing issue. 

Just FYI, I didn't get any error message and I'm not experiencing any problems with the new versions while using react-scripts v4.0.3.
