### ISSUE TITLE
Nuxtjs docs are outdated

### ISSUE THREAD

**Issue by tejasc0** [tailwindlabs/tailwindcss.com#923]
Now no need to install tailwindcss@latest along with @nuxtjs/tailwindcss as nuxtjs/tailwindcss support postcss

**Comment by tejasc0** [comment]
ref: [Nuxtjs setup](https://tailwindcss.com/docs/guides/nuxtjs)

**Comment by reinink** [comment]
Hey thanks for reporting this @tejasc0! I just tried this, and you're right, it works without explicitly installing `tailwindcss@latest`. I also noticed that if you use `create-next-app`, you get a "Tailwind CSS" option, which handles all this for you, so maybe it's worth noting that in this guide as well.

I'm going to chat with the team to figure out the best way to make these changes, and will follow up once that's been done. 👍

**Comment by dacoto97** [comment]
Also for nuxt 3 you can see this: #973
https://tailwindcss-com-git-fork-dacoto97-patch-1-tailwindlabs.vercel.app/docs/guides/nuxtjs

**Comment by tejasc0** [comment]
> Also for nuxt 3 you can see this: #973 https://tailwindcss-com-git-fork-dacoto97-patch-1-tailwindlabs.vercel.app/docs/guides/nuxtjs

When will this deploy in production?

**Comment by dacoto97** [comment]
I suppose when nuxt3 be out of beta

**Comment by reinink** [comment]
Hey, just an update here. With the new v3.0 website launch, we've updated all the guides to make sure they are working, including the "[Install Tailwind CSS with Nuxt.js](https://tailwindcss.com/docs/guides/nuxtjs)" guide 👍
