### ISSUE TITLE
Custom Inset

### ISSUE THREAD

**Issue by globalexport** [tailwindlabs/tailwindcss.com#931]
Please have a look at the two following config code examples for positive and negative values:
https://tailwindcss.com/docs/top-right-bottom-left#top-right-bottom-left-scale

`inset` has two different locations here (below `theme` and below `extend`).

**Comment by reinink** [comment]
Hey there, so both of these options are possible. The first is an example of how you would edit the existing `inset` scale:

```diff
 // tailwind.config.js
  module.exports = {
    theme: {
      inset: {
        '0': 0,
        // ...
-       '64': '16rem',
+       '1/5': '20%',
      }
    }
  }
```

The second example explains how you would add an additional value to the default `inset` scale:

```diff
  // tailwind.config.js
  module.exports = {
    theme: {
      extend: {
        inset: {
+         '-16': '-4rem',
        }
      }
    }
  }
```

Put differently, when you modify `theme.inset`, you are replacing the entire default `inset` scale, but when you modify `theme.extend.inset` you are simply adding additional values to the default `inset` scale.

You can read more about customizing your Tailwind config here: https://tailwindcss.com/docs/configuration

I hope that helps! 👍

**Comment by globalexport** [comment]
Thank you for the explanation!
