### ISSUE TITLE
Printable docs

### ISSUE THREAD

**Issue by trevyn** [tailwindlabs/tailwindcss.com#934]
It would be nice to have a "print" URL that contains everything from https://tailwindcss.com/docs/ in one page, so it could be easily printed out.

And/or a PDF version of the docs. :)

**Comment by adamwathan** [comment]
Hey thanks for the suggestion! I'm going to close as not a bug/not something we are able to look at right away but definitely making note of the idea and maybe it's something we can tackle in the future if it would be helpful to people ❤️

**Comment by trevyn** [comment]
Clone repo

`perl -lne "print for /pages\['(.*?)'\]/g" src/navs/documentation.js | awk "{printf \"import Comp%d from './%s.mdx';\n\n<Comp%d />\n\n\", NR, \$0, NR}" > src/pages/docs/print.mdx`

`npm install & npm run dev`

http://localhost:3000/docs/print
