### ISSUE TITLE
Feedback button leads to wrong repo

### ISSUE THREAD

**Issue by oneWaveAdrian** [tailwindlabs/tailwindcss.com#940]
When I press the button for a missing item in the search I end up at Algolia's repo instead of Tailwind's. This is quite confusing, is there a way for better wording?
<img width="736" alt="Screenshot 2021-09-08 at 10 28 49" src="https://user-images.githubusercontent.com/8450519/132474973-8e8946b8-cb3a-422c-8e67-cd3a617b814c.png">

**Comment by adamwathan** [comment]
Hey! This is actually correct, Algolia maintains all the search stuff for docs sites themselves, and any improvements have to be made there, not here.
