### ISSUE TITLE
`px` equivalent besides `rem` in docs

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss.com#946]
I like the Tailwind Intellisense because it gives me `px` styles now besides `rem` so I don't have to do the math.

But when I open `tailwind.config.js` to use `theme('borderRadius.md')` then I don't understand its value in `px` as Intellisense doesn't work there yet.

So I open docs & there it is in `rem` again. Would love to have `px` values as I try to copy CSS from online & then convert it to `px` but I don't know if I need to use JIT mode or the equivalent `px` value exists in `rem`.

A comment would be helpful like `rounded-md => border-radius: 0.375rem; /* 6px */`

**Comment by iamandrewluca** [comment]
While the PR is in draft. One can use this [PR Vercel build URL](https://tailwindcss-com-git-fork-iamandrewluca-rem-516a2d-tailwindlabs.vercel.app/) to take leverage of this functionally

**Comment by deadcoder0904** [comment]
@iamandrewluca that looks great 👌

**Comment by iamandrewluca** [comment]
@deadcoder0904 rebased PR on top of new Tailwind Docs

**Comment by deadcoder0904** [comment]
not sure, why you tagged me? looking good i guess but i dont have merge rights & anyways adam will take care of it like he said :)

**Comment by iamandrewluca** [comment]
Tagged you just to inform 🙂 Adam said that will look at it in the future, at the moment, no resources

**Comment by reinink** [comment]
Hey @deadcoder0904, thanks for sharing this idea!

Thanks to the work of @iamandrewluca, we've been able to get this added to the website — it's deploying to production right now. 🥳

<img width="482" alt="image" src="https://user-images.githubusercontent.com/882133/155757969-58ef3712-5a80-4e8c-8b83-72a52633abc6.png">
