### ISSUE TITLE
figma community file example text sizes don't match styles

### ISSUE THREAD

**Issue by cairin** [tailwindlabs/tailwindcss.com#948]
In the [community file](https://www.figma.com/community/file/958383439532195363) the examples for `7xl`, `8xl` and `9xl` are all styled as `6xl`. The styles are in the file, it's just the examples that aren't styled correctly:

*How it currently looks*
![How it currently looks](https://user-images.githubusercontent.com/10084084/133226845-deb0b0f0-c3cb-4a6d-b624-29f978626b80.png)

*How it should look*
![How it should look](https://user-images.githubusercontent.com/10084084/133226887-01d52a47-a0b7-402d-9328-66321aeac667.png)

**Comment by adamwathan** [comment]
Good catch, should be fixed now thanks!
