### ISSUE TITLE
Show demos for drop shadow in docs

### ISSUE THREAD

**Issue by akashshyamdev** [tailwindlabs/tailwindcss.com#962]
Hey guys,

I think there should be a demo that shows the different levels of `drop-shadow`. 7 White boxes that show utilise each class like `drop-shadow-none`, `drop-shadow-xl` etc.

What do you think about this problem? I'd love to take up this issue, especially if it's part of hacktoberfest! Looking forward to your reply!

Thanks,
Akash

**Comment by adamwathan** [comment]
Hey! Yep agree and working on it in the next few weeks 👍🏻 

Going to close as it's easier for us to stay on top of issues when open issues just represent bugs to fix rather than improvements, but this is in progress and should be part of the new website launch later this month.
