### ISSUE TITLE
Where would I find the Figma Tailwind UI?

### ISSUE THREAD

**Issue by AyaanZaveri** [tailwindlabs/tailwindcss.com#977]
I know you guys discontinued it, but where would I find the last version?

**Comment by adamwathan** [comment]
Hey! Here: https://tailwindui.com/documentation#figma-assets

Tailwind UI Discord is best place for these sorts of questions btw 👍🏻

**Comment by AyaanZaveri** [comment]
Thanks for the response, also I found 2 files on Figma Community with the Official Tailwind UI:
https://www.figma.com/community/file/968950247359551580
https://www.figma.com/community/file/995699927571503463
