### ISSUE TITLE
`@use` alternative in Installation section

### ISSUE THREAD

**Issue by MysticEarth** [tailwindlabs/tailwindcss.com#982]
The [Installation](https://tailwindcss.com/docs/installation#include-tailwind-in-your-css) section mentions multiple alternatives about how to import the Tailwind directives.

When you want to combine Tailwind with the latest version of Angular Material however, none of these are correct. Angular Material requires the use of `@use` to import different SASS stylesheets. So, adding a section to the docs explaining this alternative would be helpful I think:

```scss
@use '~tailwindcss/base';
@use '~tailwindcss/components';
@use '~tailwindcss/utilities';
```

**Comment by adamwathan** [comment]
Thanks for the suggestion! I will keep this in mind when we add an integration guide for Angular.
