### ISSUE TITLE
General / Issue solving: Can't install tailwind inside a Google Drive (formerly Google Filestream) folder

### ISSUE THREAD

**Issue by rorar** [tailwindlabs/tailwindcss.com#985]
**What happened*
While trying to install tailwind inside a GGrive folder to keep my work in sync for my studies, 
mkdir errors were thrown at me.
![image](https://user-images.githubusercontent.com/44790144/141368194-6154c2e0-ffaf-43e3-aa34-5987d90ee0b5.png)

**What I did**
- I was using the follwing npm "script":
`npm install -D tailwindcss@latest postcss@latest autoprefixer@latest`
- I tried to add the folders manually

**Solution**
- Do not use a GDrive Folder
- It might be helpful against frustration and headache (for students / starters like me) 
to give a hint about this issue.
If you google for the issue it takes a long time to stumble over the solution.
Just a small note should be enough.

**Comment by OyewoleOyedeji** [comment]
Have you tried doing the command in administrative mode

**Comment by OyewoleOyedeji** [comment]
Since the issue has been resolved, you can closed this issue 😐

**Comment by reinink** [comment]
Hey thanks for reporting this, as it can be helpful for others. Going to close this since it's resolved 👍
