### ISSUE TITLE
https://www.tailwindcss.cn/docs/extracting-components document content error

### ISSUE THREAD

**Issue by zaleGZL** [tailwindlabs/tailwindcss.com#996]
![image](https://user-images.githubusercontent.com/20339327/145235208-d03190ec-601d-4d89-82aa-0fd8f05508d0.png)

https://www.tailwindcss.cn/docs/extracting-components

**Comment by reinink** [comment]
Hey there, we don't manage the tailwindcss.cn website — this is managed completely separate from us by someone in the community. I'd recommend letting the maintainer of this fork know 👍
